### ISSUE TITLE
using pyannote on torch cpu only

### ISSUE THREAD

**Issue by manish-kumar-iisc** [pyannote/pyannote-audio#1017]
torch with cuda is taking a lot of space, compared with torch cpu only [LINK](https://pytorch.org/get-started/previous-versions/)
i am running pyannote on cpu only, but want to use torch with cpu libs only, but it is giving below error
```
Traceback (most recent call last):
  File "./utils/pyannote_vad.py", line 3, in <module>
    from pyannote.audio import Pipeline
  File "/home/manish/pyannote_env_sep/lib/python3.7/site-packages/pyannote/audio/__init__.py", line 29, in <module>
    from .core.inference import Inference
  File "/home/manish/pyannote_env_sep/lib/python3.7/site-packages/pyannote/audio/core/inference.py", line 33, in <module>
    from pyannote.audio.core.io import AudioFile
  File "/home/manish/pyannote_env_sep/lib/python3.7/site-packages/pyannote/audio/core/io.py", line 38, in <module>
    import torchaudio
  File "/home/manish/pyannote_env_sep/lib/python3.7/site-packages/torchaudio/__init__.py", line 1, in <module>
    from torchaudio import _extension  # noqa: F401
  File "/home/manish/pyannote_env_sep/lib/python3.7/site-packages/torchaudio/_extension.py", line 27, in <module>
    _init_extension()
  File "/home/manish/pyannote_env_sep/lib/python3.7/site-packages/torchaudio/_extension.py", line 21, in _init_extension
    torch.ops.load_library(path)
  File "/home/manish/pyannote_env_sep/lib/python3.7/site-packages/torch/_ops.py", line 110, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libtorch_hip.so: cannot open shared object file: No such file or directory
```

- torch with cpu version: pip install torch==1.10.1+cpu torchvision==0.11.2+cpu torchaudio==0.10.1 -f https://download.pytorch.org/whl/torch_stable.html
- installing pyannote using: git clone https://github.com/pyannote/pyannote-audio.git, cd pyannote-audio, git checkout develop, pip install .

how to use torch with cpu only for pyannote?

**Comment by manish-kumar-iisc** [comment]
"pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu"
with latest version of torch cpu, pyannote is working.
