### ISSUE TITLE
Cannot apply data augmentation

### ISSUE THREAD

**Issue by ngocpham97** [pyannote/pyannote-audio#1033]
**Describe the bug**
Hello, I want to agmentation data training and follow the instructions in [training_a_model.ipynb](https://github.com/pyannote/pyannote-audio/blob/develop/tutorials/training_a_model.ipynb) but doesn't work.

**To Reproduce**
****
```bash
import os
os.environ["PYANNOTE_DATABASE_CONFIG"] = '/home/ngocpt/Desktop/AMI-diarization-setup/pyannote/database.yml'
os.environ["CUDA_VISIBLE_DEVICES"] = '0,1'


from types import MethodType
from torch.optim import SGD
import pytorch_lightning as pl
from pyannote.database import get_protocol
from pyannote.audio.models.segmentation import PyanNet
from pyannote.audio.tasks import Segmentation
from torch_audiomentations import AddBackgroundNoise
from torch.optim.lr_scheduler import ExponentialLR


ami = get_protocol('AMI.SpeakerDiarization.only_words')

augmentation = AddBackgroundNoise("/home/ngocpt/Desktop/musan")
seg_task = Segmentation(ami, duration=5, max_num_speakers=4, augmentation=augmentation, batch_size=128)
model = PyanNet(task=seg_task, sincnet={'stride': 10})
trainer = pl.Trainer(gpus=2, strategy='ddp', max_epochs=100)
trainer.fit(model) 
```

**This is runtime error**

```AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ngocpt/anaconda3/envs/asr/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ngocpt/anaconda3/envs/asr/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/home/ngocpt/anaconda3/envs/asr/lib/python3.8/site-packages/pyannote/audio/tasks/segmentation/mixins.py", line 331, in collate_fn
    return {"X": augmented.samples, "y": self.adapt_y(augmented.targets.squeeze(1))}
AttributeError: 'Tensor' object has no attribute 'samples'
```
how can i fix it ?

**Comment by ngocpham97** [comment]
Can you explain more clearly? I tried checkout to master branch and reinstall torch-audiomentations but it still gives the above error

**Comment by hbredin** [comment]
`pip install https://github.com/asteroid-team/torch-audiomentations/archive/master.zip`

You might also need to pass option `output_type="dict"` to `AddBackgroundNoise`.
This will become the default behavior in future version of `torch-audiomentations`.

**Comment by hbredin** [comment]
Would you mind contributing a PR that updates the `training_a_model.ipynb` notebook accordingly?
