### ISSUE TITLE
Issue with segmentation model

### ISSUE THREAD

**Issue by petersnias** [pyannote/pyannote-audio#1040]
Hi.  I noticed a change to the segmentation model:  https://huggingface.co/pyannote/segmentation  

Ever since then I'm getting the following error:

Traceback (most recent call last):
  File "test.py", line 3, in <module>
    model = Model.from_pretrained("pyannote/segmentation")
  File "/home/npeters/.local/lib/python3.8/site-packages/pyannote/audio/core/model.py", line 804, in from_pretrained
    loaded_checkpoint = pl_load(path_for_pl, map_location=map_location)
  File "/opt/anaconda/lib/python3.8/site-packages/pytorch_lightning/utilities/cloud_io.py", line 38, in load
    return torch.load(f, map_location=map_location)
  File "/opt/anaconda/lib/python3.8/site-packages/torch/serialization.py", line 607, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/opt/anaconda/lib/python3.8/site-packages/torch/serialization.py", line 882, in _load
    result = unpickler.load()
  File "/opt/anaconda/lib/python3.8/site-packages/torch/serialization.py", line 875, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'torch.torch_version'

Any suggestions?

**Comment by acidcoma** [comment]
same problem

**Comment by hbredin** [comment]
You may try to load the previous version using `pyannote/segmentation@Interspeech2021` instead of `pyannote/segmentation`.
