### ISSUE TITLE
Data loader multithreading does not function

### ISSUE THREAD

**Issue by JenyaPu** [pyannote/pyannote-audio#1041]
The data loader multithreading must be broken (could possibly be the PyTorch Lightning issue).
When I run training with the following task:

```
from copy import deepcopy
import pytorch_lightning as pl
fro pyannote.audio import Model
from pyannote.audio.tasks import Segmentation
from pyannote.database import get_protocol

diar_protocol = get_protocol('MyDatabase.SpeakerDiarization.MyProtocol')
pretrained = Model.from_pretrained("pyannote/segmentation")
seg_task = Segmentation(diar_protocol)
finetuned = deepcopy(pretrained)
finetuned.task = seg_task
trainer = pl.Trainer(max_epochs=10)
trainer.fit(finetuned)
```

The code falls on the trainer.fit(finetuned) line and I get the error with the following traceback:

```
Traceback (most recent call last):
  File "D:\Projects\Python\PoCSpeechEmotion\modules\diarization_model\train_model.py", line 48, in <module>
    main()
  File "D:\Projects\Python\PoCSpeechEmotion\modules\diarization_model\train_model.py", line 42, in main
    trainer.fit(finetuned)
  File "C:\Program Files\Python310\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 770, in fit
    self._call_and_handle_interrupt(
  File "C:\Program Files\Python310\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 723, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 811, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "C:\Program Files\Python310\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1236, in _run
    results = self._run_stage()
  File "C:\Program Files\Python310\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1323, in _run_stage
    return self._run_train()
  File "C:\Program Files\Python310\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1345, in _run_train
    self._run_sanity_check()
  File "C:\Program Files\Python310\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1413, in _run_sanity_check
    val_loop.run()
  File "C:\Program Files\Python310\lib\site-packages\pytorch_lightning\loops\base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\pytorch_lightning\loops\dataloader\evaluation_loop.py", line 154, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "C:\Program Files\Python310\lib\site-packages\pytorch_lightning\loops\base.py", line 199, in run
    self.on_run_start(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\pytorch_lightning\loops\epoch\evaluation_epoch_loop.py", line 88, in on_run_start
    self._data_fetcher = iter(data_fetcher)
  File "C:\Program Files\Python310\lib\site-packages\pytorch_lightning\utilities\fetching.py", line 178, in __iter__
    self.dataloader_iter = iter(self.dataloader)
  File "C:\Program Files\Python310\lib\site-packages\torch\utils\data\dataloader.py", line 368, in __iter__
    return self._get_iterator()
  File "C:\Program Files\Python310\lib\site-packages\torch\utils\data\dataloader.py", line 314, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Program Files\Python310\lib\site-packages\torch\utils\data\dataloader.py", line 927, in __init__
    w.start()
  File "C:\Program Files\Python310\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Program Files\Python310\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Program Files\Python310\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Program Files\Python310\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Program Files\Python310\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle '_thread.RLock' object
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Program Files\Python310\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
```

What fixed it for me is specifying the _num_workers=0_, but this might affect the performance.
```
seg_task = Segmentation(diar_protocol, max_num_speakers=2, num_workers=0)
```
Any value of _num_workers_ parameter other than 0 causes the above error.

**Content of `database.yml`**

```yaml
Databases:
  MyDatabase: ../../samples/diarization/{uri}.wav

Protocols:
  MyDatabase:
    SpeakerDiarization:
      MyProtocol:
        train:
          uri: lists/dataset_diarization_train.lst
          annotation: rttms/dataset_diarization_train.rttm
          annotated: uems/dataset_diarization_train.uem
        development:
          uri: lists/dataset_diarization_development.lst
          annotation: rttms/dataset_diarization_development.rttm
          annotated: uems/dataset_diarization_development.uem
        test:
          uri: lists/dataset_diarization_test.lst
          annotation: rttms/dataset_diarization_test.rttm
          annotated: uems/dataset_diarization_test.uem
```

**Comment by hbredin** [comment]
Most likely a Windows / Python 3.10 / multiprocessing issue.

Windows is not supported by pyannote.audio (though some people were succesful training pyannote models on Windows)

Can you try again on a Linux machine?

**Comment by hbredin** [comment]
Possibly related: https://pytorch-lightning.readthedocs.io/en/latest/guides/speed.html#spawn
