### ISSUE TITLE
Error in torch.hub.load()

### ISSUE THREAD

**Issue by ken-mitamura** [pyannote/pyannote-audio#1044]
**Describe the bug**

Error when executing `torch.hub.load()`

```
$ python
Python 3.8.7 (default, May 10 2022, 02:27:54) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.hub.load('pyannote/pyannote-audio', 'sad', pipeline=True)
Downloading: "https://github.com/pyannote/pyannote-audio/archive/master.zip" to /root/.cache/torch/hub/master.zip
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/local/python-3.8.7/lib/python3.8/site-packages/torch/hub.py", line 382, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/root/local/python-3.8.7/lib/python3.8/site-packages/torch/hub.py", line 408, in _load_local
    hub_module = import_module(MODULE_HUBCONF, hubconf_path)
  File "/root/local/python-3.8.7/lib/python3.8/site-packages/torch/hub.py", line 76, in import_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 915, in get_code
  File "<frozen importlib._bootstrap_external>", line 972, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/torch/hub/pyannote_pyannote-audio_master/hubconf.py'
>>> 
```

I suspect this is due to the removal of `hubconf.py` by the #900 merge.
I have succeeded by specifying an older version (1.1.2).

```
$ python
Python 3.8.7 (default, May 10 2022, 02:27:54) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.hub.load('pyannote/pyannote-audio:1.1.2', 'sad', pipeline=True)
Downloading: "https://github.com/pyannote/pyannote-audio/archive/1.1.2.zip" to /root/.cache/torch/hub/1.1.2.zip
Downloading list of pretrained models and pipelines to "/root/.pyannote/hub/pretrained.yml".
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 901/901 [00:00<00:00, 623kB/s]
Downloading pretrained model "sad_dihard" to "/root/.pyannote/hub/models/sad_dihard.zip".
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.41M/2.41M [00:00<00:00, 16.1MB/s]
/root/local/python-3.8.7/lib/python3.8/site-packages/setuptools/distutils_patch.py:25: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  warnings.warn(
<pyannote.audio.pipeline.speech_activity_detection.SpeechActivityDetection object at 0x7fd1f546fe20>
>>>
```

**environment**

- python 3.8.7
- torch 1.9.1+cu111

**Comment by hbredin** [comment]
Pinning the version is indeed the solution.

Not that pyannote.audio 2.0 has just been released with much  better voice activity detection and speaker diarization pipelines. Models and pipelines are now hosted on Huggingface Hub and loading with `torch.hub` is no longer supported in 2.x branch.

**Comment by chuanma** [comment]
Pinning the version doesn't work for the "dia" model. Based on the last 2 lines of the stack trace below, the "dia" model relies on the "sad_dihard" model of the master branch.

```
>>> torch.hub.load("pyannote/pyannote-audio:1.1.2", "dia", pipeline=True, trust_repo=True)
Downloading: "https://github.com/pyannote/pyannote-audio/zipball/1.1.2" to /root/.cache/torch/hub/1.1.2.zip
Using cache found in /root/.cache/torch/hub/pyannote_pyannote-audio_master
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/torch/hub.py", line 540, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/torch/hub.py", line 569, in _load_local
    model = entry(*args, **kwargs)
  File "/root/.cache/torch/hub/pyannote_pyannote-audio_1.1.2/hubconf.py", line 244, in _generic
    return load_pretrained_pipeline(params_yml.parent)
  File "/usr/local/lib/python3.7/site-packages/pyannote/audio/pipeline/utils.py", line 92, in load_pretrained_pipeline
    pipeline = Klass(**config["pipeline"].get("params", {}))
  File "/usr/local/lib/python3.7/site-packages/pyannote/audio/pipeline/speaker_diarization.py", line 121, in __init__
    sad_scores=self.sad_scores, scd_scores=self.scd_scores
  File "/usr/local/lib/python3.7/site-packages/pyannote/audio/pipeline/speech_turn_segmentation.py", line 99, in __init__
    scores=self.sad_scores
  File "/usr/local/lib/python3.7/site-packages/pyannote/audio/pipeline/speech_activity_detection.py", line 100, in __init__
    self._scores = Wrapper(self.scores)
  File "/usr/local/lib/python3.7/site-packages/pyannote/audio/features/wrapper.py", line 217, in __init__
    raise ValueError(msg)
ValueError: Could not load sad_dihard model from torch.hub. The following exception was raised:
[Errno 2] No such file or directory: '/root/.cache/torch/hub/pyannote_pyannote-audio_master/hubconf.py'
```

**Comment by shridharindiumsoft** [comment]
Hi @ken-mitamura , I tried installing your suggested versions but it does not work on this.

**Comment by eyaler** [comment]
solution:
```
!pip install pyannote.core==4.1 pyannote.pipeline==1.5.2 pyannote.audio==1.1.1
!wget -nc https://raw.githubusercontent.com/pyannote/pyannote-audio/1.1.1/hubconf.py -P /root/.cache/torch/hub/pyannote_pyannote-audio_main
!wget -nc https://raw.githubusercontent.com/pyannote/pyannote-audio/1.1.1/hubconf.py -P /root/.cache/torch/hub/pyannote_pyannote-audio-hub_master
import torch
import pyannote.core #https://github.com/pyannote/pyannote-audio/issues/561
pipeline = torch.hub.load('pyannote/pyannote-audio', 'dia', trust_repo=True)
```
