### ISSUE TITLE
train question

### ISSUE THREAD

**Issue by NICECPU** [pyannote/pyannote-audio#1099]
Sanity Checking: 0it [00:00, ?it/s]Protocol AMI.SpeakerDiarization.only_words does not provide the path to audio files: adding an 'audio' preprocessor for you. See pyannote.database documentation on how to do that yourself.
Protocol AMI.SpeakerDiarization.only_words does not precompute the output of torchaudio.info(): adding a 'torchaudio.info' preprocessor for you to speed up dataloaders. See pyannote.database documentation on how to do that yourself.

May I ask which step I have missed? I checked the prompted document and did not find my mistake

**Comment by hbredin** [comment]
You did not miss anything. Those are just warnings.

You can add the following preprocessors when instantiating the protocol if you really want to get rid of those warnings:

https://github.com/pyannote/pyannote-audio/blob/b3d9372cc6738994d614e1f9f3d3c7e3770acfed/pyannote/audio/cli/train.py#L55

**Comment by NICECPU** [comment]
> You did not miss anything. Those are just warnings.
> 
> You can add the following preprocessors when instantiating the protocol if you really want to get rid of those warnings:
> 
> https://github.com/pyannote/pyannote-audio/blob/b3d9372cc6738994d614e1f9f3d3c7e3770acfed/pyannote/audio/cli/train.py#L55

Thank you for your reply. May I ask why the following mistakes are made? When I run this code...
trainer.fit(vad_model)

GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name              | Type             | Params | In sizes        | Out sizes                                        
-----------------------------------------------------------------------------------------------------------------------------
0 | sincnet           | SincNet          | 42.6 K | [128, 1, 32000] | [128, 60, 115]                                   
1 | lstm              | LSTM             | 589 K  | [128, 115, 60]  | [[128, 115, 256], [[4, 128, 128], [4, 128, 128]]]
2 | linear            | ModuleList       | 49.4 K | ?               | ?                                                
3 | classifier        | Linear           | 129    | [128, 115, 128] | [128, 115, 1]                                    
4 | activation        | Sigmoid          | 0      | [128, 115, 1]   | [128, 115, 1]                                    
5 | validation_metric | MetricCollection | 0      | ?               | ?                                                
-----------------------------------------------------------------------------------------------------------------------------
681 K     Trainable params
0         Non-trainable params
681 K     Total params
2.728     Total estimated model params size (MB)
Sanity Checking: 0it [00:00, ?it/s]Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\jiang xin\.conda\envs\pyannote\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\jiang xin\.conda\envs\pyannote\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\jiang xin\.conda\envs\pyannote\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\jiang xin\.conda\envs\pyannote\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\jiang xin\.conda\envs\pyannote\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\jiang xin\.conda\envs\pyannote\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\jiang xin\.conda\envs\pyannote\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\Python_Project\Speaker_Diar\AMI-diarization-setup\pyannote\load.py", line 12, in <module>
    trainer.fit(vad_model)
  File "C:\Users\jiang xin\.conda\envs\pyannote\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 770, in fit
    self._call_and_handle_interrupt(
  File "C:\Users\jiang xin\.conda\envs\pyannote\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 723, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "C:\Users\jiang xin\.conda\envs\pyannote\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 811, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "C:\Users\jiang xin\.conda\envs\pyannote\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1236, in _run
    results = self._run_stage()
  File "C:\Users\jiang xin\.conda\envs\pyannote\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1323, in _run_stage
    return self._run_train()
  File "C:\Users\jiang xin\.conda\envs\pyannote\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1345, in _run_train
    self._run_sanity_check()
  File "C:\Users\jiang xin\.conda\envs\pyannote\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1413, in _run_sanity_check
    val_loop.run()
  File "C:\Users\jiang xin\.conda\envs\pyannote\lib\site-packages\pytorch_lightning\loops\base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "C:\Users\jiang xin\.conda\envs\pyannote\lib\site-packages\pytorch_lightning\loops\dataloader\evaluation_loop.py", line 155, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "C:\Users\jiang xin\.conda\envs\pyannote\lib\site-packages\pytorch_lightning\loops\base.py", line 199, in run
    self.on_run_start(*args, **kwargs)
  File "C:\Users\jiang xin\.conda\envs\pyannote\lib\site-packages\pytorch_lightning\loops\epoch\evaluation_epoch_loop.py", line 88, in on_run_start
    self._data_fetcher = iter(data_fetcher)
  File "C:\Users\jiang xin\.conda\envs\pyannote\lib\site-packages\pytorch_lightning\utilities\fetching.py", line 178, in __iter__
    self.dataloader_iter = iter(self.dataloader)
  File "C:\Users\jiang xin\.conda\envs\pyannote\lib\site-packages\torch\utils\data\dataloader.py", line 368, in __iter__
    return self._get_iterator()
  File "C:\Users\jiang xin\.conda\envs\pyannote\lib\site-packages\torch\utils\data\dataloader.py", line 314, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\jiang xin\.conda\envs\pyannote\lib\site-packages\torch\utils\data\dataloader.py", line 927, in __init__
    w.start()
  File "C:\Users\jiang xin\.conda\envs\pyannote\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\jiang xin\.conda\envs\pyannote\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\jiang xin\.conda\envs\pyannote\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\jiang xin\.conda\envs\pyannote\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\jiang xin\.conda\envs\pyannote\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\jiang xin\.conda\envs\pyannote\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**Comment by hbredin** [comment]
Closing as I believe the original issue has been solved.

Please open new issue for this other problem, but check for existing (open or closed) ones first.
