### ISSUE TITLE
Error: start is only allowed for seekable files

### ISSUE THREAD

**Issue by ainnotate** [pyannote/pyannote-audio#1104]
I'm able to test pyannote using the below code and the dirarization works as expected. 

```
from pyannote.audio import Pipeline
pipeline = Pipeline.from_pretrained("pyannote/speaker-diarization")

# apply pretrained pipeline
diarization = pipeline("audio.wav")

# print the result
for turn, _, speaker in diarization.itertracks(yield_label=True):
    print(f"start={turn.start:.1f}s stop={turn.end:.1f}s speaker_{speaker}")
```

However, I get the below error for some wav files. I'm not sure the reason behind the issue. [This](https://drive.google.com/file/d/1X4Qo_C2Cwckirl8yXUzhxQOPO3VG1pTI/view?usp=sharing) is the problematic wav file that is thworing the below error for me. 

```
Traceback (most recent call last):
  File "pyannote_test.py", line 7, in <module>
    diarization = pipeline(sys.argv[1])
  File "/home/san/anaconda3/envs/pyannote/lib/python3.8/site-packages/pyannote/audio/core/pipeline.py", line 210, in __call__
    return self.apply(file, **kwargs)
  File "/home/san/anaconda3/envs/pyannote/lib/python3.8/site-packages/pyannote/audio/pipelines/speaker_diarization.py", line 452, in apply
    embeddings = self.get_embeddings(
  File "/home/san/anaconda3/envs/pyannote/lib/python3.8/site-packages/pyannote/audio/pipelines/speaker_diarization.py", line 306, in get_embeddings
    for batch in batches:
  File "/home/san/anaconda3/envs/pyannote/lib/python3.8/site-packages/pyannote/audio/pipelines/speaker_diarization.py", line 274, in iter_waveform_and_mask
    waveform, _ = self._audio.crop(
  File "/home/san/anaconda3/envs/pyannote/lib/python3.8/site-packages/pyannote/audio/core/io.py", line 384, in crop
    data, _ = torchaudio.load(
  File "/home/san/anaconda3/envs/pyannote/lib/python3.8/site-packages/torchaudio/backend/soundfile_backend.py", line 205, in load
    frames = file_._prepare_read(frame_offset, None, num_frames)
  File "/home/san/anaconda3/envs/pyannote/lib/python3.8/site-packages/soundfile.py", line 1339, in _prepare_read
    raise ValueError("start is only allowed for seekable files")
ValueError: start is only allowed for seekable files

```

Any thoughts on this issue?

**Comment by ainnotate** [comment]
The issue was with the codec being used in the WAV file. torchaudio doesn't support GSM coded. Simply converting the wav using the below command fixed the problem.Hope this helps someone. 

`ffmpeg -i input.wav output.wav`

Thank you.
