### ISSUE TITLE
pyannote-speech-detection validate --chronological not working 

### ISSUE THREAD

**Issue by bml1g12** [pyannote/pyannote-audio#113]
Using pyannote.audio==1.0.1

I followed https://github.com/pyannote/pyannote-audio/tree/master/tutorials/change-detection
Using AMI and the features from the feature extraction tutorial
Training proceeds correctly, as shown by tensorboard visualization of EER and loss.

I did not run the validation during training, but instead ran it retrospectively  after using:

`pyannote-change-detection validate --purity=0.8 $MYPATH/AMI.SpeakerDiarization.MixHeadset.train AMI.SpeakerDiarization.MixHeadset`

Despite using `--chronological`, or `--from 0 --to 100`) it hung. In this usage, it prints  `0epoch [00:00, ?epoch/s]` and performs no further action. Restarting the training from the last epoch, and running validation in parallel seemed to work. 

I also tested the speech detection tutorial and found that when training and validating, even when used in parallel, the validation hung. 

In contrast, the embedding application `pyannote-speaker-embedding  validate --chronological`  shows the expected behavior - allowing retrospective validation. 

In case it is useful, I've included a stack trace of what is output when ctrl-C cancelling the validation

```
pyannote-speech-detection --from=100 validate ${TRAIN_DIR} AMI.SpeakerDiarization.MixHeadset 
0epoch [00:00, ?epoch/s]^CTraceback (most recent call last):
  File "/home/ben/.local/bin/pyannote-speech-detection", line 11, in <module>
    sys.exit(main())
  File "/home/ben/.local/lib/python3.6/site-packages/pyannote/audio/applications/speech_detection.py", line 390, in main
    in_order=in_order)
  File "/home/ben/.local/lib/python3.6/site-packages/pyannote/audio/applications/base.py", line 222, in validate
    validation_data=validation_data)
  File "/home/ben/.local/lib/python3.6/site-packages/pyannote/audio/applications/speech_detection.py", line 235, in validate_epoch
    scores = sequence_labeling.apply(current_file)
  File "/home/ben/.local/lib/python3.6/site-packages/pyannote/audio/labeling/extraction.py", line 209, in apply
    incomplete=True)]
  File "/home/ben/.local/lib/python3.6/site-packages/pyannote/audio/labeling/extraction.py", line 208, in <listcomp>
    batches = [batch for batch in self.from_file(current_file,
  File "/home/ben/.local/lib/python3.6/site-packages/pyannote/generators/batch.py", line 285, in from_file
    incomplete=incomplete):
  File "/home/ben/.local/lib/python3.6/site-packages/pyannote/generators/batch.py", line 343, in __call__
    batch = self.pack(self.signature)
  File "/home/ben/.local/lib/python3.6/site-packages/pyannote/generators/batch.py", line 186, in pack
    packed = batch if pack_func is None else pack_func(batch)
  File "/home/ben/.local/lib/python3.6/site-packages/pyannote/audio/labeling/extraction.py", line 191, in _pack
    return self.model(X).data.to('cpu').numpy()
  File "/home/ben/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ben/.local/lib/python3.6/site-packages/pyannote/audio/labeling/models.py", line 147, in forward
    output, _ = layer(output, hidden)
  File "/home/ben/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ben/.local/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 192, in forward
    output, hidden = func(input, self.all_weights, hx, batch_sizes)
  File "/home/ben/.local/lib/python3.6/site-packages/torch/nn/_functions/rnn.py", line 323, in forward
    return func(input, *fargs, **fkwargs)
  File "/home/ben/.local/lib/python3.6/site-packages/torch/nn/_functions/rnn.py", line 243, in forward
    nexth, output = func(input, hidden, weight, batch_sizes)
  File "/home/ben/.local/lib/python3.6/site-packages/torch/nn/_functions/rnn.py", line 86, in forward
    hy, output = inner(input, hidden[l], weight[l], batch_sizes)
  File "/home/ben/.local/lib/python3.6/site-packages/torch/nn/_functions/rnn.py", line 115, in forward
    hidden = inner(input[i], hidden, *weight)
  File "/home/ben/.local/lib/python3.6/site-packages/torch/nn/_functions/rnn.py", line 37, in LSTMCell
    ingate = F.sigmoid(ingate)
  File "/home/ben/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 974, in sigmoid
    return input.sigmoid()
```

**Comment by bml1g12** [comment]
Doing some debugging I think have narrowed down the issue:
```
audio/applications/change_detection.py
class SpeakerChangeDetection(SpeechActivityDetection):
def validate_epoch...
         ...
        # extract predictions for all files.
        predictions = {}
        for current_file in getattr(protocol, subset)():
            uri = get_unique_identifier(current_file)
            predictions[uri] = sequence_labeling.apply(current_file) #<< this line 211
```
sequence_labeling.apply sometimes takes a few seconds, and sometimes takes minutes such that a single epoch can take 30 minutes
`Epoch #0 : speaker_change_detection/coverage@0.80purity = 0.289% [0.289%, #0]: : 1epoch [31:01, 1861.78s/epoch]`

**Comment by hbredin** [comment]
@hedonistrh I just deleted your comment to clean up this thread (your comment was not related to this issue).

`metric(reference, hypothesis, uem=uem)` may indeed take forever when there are too many segments in the hypothesis.  I would gladly take a PR on `pyannote-metrics` speeding things up...

**Comment by chitwansaharia** [comment]
I am running validate --chronological on AMI.SpeakerDiarization.MixHeadset with --gpu, and it takes ~5min for each epoch validation. Is it normal ? 
Epoch #17 : overlap_speech_detection/recall@0.90precision = 0.000% [0.000%, #0]: : 18epoch [1:19:31, 264.80s/epoch]

**Comment by hbredin** [comment]
It is normal. For each epoch, validation looks for the best threshold to reach the targeted precision (here: 90%). To do that, it runs [dichotomic search](https://github.com/pyannote/pyannote-audio/blob/b678920057ace936c8900c62d2975e958903fae2/pyannote/audio/applications/overlap_detection.py#L148-L182) in 10 steps. Each step consists in a loop over all 21 files in AMI development set.

For validation to not lag behind training, you can use --every=10 option to only run validation every 10 epochs, for instance.

Also, on the example you reported, it looks like the requested precision (90%) is too high and is never reached by the model. You should probably use a smaller value, otherwise reported recall will always be 0%.

**Comment by chitwansaharia** [comment]
I see. I will try lowering the target precision. Thanks!
