### ISSUE TITLE
Pipeline Application : "ValueError: need at least one array to concatenate"

### ISSUE THREAD

**Issue by bluemonk482** [pyannote/pyannote-audio#117]
I have followed the training instructions in https://github.com/pyannote/pyannote-audio/tree/master/tutorials/pipeline. However, it outputs `AMI.SpeakerDiarization.MixHeadset.development` rather than `AMI.SpeakerDiarization.MixHeadset.train`.

```
(pyannote) ccrmad@ccrmad:~/Tools/pyannote-audio/tutorials/pipeline/train$ ls
AMI.SpeakerDiarization.MixHeadset.development
(pyannote) ccrmad@ccrmad:~/Tools/pyannote-audio/tutorials/pipeline/train/AMI.SpeakerDiarization.MixHeadset.development$ ls
31318  4790  params.yml  params.yml.lock  tune.db  tune.db.lock
```

I used `AMI.SpeakerDiarization.MixHeadset.development` as my `TRAIN_DIR`, and tried to apply the optimized pipeline on all files of the AMI database as instructed. I get the error shown below. 

```
(pyannote) ccrmad@ccrmad:~/Tools/pyannote-audio$ export TRAIN_DIR=${EXPERIMENT_DIR}/train/AMI.SpeakerDiarization.MixHeadset.development
(pyannote) ccrmad@ccrmad:~/Tools/pyannote-audio$ pyannote-pipeline apply ${TRAIN_DIR}/params.yml AMI.SpeakerDiarization.MixHeadset tutorials/pipeline/output
Development set: 21it [03:01,  8.66s/it]
Test set: 22it [03:48, 10.40s/it]
Training set: 26it [13:12, 30.47s/it]Traceback (most recent call last):
  File "/home/ccrmad/miniconda2/envs/pyannote/bin/pyannote-pipeline", line 11, in <module>
    sys.exit(main())
  File "/home/ccrmad/miniconda2/envs/pyannote/lib/python3.6/site-packages/pyannote/audio/applications/pipeline.py", line 272, in main
    application.apply(protocol_name, output_dir)
  File "/home/ccrmad/miniconda2/envs/pyannote/lib/python3.6/site-packages/pyannote/audio/applications/pipeline.py", line 226, in apply
    hypothesis = self.pipeline_.apply(current_file)
  File "/home/ccrmad/miniconda2/envs/pyannote/lib/python3.6/site-packages/pyannote/audio/pipeline/speaker_diarization.py", line 260, in apply
    [np.sum(emb.crop(t, mode='loose'), axis=0) for t in speech_turns]))
  File "/home/ccrmad/miniconda2/envs/pyannote/lib/python3.6/site-packages/pyannote/audio/pipeline/speaker_diarization.py", line 260, in <listcomp>
    [np.sum(emb.crop(t, mode='loose'), axis=0) for t in speech_turns]))
  File "/home/ccrmad/miniconda2/envs/pyannote/lib/python3.6/site-packages/pyannote/core/feature.py", line 164, in crop
    [self.data[r[0]: r[1], :] for r in clipped_ranges])
  File "/home/ccrmad/miniconda2/envs/pyannote/lib/python3.6/site-packages/numpy/core/shape_base.py", line 234, in vstack
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
ValueError: need at least one array to concatenate
```

Am I doing anything wrong here? Any help would be greatly appreciated! Thanks!

**Comment by hbredin** [comment]
I believe I fixed the bug in `pyannote.core 1.4.1` (see https://github.com/pyannote/pyannote-core/issues/19).

Would you mind trying updating to this new version of pyannote.audio and let me know whether it fixes the issue?

**Comment by OndraN** [comment]
Hi, thanks for response. I just update pyannote.core to version 1.4.1 (I had 1.4) and it work. Thanks a lot.

**Comment by hbredin** [comment]
Closing this issue. Please re-open if needed.
