### ISSUE TITLE
Wrong timestamps when using MPS on a Mac M1 

### ISSUE THREAD

**Issue by seboslaw** [pyannote/pyannote-audio#1337]
Hey guys, 

first of all kudos for pyannnote. It's amazing. However, I've noticed an issue. When running the `develop` branch on my M1 Mac (13.3.1 (22E261)) I get totally screwed timestamps when comparing them to the results running the same on colab with CUDA.

I'm running:

```
import sys
from pyannote.audio import Pipeline
from pyannote.core import Annotation
import time

api_token = os.environ.get("HF_API_TOKEN")

pipeline = Pipeline.from_pretrained("pyannote/speaker-diarization@2.1", use_auth_token=api_token)

pipeline.to("mps")

diarization = pipeline(sys.argv[1])
assert isinstance(diarization, Annotation)

for speech_turn, track, speaker in diarization.itertracks(yield_label=True):
    print(f"{speech_turn.start:4.1f} {speech_turn.end:4.1f} {speaker}")
```

Here are the incorrect result for MPS:

```
 0.5  6.0 SPEAKER_02
18.5 22.0 SPEAKER_00
34.5 35.5 SPEAKER_01
35.5 38.0 SPEAKER_00
50.4 54.0 SPEAKER_00
66.5 70.0 SPEAKER_00
82.5 86.0 SPEAKER_01
98.5 98.5 SPEAKER_01
98.5 102.0 SPEAKER_00
114.5 118.0 SPEAKER_00
130.5 134.0 SPEAKER_00
146.4 150.0 SPEAKER_01
162.4 166.0 SPEAKER_01
178.5 182.0 SPEAKER_01
194.5 198.0 SPEAKER_01
210.5 214.0 SPEAKER_01
226.5 230.0 SPEAKER_00
242.5 246.0 SPEAKER_00
258.4 262.0 SPEAKER_00
274.4 278.0 SPEAKER_00
290.5 294.0 SPEAKER_01
306.5 310.0 SPEAKER_00
322.5 326.0 SPEAKER_00
338.5 342.0 SPEAKER_00
```

Here are the **correct** results using CUDA:

```
[ 00:00:01.139 -->  00:00:09.002] A SPEAKER_00
[ 00:00:09.002 -->  00:00:11.500] JY SPEAKER_04
[ 00:00:11.500 -->  00:00:30.501] AT SPEAKER_02
[ 00:00:30.501 -->  00:00:36.441] JZ SPEAKER_04
[ 00:00:36.441 -->  00:00:44.001] AU SPEAKER_02
[ 00:00:44.001 -->  00:00:48.473] KA SPEAKER_04
[ 00:00:48.473 -->  00:01:20.080] AV SPEAKER_02
[ 00:01:19.995 -->  00:01:26.779] KB SPEAKER_04
[ 00:01:26.644 -->  00:01:33.900] AW SPEAKER_02
[ 00:01:34.424 -->  00:01:39.469] KC SPEAKER_04
[ 00:01:39.942 -->  00:02:17.691] AX SPEAKER_02
[ 00:01:57.255 -->  00:01:57.998] KD SPEAKER_04
[ 00:02:17.742 -->  00:02:49.956] KE SPEAKER_04
[ 00:02:31.984 -->  00:02:32.322] II SPEAKER_03
[ 00:02:33.891 -->  00:02:34.566] AC SPEAKER_01
[ 00:02:36.540 -->  00:02:36.827] AD SPEAKER_01
[ 00:02:42.345 -->  00:02:42.767] AE SPEAKER_01
[ 00:02:48.134 -->  00:02:52.724] AY SPEAKER_02
[ 00:02:52.724 -->  00:03:46.589] KF SPEAKER_04
[ 00:03:24.314 -->  00:03:26.693] AZ SPEAKER_02
[ 00:03:38.117 -->  00:03:38.590] BA SPEAKER_02
[ 00:03:46.302 -->  00:03:47.871] BB SPEAKER_02
[ 00:03:47.871 -->  00:03:49.474] KG SPEAKER_04
[ 00:03:48.715 -->  00:04:51.169] BC SPEAKER_02
[ 00:04:01.118 -->  00:04:01.489] B SPEAKER_00
[ 00:04:11.327 -->  00:04:11.817] C SPEAKER_00
[ 00:04:16.221 -->  00:04:16.559] D SPEAKER_00
[ 00:04:26.802 -->  00:04:27.173] AF SPEAKER_01
[ 00:04:51.169 -->  00:05:02.897] KH SPEAKER_04
[ 00:05:02.121 -->  00:05:24.464] BD SPEAKER_02
[ 00:05:24.464 -->  00:05:28.851] KI SPEAKER_04
[ 00:05:26.320 -->  00:05:26.337] BE SPEAKER_02
[ 00:05:28.851 -->  00:05:31.028] BF SPEAKER_02
[ 00:05:31.197 -->  00:05:38.217] KJ SPEAKER_04
[ 00:05:38.217 -->  00:05:47.498] BG SPEAKER_02
[ 00:05:47.498 -->  00:06:00.154] KK SPEAKER_04
```

**Comment by hbredin** [comment]
I noticed that as well. This is an issue in pytorch (not so ready for prime time) support for `mps`.

**Comment by seboslaw** [comment]
@hbredin I realised I didn't have PyTorch nightly installed and thought doing so would improve things:

```
pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu
```

However, now pyannote bails on me with the following error:

```
Traceback (most recent call last):
  File "/Users/user/diarization-test/main.py", line 28, in <module>
    diarization = pipeline(sys.argv[1])
  File "/Users/user/diarization-test/pyannote/lib/python3.10/site-packages/pyannote/audio/core/pipeline.py", line 315, in __call__
    return self.apply(file, **kwargs)
  File "/Users/user/diarization-test/pyannote/lib/python3.10/site-packages/pyannote/audio/pipelines/speaker_diarization.py", line 496, in apply
    embeddings = self.get_embeddings(
  File "/Users/user/diarization-test/pyannote/lib/python3.10/site-packages/pyannote/audio/pipelines/speaker_diarization.py", line 266, in get_embeddings
    min_num_samples = self._embedding.min_num_samples
  File "/opt/homebrew/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/Users/user/diarization-test/pyannote/lib/python3.10/site-packages/pyannote/audio/pipelines/speaker_verification.py", line 289, in min_num_samples
    _ = self.classifier_.encode_batch(
  File "/Users/user/diarization-test/pyannote/lib/python3.10/site-packages/speechbrain/pretrained/interfaces.py", line 943, in encode_batch
    feats = self.mods.compute_features(wavs)
  File "/Users/user/diarization-test/pyannote/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/user/diarization-test/pyannote/lib/python3.10/site-packages/speechbrain/lobes/features.py", line 138, in forward
    STFT = self.compute_STFT(wav)
  File "/Users/user/diarization-test/pyannote/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/user/diarization-test/pyannote/lib/python3.10/site-packages/speechbrain/processing/features.py", line 147, in forward
    stft = torch.stft(
  File "/Users/user/diarization-test/pyannote/lib/python3.10/site-packages/torch/functional.py", line 642, in stft
    return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
TypeError: Complex types are unsupported on MPS
```

**Comment by hbredin** [comment]
Unfortunately, that just confirms that pytorch `mps` support is not there yet...

**Comment by hbredin** [comment]
See https://github.com/pytorch/pytorch/issues/77764

**Comment by seboslaw** [comment]
Ouch...that's a long thread - seems like still a lot of work ahead :)
Sucks that `PYTORCH_ENABLE_MPS_FALLBACK=1` doesn't work here.
