### ISSUE TITLE
pyannote.audio in prodigy

### ISSUE THREAD

**Issue by wasabitf** [pyannote/pyannote-audio#1347]
Hi everyone,

I am trying to make work pyannote.audio in prodigy, but with out success. I work in a research that implements diarization in classroom environment that from this data we try to infer other features. So we decide use prodigy with pyannote.audio recipes in jupiter lab for labelling but when I use the command:

!prodigy pyannote.audio dataset audioTest pyannote/speaker-segmentation

I get:

Traceback (most recent call last):
  File "/home/wasabi/miniconda3/envs/prodigylab/lib/python3.10/runpy.py", line 196, in _run_module_as_main
  return _run_code(code, main_globals, None,
  File "/home/wasabi/miniconda3/envs/prodigylab/lib/python3.10/runpy.py", line 86, in _run_code
  exec(code, run_globals)
  File "/home/wasabi/miniconda3/envs/prodigylab/lib/python3.10/site-packages/prodigy/__main__.py", line 62, in <module>
  controller = recipe(*args, use_plac=True)
  File "cython_src/prodigy/core.pyx", line 374, in prodigy.core.recipe.recipe_decorator.recipe_proxy
  File "/home/wasabi/miniconda3/envs/prodigylab/lib/python3.10/site-packages/plac_core.py", line 367, in call
  cmd, result = parser.consume(arglist)
  File "/home/wasabi/miniconda3/envs/prodigylab/lib/python3.10/site-packages/plac_core.py", line 232, in consume
  return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/home/wasabi/miniconda3/envs/prodigylab/lib/python3.10/site-packages/pyannote/audio/interactive/pipeline/recipe.py", line 178, in pipeline
  pipeline = Pipeline.from_pretrained(pipeline, use_auth_token=True)
  File "/home/wasabi/miniconda3/envs/prodigylab/lib/python3.10/site-packages/pyannote/audio/core/pipeline.py", line 130, in from_pretrained
  Klass = get_class_by_name(
  File "/home/wasabi/miniconda3/envs/prodigylab/lib/python3.10/site-packages/pyannote/core/utils/helper.py", line 68, in get_class_by_name
  return getattr(import_module(module_name), class_name)
AttributeError: module 'pyannote.audio.pipelines' has no attribute 'SpeakerSegmentation'

I think I have followed the instructions properly:

 pip install https://github.com/pyannote/pyannote-audio/archive/refs/heads/develop.zip
This erros are relevants?

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
launchdarkly-server-sdk 7.5.0 requires pyRFC3339>=1.0, which is not installed.
label-studio 1.7.3 requires lockfile>=0.12.0, which is not installed.
launchdarkly-server-sdk 7.5.0 requires semver<3.0.0,>=2.10.2, but you have semver 3.0.0 which is incompatible.
label-studio 1.7.3 requires requests<=2.28,>=2.22.0, but you have requests 2.28.2 which is incompatible.

I accept the terms an conditions in
https://huggingface.co/pyannote/speaker-segmentation
I log with my token with
from huggingface_hub import notebook_login

notebook_login()

And then I use the command

Could someone guide me? What is wrong?

**Comment by hbredin** [comment]
Prodigy support is no longer maintained and will most likely disappear in future versions of pyannote.audio due to lack of resources to maintain this part of the library.

You might want to try installing pyannote.audio from an older commit (e.g. the ones where Prodigy recipes were introduced).
