### ISSUE TITLE
'ProtocolFile' object has no attribute 'dim': Broken Tutorial

### ISSUE THREAD

**Issue by great-goblin** [pyannote/pyannote-audio#1377]
Hi all,

I'm new to this library so apologies if this is a basic question. I've been trying to run [this tutorial](https://github.com/pyannote/pyannote-audio/blob/develop/tutorials/adapting_pretrained_pipeline.ipynb) but was running into issues trying to run it in Jypter immediately. Won't go into those issues, but I tried instead to replicate it on my own machine. 

```python

from pyannote.database import registry, FileFinder, get_protocol
from pyannote.audio import Inference, Model
from pyannote.metrics.diarization import DiarizationErrorRate

#Load database
registry.load_database("SIF/data_preparation/AMI-diarization-setup/pyannote/database.yml")
ami = get_protocol('AMI.SpeakerDiarization.only_words', {'audio': FileFinder()})

#Get a test file
test_file = next(ami.test())

#Get the pretrained model
pretrained = Model.from_pretrained("pyannote/segmentation", use_auth_token="<mytoken>")

#Testing its performance
metric = DiarizationErrorRate()
for file in ami.test():
    # apply pretrained pipeline
    file["pretrained pipeline"] = pretrained(file)
    # evaluate its performance
    metric(file["annotation"], file["pretrained pipeline"], uem=file["annotated"])
print(f"The pretrained pipeline reaches a Diarization Error Rate (DER) of {100 * abs(metric):.1f}% on {ami.name} test set.")
spk_probability = Inference(pretrained, step=2.5)(test_file)
```

This is essentially copy and pasted from the tutorial I linked above. Unfortunately, when attempting to run this, the program fails at `file["pretrained pipeline"] = pretrained(file)` and throws the error message `AttributeError: 'ProtocolFile' object has no attribute 'dim'`:

Here's the full error message:
```
AMI-SDM.SpeakerDiarization.only_words' found in C:\Users\ericl\Code\SIF\data_preparation\AMI-diarization-setup\pyannote\database.yml does not define the 'scope' of speaker labels (file, database, or global). Setting it to 'file'.
'AMI-SDM.SpeakerDiarization.mini' found in C:\Users\ericl\Code\SIF\data_preparation\AMI-diarization-setup\pyannote\database.yml does not define the 'scope' of speaker labels (file, database, or global). Setting it to 'file'.
'AMI.SpeakerDiarization.only_words' found in C:\Users\ericl\Code\SIF\data_preparation\AMI-diarization-setup\pyannote\database.yml does not define the 'scope' of speaker labels (file, database, or global). Setting it to 'file'.
'AMI.SpeakerDiarization.mini' found in C:\Users\ericl\Code\SIF\data_preparation\AMI-diarization-setup\pyannote\database.yml does not define the 'scope' of speaker labels (file, database, or global). Setting it to 'file'.
'AMI.SpeakerDiarization.word_and_vocalsounds' found in C:\Users\ericl\Code\SIF\data_preparation\AMI-diarization-setup\pyannote\database.yml does not define the 'scope' of speaker labels (file, database, or global). Setting it to 'file'.
Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.0.2. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file C:\Users\ericl\.cache\torch\pyannote\models--pyannote--segmentation\snapshots\7d5cf7bca4dcac7f943eb834bec0906a90da8c97\pytorch_model.bin`
Model was trained with pyannote.audio 0.0.1, yours is 2.1.1. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.10.0+cu102, yours is 2.0.1+cu118. Bad things might happen unless you revert torch to 1.x.
Traceback (most recent call last):
  File "c:\Users\ericl\Code\SIF\data_preparation\scripts\finetune2.py", line 22, in <module>
    file["pretrained pipeline"] = pretrained(file)
                                  ^^^^^^^^^^^^^^^^
  File "C:\Users\ericl\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ericl\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyannote\audio\models\segmentation\PyanNet.py", line 171, in forward
    outputs = self.sincnet(waveforms)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ericl\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ericl\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyannote\audio\models\blocks\sincnet.py", line 81, in forward      
    outputs = self.wav_norm1d(waveforms)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ericl\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ericl\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\instancenorm.py", line 69, in forward
    self._check_input_dim(input)
  File "C:\Users\ericl\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\instancenorm.py", line 148, in _check_input_dim   
    if input.dim() not in (2, 3):
       ^^^^^^^^^
AttributeError: 'ProtocolFile' object has no attribute 'dim'
```

Any ideas on how to resolve this? I'd like to follow the tutorial to learn how to fine-tune the pretrained diarization model on my own data, but unsure of why we're feeding in a ProtocolFile object to the pretrained model in the tutorial, when the type declaration of Model dosn't accept ProtocolFile as an argument.

**Comment by flyingleafe** [comment]
@great-goblin You are feeding a `ProtocolFile` to the `Model`, not to the `Pipeline`, as the tutorial says.
Replace
```
Model.from_pretrained("pyannote/segmentation", ...)
```
with
```
Pipeline.from_pretrained("pyannote/speaker-diarization", ...)
```
