### ISSUE TITLE
Metric fails, binarize seems to return pyannote.core.feature.SlidingWindowFeature instead of Annotation

### ISSUE THREAD

**Issue by tomschelsen** [pyannote/pyannote-audio#1395]
The code is taken from [the tutorial](https://github.com/pyannote/pyannote-audio/blob/7379f1c82be093078354449100e1a84cbdfbafdf/tutorials/training_a_model.ipynb#L411) , I'm just using SegmentationPurityCoverageFMeasure as a metric instead of DER.

Traceback:
```
Traceback (most recent call last):
  File "train_pyannote.py", line 788, in <module>
    purcovfscore_pretrained = test(model=pyannote_segmentation_pretrained_model, protocol=protocol, subset="test")
  File "train_pyannote.py", line 703, in test
    _ = metric(
  File "/usr/local/lib/python3.8/dist-packages/pyannote/metrics/base.py", line 114, in __call__
    components = self.compute_components(reference, hypothesis, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pyannote/metrics/segmentation.py", line 220, in compute_components
    return self._process(reference, hypothesis)
  File "/usr/local/lib/python3.8/dist-packages/pyannote/metrics/segmentation.py", line 202, in _process
    reference, hypothesis = self._preprocess(reference, hypothesis)
  File "/usr/local/lib/python3.8/dist-packages/pyannote/metrics/segmentation.py", line 118, in _preprocess
    hypothesis_partition = self._partition(hypothesis, coverage)
  File "/usr/local/lib/python3.8/dist-packages/pyannote/metrics/segmentation.py", line 82, in _partition
    boundaries.add(segment.start)
AttributeError: 'tuple' object has no attribute 'start'
```

Debug-printing shows me that the `reference` variable looks like an `Annotation`, but printing `hypothesis` type shows `<class 'pyannote.core.feature.SlidingWindowFeature'>`. Shouldn't it be an Annotation as well ?

I am on pyannote.metrics 3.2.1 , pyannote.database 5.0.1 , pyannote.core 5.0.0

Any help much appreciated. Thanks

**Comment by tomschelsen** [comment]
Solved using this instead

```
pyannote_to_scd = lambda probability: numpy.max(
        numpy.abs(numpy.diff(probability, n=1, axis=TIME_AXIS)), 
        axis=SPEAKER_AXIS, keepdims=True
    )
pyannote_scd = Inference(
        model, 
        pre_aggregation_hook=pyannote_to_scd, 
        device=device
    )
pyannote_peak = Peak(alpha=0.05)
pyannote_scd_prob = pyannote_scd(file)
hypothesis = pyannote_peak(pyannote_scd_prob)
```
