### ISSUE TITLE
Getting 'ModuleNotFoundError: No module named 'pytorch_lightning.utilities.cloud_io'' Error In Colab

### ISSUE THREAD

**Issue by ahmadalghadban** [pyannote/pyannote-audio#1421]
I'm using a script from another repo which depend on pyannote.audio module and got the following error
The problem starts from the other repo script but its cause is ' from pyannote.audio.core.io import Audio, AudioFile'
which ends with 'ModuleNotFoundError: No module named 'pytorch_lightning.utilities.cloud_io''

Traceback (most recent call last):
  File "/content/speaker-change-detection/train.py", line 7, in <module>
    from data import SegmentationAndSCDData
  File "/content/speaker-change-detection/data.py", line 11, in <module>
    from pyannote.audio.core.io import Audio, AudioFile
  File "/usr/local/lib/python3.10/dist-packages/pyannote/audio/__init__.py", line 29, in <module>
    from .core.inference import Inference
  File "/usr/local/lib/python3.10/dist-packages/pyannote/audio/core/inference.py", line 35, in <module>
    from pyannote.audio.core.model import Model
  File "/usr/local/lib/python3.10/dist-packages/pyannote/audio/core/model.py", line 39, in <module>
    from pytorch_lightning.utilities.cloud_io import load as pl_load
ModuleNotFoundError: No module named 'pytorch_lightning.utilities.cloud_io'

**Comment by ckchandler** [comment]
@ahmadalghadban were you able to find a solution to this issue?
