### ISSUE TITLE
Incomplete wav chunk

### ISSUE THREAD

**Issue by Jcakilv** [pyannote/pyannote-audio#146]
Hi, i tried to follow the speech activity tutorial in develop branch, get these error.

```html
Training set: 0it [00:00, ?it/s]/root/anaconda3/envs/diarization/lib/python3.6/s
ite-packages/AMI/__init__.py:51: FutureWarning: read_table is deprecated, use re
ad_csv instead, passing sep='\t'.
  annotated = read_table(annotated, delim_whitespace=True, names=names)
/root/anaconda3/envs/diarization/lib/python3.6/site-packages/AMI/__init__.py:56:
 FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'
.
  annotation = read_table(annotation, delim_whitespace=True, names=names)
Training set: 115it [00:06, 18.92it/s]
Training set: 4it [00:04,  1.26s/it]/root/anaconda3/envs/diarization/lib/python3
.6/site-packages/pyannote.audio-1.0+217.g47f257a-py3.6.egg/pyannote/audio/labeli
ng/tasks/speech_activity_detection.py:105: RuntimeWarning: invalid value encount
ered in greater
Training set: 115it [01:12,  1.54it/s]
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/root/anaconda3/envs/diarization/lib/python3.6/threading.py", line 916, 
in _bootstrap_inner
    self.run()
  File "/root/anaconda3/envs/diarization/lib/python3.6/site-packages/pyannote/ge
nerators/background.py", line 80, in run
    for item in self.generator:
  File "/root/anaconda3/envs/diarization/lib/python3.6/site-packages/pyannote/generators/batch.py", line 203, in __next__
    return next(self.batch_generator_)
  File "/root/anaconda3/envs/diarization/lib/python3.6/site-packages/pyannote/generators/batch.py", line 214, in iter_batches
    for fragment in self.generator:
  File "/root/anaconda3/envs/diarization/lib/python3.6/site-packages/pyannote/generators/batch.py", line 87, in __next__
    return next(generator)
  File "/root/anaconda3/envs/diarization/lib/python3.6/site-packages/pyannote.audio-1.0+217.g47f257a-py3.6.egg/pyannote/audio/labeling/tasks/base.py", line 213, in random_samples
    fixed=self.duration)
  File "/root/anaconda3/envs/diarization/lib/python3.6/site-packages/pyannote.audio-1.0+217.g47f257a-py3.6.egg/pyannote/audio/features/base.py", line 202, in crop  
    fixed=xsegment.duration)
  File "/root/anaconda3/envs/diarization/lib/python3.6/site-packages/pyannote.audio-1.0+217.g47f257a-py3.6.egg/pyannote/audio/features/utils.py", line 278, in crop 
    mmap=True)
  File "/root/anaconda3/envs/diarization/lib/python3.6/site-packages/scipy/io/wavfile.py", line 248, in read
    raise ValueError("Incomplete wav chunk.")
ValueError: Incomplete wav chunk.
```
Thanks for help!

**Comment by hbredin** [comment]
I also had this issue before.

For some reason, `scipy.io.wavfile` cannot read the following files:

```
amicorpus/IS1004d/audio/IS1004d.Mix-Headset.wav
amicorpus/IS1006c/audio/IS1006c.Mix-Headset.wav
amicorpus/IS1008d/audio/IS1008d.Mix-Headset.wav
amicorpus/IS1007a/audio/IS1007a.Mix-Headset.wav
amicorpus/IS1008c/audio/IS1008c.Mix-Headset.wav
amicorpus/IS1005a/audio/IS1005a.Mix-Headset.wav
amicorpus/IS1008b/audio/IS1008b.Mix-Headset.wav
amicorpus/IS1009b/audio/IS1009b.Mix-Headset.wav
amicorpus/IS1002c/audio/IS1002c.Mix-Headset.wav
amicorpus/IS1004b/audio/IS1004b.Mix-Headset.wav
amicorpus/IS1008a/audio/IS1008a.Mix-Headset.wav
amicorpus/IS1004a/audio/IS1004a.Mix-Headset.wav
amicorpus/IS1005b/audio/IS1005b.Mix-Headset.wav
amicorpus/IS1007c/audio/IS1007c.Mix-Headset.wav
amicorpus/IS1004c/audio/IS1004c.Mix-Headset.wav
amicorpus/IS1009c/audio/IS1009c.Mix-Headset.wav
amicorpus/IS1003c/audio/IS1003c.Mix-Headset.wav
amicorpus/IS1009a/audio/IS1009a.Mix-Headset.wav
amicorpus/IS1009d/audio/IS1009d.Mix-Headset.wav
amicorpus/IS1006a/audio/IS1006a.Mix-Headset.wav
amicorpus/IS1005c/audio/IS1005c.Mix-Headset.wav
amicorpus/IS1006d/audio/IS1006d.Mix-Headset.wav
amicorpus/IS1003d/audio/IS1003d.Mix-Headset.wav
amicorpus/IS1007b/audio/IS1007b.Mix-Headset.wav
```

One solution I found was to open them with `librosa` and write them back with `scipy.io.wavfile.write`.

**Comment by Jcakilv** [comment]
Thank it works

**Comment by hbredin** [comment]
Good to know. I guess I need to update the tutorials with this information.

Did you write a script for doing this read/write operation? 
Would you mind sharing it so that I can link to it in the tutorials?

**Comment by hbredin** [comment]
Re-opening to make sure this is clearly stated in tutorials before releasing 2.0.

**Comment by Jcakilv** [comment]
```html
import os
import sys
import glob
import numpy as np
import librosa
from scipy.io import wavfile

def main(pathAudio):
	for dirs in os.listdir(pathAudio):
		auds = glob.glob(os.path.join(pathAudio, dirs + '/audio'))
		for aud in auds:
			wavs = glob.glob(os.path.join(pathAudio, dirs, aud + '/*.wav'))
			for wav in wavs:
				print wav
				y, sr = librosa.load(wav, sr = 16000, mono=True)
				y = y * 32767 / max(0.01, np.max(np.abs(y)))
				wavfile.write(wav, sr, y.astype(np.int16))

if __name__ == '__main__':
	main('/home/ubuntu/train/neet')
```

**Comment by Jcakilv** [comment]
```html
import os
import sys
import glob
import numpy as np
import librosa
from scipy.io import wavfile

def main(pathAudio):
	for dirs in os.listdir(pathAudio):
		auds = glob.glob(os.path.join(pathAudio, dirs + '/audio'))
		for aud in auds:
			wavs = glob.glob(os.path.join(pathAudio, dirs, aud + '/*.wav'))
			for wav in wavs:
				print wav
				y, sr = librosa.load(wav, sr = 16000, mono=True)
				y = y * 32767 / max(0.01, np.max(np.abs(y)))
				wavfile.write(wav, sr, y.astype(np.int16))

if __name__ == '__main__':
	main('path/to/folder')
```
sorry if my write is mess

**Comment by hbredin** [comment]
Thanks for sharing your script!

**Comment by hadware** [comment]
maybe I should include that script as part of a "finishing" sequence for the odessa-ami database repo I commited on?
Another way (not requiring librosa to be installed, which is good for the odessa-ami repo) is to use this function that leverages standard `wave` module:

```python3
import wave

def normalize_wav(input_file, output_file):
    with wave.open(input_file, "rb") as r_wav, wave.open(output_file, "wb") as w_wav:
        w_wav.setparams(r_wav.getparams())
        w_wav.writeframes(r_wav.readframes(w_wav.getnframes()))
```

You can use that function to "fix" the wav file "on the fly" using a BytesIO:
```python3
import io
from scipy.io.wavfile import read

buff = io.BytesIO()
normalize_wav("/tmp/original.wav", buff)
buff.seek(0)
rate, data = read(buff)
```

**Comment by hbredin** [comment]
Fixing wav files after download would be great, thanks!

The "on-the-fly" solution is pretty... however it probably does not allow fast random access like `scipy.io.wavfile.read(..., mmap=True)` does in `RawAudio.crop`:

https://github.com/pyannote/pyannote-audio/blob/aebf796aaa58c2861feb4d1280cddff2d76febe0/pyannote/audio/features/utils.py#L277-L278 
https://github.com/pyannote/pyannote-audio/blob/aebf796aaa58c2861feb4d1280cddff2d76febe0/pyannote/audio/features/utils.py#L288

Training embeddings heavily relies on this "feature" to make batch generation faster...

**Comment by hadware** [comment]
Alright then, i'll just add it to the odessa-ami repo.

**Comment by CelesteAnaid** [comment]
> ```
> import os
> import sys
> import glob
> import numpy as np
> import librosa
> from scipy.io import wavfile
> 
> def main(pathAudio):
> 	for dirs in os.listdir(pathAudio):
> 		auds = glob.glob(os.path.join(pathAudio, dirs + '/audio'))
> 		for aud in auds:
> 			wavs = glob.glob(os.path.join(pathAudio, dirs, aud + '/*.wav'))
> 			for wav in wavs:
> 				print wav
> 				y, sr = librosa.load(wav, sr = 16000, mono=True)
> 				y = y * 32767 / max(0.01, np.max(np.abs(y)))
> 				wavfile.write(wav, sr, y.astype(np.int16))
> 
> if __name__ == '__main__':
> 	main('path/to/folder')
> ```
> 
> sorry if my write is mess

Hi!! Do you mind explaining the formula, please? why you multiply "y" by 32767 and then divide it?

**Comment by hadware** [comment]
* 32767 is the maximum (absolute) value you can reach with an int16
* i'm guessing the division is to get a normalized value
