### ISSUE TITLE
ModuleNotFoundError: 'pyannote.core'

### ISSUE THREAD

**Issue by rnunziata** [pyannote/pyannote-audio#160]
install looks ok after backing out cuda-10 for dlib error: However I get path error not sure what I missed. In installation. note first is says this core is not installed then after install its says it can not find core.

```
>>pyannote-pipeline --help

Traceback (most recent call last):
  File "/home/rjn/anaconda3/bin/pyannote-pipeline", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/rjn/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3105, in <module>
    @_call_aside
  File "/home/rjn/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3089, in _call_aside
    f(*args, **kwargs)
  File "/home/rjn/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3118, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/rjn/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 578, in _build_master
    ws.require(__requires__)
  File "/home/rjn/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 895, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/rjn/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 781, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pyannote.core>=2.1' distribution was not found and is required by pyannote.pipeline


>> pip install pyannote.core

Collecting pyannote.core
  Using cached https://files.pythonhosted.org/packages/da/78/4f9fda718a1a0992a27042cd321d11bbe1e60a6e8d491846791e96c96d51/pyannote.core-2.1-py3-none-any.whl
Requirement already satisfied: pandas>=0.17.1 in /home/rjn/anaconda3/lib/python3.6/site-packages (from pyannote.core) (0.23.4)
Requirement already satisfied: sortedcontainers>=2.0.4 in /home/rjn/anaconda3/lib/python3.6/site-packages (from pyannote.core) (2.0.5)
Requirement already satisfied: six>=1.10.0 in /home/rjn/anaconda3/lib/python3.6/site-packages (from pyannote.core) (1.11.0)
Requirement already satisfied: numpy>=1.10.4 in /home/rjn/anaconda3/lib/python3.6/site-packages (from pyannote.core) (1.14.3)
Requirement already satisfied: matplotlib>=2.0.0 in /home/rjn/anaconda3/lib/python3.6/site-packages (from pyannote.core) (2.0.2)
Requirement already satisfied: scipy>=0.10.0 in /home/rjn/anaconda3/lib/python3.6/site-packages (from pyannote.core) (0.19.0)
Requirement already satisfied: simplejson>=3.8.1 in /home/rjn/anaconda3/lib/python3.6/site-packages (from pyannote.core) (3.16.0)
Requirement already satisfied: xarray>=0.7.0 in /home/rjn/anaconda3/lib/python3.6/site-packages (from pyannote.core) (0.11.3)
Requirement already satisfied: python-dateutil>=2.5.0 in /home/rjn/anaconda3/lib/python3.6/site-packages (from pandas>=0.17.1->pyannote.core) (2.7.3)
Requirement already satisfied: pytz>=2011k in /home/rjn/anaconda3/lib/python3.6/site-packages (from pandas>=0.17.1->pyannote.core) (2018.5)
Requirement already satisfied: pyparsing!=2.0.0,!=2.0.4,!=2.1.2,!=2.1.6,>=1.5.6 in /home/rjn/anaconda3/lib/python3.6/site-packages (from matplotlib>=2.0.0->pyannote.core) (2.2.0)
Requirement already satisfied: cycler>=0.10 in /home/rjn/anaconda3/lib/python3.6/site-packages (from matplotlib>=2.0.0->pyannote.core) (0.10.0)
Installing collected packages: pyannote.core
Successfully installed pyannote.core-2.1
You are using pip version 10.0.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


>> pyannote-pipeline --help

Traceback (most recent call last):
  File "/home/rjn/anaconda3/bin/pyannote-pipeline", line 11, in <module>
    load_entry_point('pyannote.pipeline==1.0', 'console_scripts', 'pyannote-pipeline')()
  File "/home/rjn/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/rjn/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2707, in load_entry_point
    return ep.load()
  File "/home/rjn/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2325, in load
    return self.resolve()
  File "/home/rjn/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2331, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/rjn/anaconda3/lib/python3.6/site-packages/pyannote.pipeline-1.0-py3.6.egg/pyannote/pipeline/__init__.py", line 35, in <module>
    from .pipeline import Pipeline
  File "/home/rjn/anaconda3/lib/python3.6/site-packages/pyannote.pipeline-1.0-py3.6.egg/pyannote/pipeline/pipeline.py", line 40, in <module>
    from pyannote.core import Timeline
ModuleNotFoundError: No module named 'pyannote.core'


```

```

>>  sudo find . / -name pyannot*


./anaconda3/bin/__pycache__/pyannote-metrics.cpython-36.pyc
./anaconda3/bin/pyannote-metrics.py
./anaconda3/bin/pyannote-pipeline
./anaconda3/lib/python3.6/site-packages/pyannote.generators-2.0.dist-info
./anaconda3/lib/python3.6/site-packages/pyannote.db.odessa.ami-1.0.dist-info
./anaconda3/lib/python3.6/site-packages/pyannote.generators-2.0-py3.6-nspkg.pth
./anaconda3/lib/python3.6/site-packages/pyannote.database-1.5.5.dist-info
./anaconda3/lib/python3.6/site-packages/pyannote.core-2.1-py3.6-nspkg.pth
./anaconda3/lib/python3.6/site-packages/pyannote.parser-0.7.1-py3.6-nspkg.pth
./anaconda3/lib/python3.6/site-packages/pyannote.database-1.5.5-py3.6-nspkg.pth
./anaconda3/lib/python3.6/site-packages/pyannote.metrics-1.8.1-py3.6-nspkg.pth
./anaconda3/lib/python3.6/site-packages/pyannote.pipeline-1.0-py3.6.egg
./anaconda3/lib/python3.6/site-packages/pyannote.pipeline-1.0-py3.6.egg/pyannote.pipeline-1.0-py3.6-nspkg.pth
./anaconda3/lib/python3.6/site-packages/pyannote.pipeline-1.0-py3.6.egg/pyannote
./anaconda3/lib/python3.6/site-packages/pyannote.metrics-1.8.1.dist-info
./anaconda3/lib/python3.6/site-packages/pyannote.parser-0.7.1.dist-info
./anaconda3/lib/python3.6/site-packages/pyannote
./anaconda3/lib/python3.6/site-packages/pyannote.core-2.1.dist-info
./projects/voice/pyannote-audio
./projects/voice/pyannote-audio/dist/pyannote.audio-1.0+227.g0731ccd-py3.6.egg
./projects/voice/pyannote-audio/build/lib/pyannote
./projects/voice/pyannote-audio/pyannote
./projects/voice/pyannote-audio/pyannote.audio.egg-info

```

**Comment by rnunziata** [comment]
bad installation...

**Comment by Fanghc95** [comment]
hello！Did U install pyannote.audio sucessfully?

I wanted to use pre-trainned modal on my own wav, but it said 'No module named 'pyannote.generators'. I find it in my packages list.
I don't kown how to do ...
