### ISSUE TITLE
pyannote-audio-train cli interface bug

### ISSUE THREAD

**Issue by adamkatav** [pyannote/pyannote-audio#1602]
Hello, I'm trying to run `pyannote-audio-train`  with the example in [this](https://github.com/pyannote/pyannote-audio/blob/develop/tutorials/training_with_cli.md) tutorial.
Running on Linux, python 3.11
 However I'm getting an error:
```python
Traceback (most recent call last):
  File "/home/adam/Desktop/spcup2024/.venv/bin/pyannote-audio-train", line 5, in <module>
    from pyannote.audio.cli.train import train
  File "/home/adam/Desktop/spcup2024/.venv/lib/python3.11/site-packages/pyannote/audio/cli/train.py", line 27, in <module>
    import hydra
  File "/home/adam/Desktop/spcup2024/.venv/lib/python3.11/site-packages/hydra/__init__.py", line 5, in <module>
    from hydra import utils
  File "/home/adam/Desktop/spcup2024/.venv/lib/python3.11/site-packages/hydra/utils.py", line 8, in <module>
    import hydra._internal.instantiate._instantiate2
  File "/home/adam/Desktop/spcup2024/.venv/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 12, in <module>
    from hydra._internal.utils import _locate
  File "/home/adam/Desktop/spcup2024/.venv/lib/python3.11/site-packages/hydra/_internal/utils.py", line 17, in <module>
    from hydra.core.utils import get_valid_filename, validate_config_path
  File "/home/adam/Desktop/spcup2024/.venv/lib/python3.11/site-packages/hydra/core/utils.py", line 19, in <module>
    from hydra.core.hydra_config import HydraConfig
  File "/home/adam/Desktop/spcup2024/.venv/lib/python3.11/site-packages/hydra/core/hydra_config.py", line 6, in <module>
    from hydra.conf import HydraConf
  File "/home/adam/Desktop/spcup2024/.venv/lib/python3.11/site-packages/hydra/conf/__init__.py", line 45, in <module>
    class JobConf:
  File "/home/adam/Desktop/spcup2024/.venv/lib/python3.11/site-packages/hydra/conf/__init__.py", line 70, in JobConf
    @dataclass
     ^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 1230, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'hydra.conf.JobConf.JobConfig.OverrideDirname'> for field override_dirname is not allowed: use default_factory
```

**Comment by adamkatav** [comment]
Downgrading to python 3.10 resolved it, but a new issue:
```python
$ pyannote-audio-train \                                                                                                                       ✔  spcup2024  ▓▒░
    model=PyanNet \
    task=VoiceActivityDetection \
    protocol=AMI.SpeakerDiarization.only_words
/home/adam/Desktop/spcup2024/.venv/lib/python3.10/site-packages/pyannote/audio/core/io.py:43: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend("soundfile")
/home/adam/Desktop/spcup2024/.venv/lib/python3.10/site-packages/torch_audiomentations/utils/io.py:27: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend("soundfile")
Seed set to 0
Error executing job with overrides: ['model=PyanNet', 'task=VoiceActivityDetection', 'protocol=AMI.SpeakerDiarization.only_words']
An error occurred during Hydra's exception formatting:
TypeError("print_exception() got an unexpected keyword argument 'etype'")
Traceback (most recent call last):
  File "/home/adam/Desktop/spcup2024/.venv/bin/pyannote-audio-train", line 8, in <module>
    sys.exit(train())
  File "/home/adam/Desktop/spcup2024/.venv/lib/python3.10/site-packages/hydra/main.py", line 48, in decorated_main
    _run_hydra(
  File "/home/adam/Desktop/spcup2024/.venv/lib/python3.10/site-packages/hydra/_internal/utils.py", line 377, in _run_hydra
    run_and_report(
  File "/home/adam/Desktop/spcup2024/.venv/lib/python3.10/site-packages/hydra/_internal/utils.py", line 294, in run_and_report
    raise ex
  File "/home/adam/Desktop/spcup2024/.venv/lib/python3.10/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/home/adam/Desktop/spcup2024/.venv/lib/python3.10/site-packages/hydra/_internal/utils.py", line 378, in <lambda>
    lambda: hydra.run(
  File "/home/adam/Desktop/spcup2024/.venv/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 111, in run
    _ = ret.return_value
  File "/home/adam/Desktop/spcup2024/.venv/lib/python3.10/site-packages/hydra/core/utils.py", line 233, in return_value
    raise self._return_value
  File "/home/adam/Desktop/spcup2024/.venv/lib/python3.10/site-packages/hydra/core/utils.py", line 160, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/adam/Desktop/spcup2024/.venv/lib/python3.10/site-packages/pyannote/audio/cli/train.py", line 54, in train
    for database_yml in cfg.registry.split(","):
  File "/home/adam/Desktop/spcup2024/.venv/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 357, in __getattr__
    self._format_and_raise(key=key, value=None, cause=e)
  File "/home/adam/Desktop/spcup2024/.venv/lib/python3.10/site-packages/omegaconf/base.py", line 190, in _format_and_raise
    format_and_raise(
  File "/home/adam/Desktop/spcup2024/.venv/lib/python3.10/site-packages/omegaconf/_utils.py", line 818, in format_and_raise
    _raise(ex, cause)
  File "/home/adam/Desktop/spcup2024/.venv/lib/python3.10/site-packages/omegaconf/_utils.py", line 716, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set end OC_CAUSE=1 for full backtrace
  File "/home/adam/Desktop/spcup2024/.venv/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 351, in __getattr__
    return self._get_impl(key=key, default_value=_DEFAULT_MARKER_)
  File "/home/adam/Desktop/spcup2024/.venv/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 445, in _get_impl
    return self._resolve_with_default(
  File "/home/adam/Desktop/spcup2024/.venv/lib/python3.10/site-packages/omegaconf/basecontainer.py", line 63, in _resolve_with_default
    raise MissingMandatoryValue("Missing mandatory value: $FULL_KEY")
omegaconf.errors.MissingMandatoryValue: Missing mandatory value: registry
    full_key: registry
    object_type=dict

```

**Comment by clement-pages** [comment]
You need to add a `registry` option containing the path to a database.yml file. For instance:
````bash
pyannote-audio-train  \
    model=PyanNet \
    task=VoiceActivityDetection \
    registry="AMI-diarization-setup/pyannote/database.yml" \
    protocol=AMI.SpeakerDiarization.only_words
````
This should fix your issue.
