### ISSUE TITLE
Issue in running pretrained model

### ISSUE THREAD

**Issue by prsnko** [pyannote/pyannote-audio#174]
I have downloaded the develop branch of pynote-audio and pip installed from there. I am having the following error when running tutorial (sad = SequenceLabeling(model=SAD_MODEL)) on pretrained model with my own audio file:

Traceback (most recent call last):
  File "run_diarization.py", line 35, in <module>
    sad = SequenceLabeling(model=SAD_MODEL)
  File "/home/prasanna/.conda/envs/pyannote/lib/python3.6/site-packages/pyannote/audio/labeling/extraction.py", line 71, in __init__
    app = BaseLabeling.from_model_pt(model, training=False)
  File "/home/prasanna/.conda/envs/pyannote/lib/python3.6/site-packages/pyannote/audio/applications/base.py", line 78, in from_model_pt
    app.model_ = app.load_model(epoch, train_dir=train_dir)
  File "/home/prasanna/.conda/envs/pyannote/lib/python3.6/site-packages/pyannote/audio/applications/base.py", line 236, in load_model
    self.model_ = self.get_model_(specifications)
  File "/home/prasanna/.conda/envs/pyannote/lib/python3.6/site-packages/pyannote/audio/labeling/models.py", line 98, in __init__
    raise ValueError(msg)
ValueError: `task_type` must be one of multi_class_classification, multi_label_classification or regression.

 Tried changing value of variable task in specs.yml (within folder for weights of SAD pretrained model) to multi-class but not resolved. Model is binary file, so not sure how to debug there.
 Any help would be highly appreciated.

**Comment by hbredin** [comment]
I recently pushed breaking changes in develop branch. 
Will fix that in the coming days. 

In the meantime, you can try with a slightly older commit (like from 2 weeks ago).

**Comment by prsnko** [comment]
Thanks for quick response. 
I tried checking out 2,4,8,16.. 52 weeks ago. It only checks out HEAD at 966df53 along with following warning:

warning: Log for 'HEAD' only goes back to Sun, 21 Apr 2019 10:59:54 -0700.
HEAD is now at 966df53... fix: fix support of variable length for all models

Is there something I am messing up here?

**Comment by prsnko** [comment]
I did git log and checked out oldest hashcode which was from Friday.
It is working now.
Thanks,
Prasanna

**Comment by hbredin** [comment]
I just pushed a fix for this. 
You should now be able to use the HEAD of develop branch.
