### ISSUE TITLE
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/home/ubuntu/whisperx/pyannote-offline/config.yaml'. Use `repo_type` argument if needed.

### ISSUE THREAD

**Issue by lucasmirachi** [pyannote/pyannote-audio#1800]
### Tested versions

- Reproducible in the last version of pyannote.

### System information

Ubuntu 24.04 

### Issue description

Hi,

I'm trying to use Pyannote for offline diarization without requiring a Hugging Face token. I'm integrating it through the WhisperX repository, following the [Pyannote tutorial for offline usage](https://github.com/pyannote/pyannote-audio/blob/develop/tutorials/community/offline_usage_speaker_diarization.ipynb). Specifically, I created a config.yaml file and downloaded the pytorch.bin model as instructed. However, I am encountering the following error when initializing the DiarizationPipeline:

`ERROR:    Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/opt/conda/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/opt/conda/lib/python3.10/site-packages/fastapi/routing.py", line 133, in merged_lifespan
    async with original_context(app) as maybe_original_state:
  File "/opt/conda/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/workspace/transcription_service/main.py", line 33, in startup
    get_transcriptor()  # Makes sure the transcriptor was initialized
  File "/workspace/transcription_service/services/whisperx.py", line 95, in get_transcriptor
    return WhisperXTranscriptor()
  File "/workspace/transcription_service/services/whisperx.py", line 57, in __init__
    self.diarization_model = whisperx.DiarizationPipeline(device="cuda")
  File "/workspace/whisperx/whisperx/diarize.py", line 19, in __init__
    self.model = Pipeline.from_pretrained(model_name)
  File "/opt/conda/lib/python3.10/site-packages/pyannote/audio/core/pipeline.py", line 88, in from_pretrained
    config_yml = hf_hub_download(
  File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 154, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/home/ubuntu/whisperx/whisperx/pyannote-offline/config.yaml'. Use `repo_type` argument if needed.
`
The error seems to indicate that from_pretrained is expecting a repo_id in the form 'repo_name' or 'namespace/repo_name'. However, the config.yaml file's path is being passed instead. This issue may stem from how the WhisperX repository initializes the diarization pipeline, but I'm unsure if there's a workaround or adjustment needed on the Pyannote side for offline usage.

**Question**
Is this a configuration issue with the config.yaml file?
Should WhisperX handle this differently, or is there a specific way Pyannote should interpret the local model path for offline usage?
I would appreciate any guidance or advice on resolving this issue. Thank you!

Here are the contents of config.yaml:

`version: 3.1.0

pipeline:
  name: pyannote.audio.pipelines.SpeakerDiarization
  params:
    clustering: AgglomerativeClustering
    embedding: pyannote/wespeaker-voxceleb-resnet34-LM
    embedding_batch_size: 32
    embedding_exclude_overlap: true
    segmentation: pyannote-offline/pytorch_model.bin
    segmentation_batch_size: 32

params:
  clustering:
    method: centroid
    min_cluster_size: 12
    threshold: 0.7045654963945799
  segmentation:
    min_duration_off: 0.0
`

### Minimal reproduction example (MRE)

whisperx

**Comment by FrenchKrab** [comment]
Haven't ran things on my side, but your trace runs through this line:
https://github.com/pyannote/pyannote-audio/blob/3e39edd58f548f3533f6dcd7e738379fe829a4e0/pyannote/audio/core/pipeline.py#L132-L133
And to get to this line I think you need `os.path.isfile(checkpoint_path)` to be false (and `checkpoint_path` is your config file path).
The most likely culprit to me is that your `config.yaml` path (`/home/ubuntu/whisperx/whisperx/pyannote-offline/config.yaml`) might be wrong / does not exist.

**Comment by lucasmirachi** [comment]
Thanks @FrenchKrab, I double checked the path and it was probalby wrong, but now I just got a different error message:

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/opt/conda/lib/python3.10/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/opt/conda/lib/python3.10/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/opt/conda/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "/opt/conda/lib/python3.10/site-packages/urllib3/connection.py", line 616, in connect
    self.sock = sock = self._new_conn()
  File "/opt/conda/lib/python3.10/site-packages/urllib3/connection.py", line 205, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x7ecd00a70e20>: Failed to resolve 'huggingface.co' ([Errno -3] Temporary failure in name resolution)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/requests/adapters.py", line 589, in send
    resp = conn.urlopen(
  File "/opt/conda/lib/python3.10/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/opt/conda/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /pyannote-offline/config.yaml/resolve/main/config.yaml (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ecd00a70e20>: Failed to resolve 'huggingface.co' ([Errno -3] Temporary failure in name resolution)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1376, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(
  File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1296, in get_hf_file_metadata
    r = _request_wrapper(
  File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 277, in _request_wrapper
    response = _request_wrapper(
  File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 300, in _request_wrapper
    response = get_session().request(method=method, url=url, **params)
  File "/opt/conda/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/conda/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 93, in send
    return super().send(request, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/requests/adapters.py", line 622, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: (MaxRetryError('HTTPSConnectionPool(host=\'huggingface.co\', port=443): Max retries exceeded with url: /pyannote-offline/config.yaml/resolve/main/config.yaml (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7ecd00a70e20>: Failed to resolve \'huggingface.co\' ([Errno -3] Temporary failure in name resolution)"))'), '(Request ID: 2995acd9-4dda-4e3f-b327-25bedfb36471)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/opt/conda/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/opt/conda/lib/python3.10/site-packages/fastapi/routing.py", line 133, in merged_lifespan
    async with original_context(app) as maybe_original_state:
  File "/opt/conda/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/workspace/transcription_service/main.py", line 33, in startup
    get_transcriptor()  # Makes sure the transcriptor was initialized
  File "/workspace/transcription_service/services/whisperx.py", line 95, in get_transcriptor
    return WhisperXTranscriptor()
  File "/workspace/transcription_service/services/whisperx.py", line 57, in __init__
    self.diarization_model = whisperx.DiarizationPipeline(device="cuda")
  File "/workspace/whisperx/whisperx/diarize.py", line 19, in __init__
    self.model = Pipeline.from_pretrained(model_name)
  File "/opt/conda/lib/python3.10/site-packages/pyannote/audio/core/pipeline.py", line 88, in from_pretrained
    config_yml = hf_hub_download(
  File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 862, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 969, in _hf_hub_download_to_cache_dir
    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
  File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1487, in _raise_on_head_call_error
    raise LocalEntryNotFoundError(
huggingface_hub.errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.
```

My machine does not have access to the internet, but according to the tutorial, it was supposed to work offline, right?

**Comment by FrenchKrab** [comment]
I think it's still a problem with paths not existing. Would need MRE to properly debug.

I think you can set the environment variable `HF_HUB_OFFLINE=1` to prevent it from going online. Maybe it will raise clearer issues to indicate which paths are incorrect ? (not sure, but it doesn't cost much to try)

**Comment by khabibulloevm** [comment]
@FrenchKrab 

config.yaml
```
pipeline:
  name: pyannote.audio.pipelines.SpeakerDiarization
  params:
    clustering: AgglomerativeClustering
    embedding: models/embedding/
    embedding_batch_size: 1
    embedding_exclude_overlap: true
    segmentation: models/segmentation/pytorch_model.bin
    segmentation_batch_size: 32


params:
  clustering:
    method: centroid
    min_cluster_size: 15
    threshold: 0.7153814381597874
  segmentation:
    min_duration_off: 0.5817029604921046
```
Error:

**Comment by khabibulloevm** [comment]
Is it possible to use local models for embeddings rather than uploading from HF?

**Comment by khabibulloevm** [comment]
@clement-pages  Hi Sir, I hope you're doing well! I was wondering if you could help me with an issue I've been facing. Your insights would be greatly appreciated. Thank you in advance!

**Comment by clement-pages** [comment]
Hey @khabibulloevm. I think the path for `embedding` model in your `config.yml` file is incorrect. According to the [tutorial](https://github.com/pyannote/pyannote-audio/blob/main/tutorials/community/offline_usage_speaker_diarization.ipynb), it should be something like `models/embedding/pyannote_model_wespeaker-voxceleb-resnet34-LM.bin` if you want to use local embedding model.

**Comment by khabibulloevm** [comment]
Thank you sir, it is working!)

**Comment by Indrijeet2042** [comment]
(env) (base) kumarindrajeet2402@instance-20250223-210405:~/VideoLLaMA2$ bash scripts/vllava/finetune.sh
WORLD_SIZE: 1
NPROC_PER_NODE: 1
[2025-03-27 05:59:00,381] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-03-27 05:59:00,619] [INFO] [comm.py:637:init_distributed] cdb=None
[2025-03-27 05:59:00,619] [INFO] [comm.py:668:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.
/home/kumarindrajeet2402/VideoLLaMA2/env/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
You are using a model of type qwen2 to instantiate a model of type videollama2_qwen2. This is not supported for all configurations of models and can yield errors.
You are attempting to use Flash Attention 2.0 with a model not initialized on GPU. Make sure to move the model to GPU after initializing it on CPU with `model.to('cuda')`.
[2025-03-27 05:59:01,456] [INFO] [partition_parameters.py:349:__exit__] finished initializing model - num_params = 339, num_elems = 7.62B
Loading checkpoint shards: 100%|███████████████████████████| 4/4 [00:05<00:00,  1.29s/it]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
[2025-03-27 05:59:07,492] [INFO] [partition_parameters.py:349:__exit__] finished initializing model - num_params = 730, num_elems = 7.92B
Traceback (most recent call last):
  File "/home/kumarindrajeet2402/VideoLLaMA2/videollama2/train.py", line 574, in <module>
    train("flash_attention_2")
  File "/home/kumarindrajeet2402/VideoLLaMA2/videollama2/train.py", line 496, in train
    model.get_model().initialize_vision_modules(model_args=model_args, fsdp=training_args.fsdp)
  File "/home/kumarindrajeet2402/VideoLLaMA2/./videollama2/model/videollama2_arch.py", line 89, in initialize_vision_modules
    mm_projector_weights = load_mm_projector(pretrain_mm_mlp_adapter)
  File "/home/kumarindrajeet2402/VideoLLaMA2/./videollama2/model/projector.py", line 59, in load_mm_projector
    snapshot_download(repo_id=model_path, cache_dir=cache_dir, token=token)
  File "/home/kumarindrajeet2402/VideoLLaMA2/env/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "/home/kumarindrajeet2402/VideoLLaMA2/env/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 154, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'work_dirs/videollama2qwen2_vllava/pretrain_siglip_tcv35_7b_16f'. Use `repo_type` argument if needed.
[2025-03-27 05:59:15,477] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 13102) of binary: /home/kumarindrajeet2402/VideoLLaMA2/env/bin/python
Traceback (most recent call last):
  File "/home/kumarindrajeet2402/VideoLLaMA2/env/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/kumarindrajeet2402/VideoLLaMA2/env/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/home/kumarindrajeet2402/VideoLLaMA2/env/lib/python3.10/site-packages/torch/distributed/run.py", line 812, in main
    run(args)
  File "/home/kumarindrajeet2402/VideoLLaMA2/env/lib/python3.10/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/home/kumarindrajeet2402/VideoLLaMA2/env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/kumarindrajeet2402/VideoLLaMA2/env/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
videollama2/train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-03-27_05:59:15
  host      : instance-20250223-210405.us-central1-a.c.research-436913.internal
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 13102)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
(env) (base) kumarindrajeet2402@instance-20250223-210405:~/VideoLLaMA2$                 Could you guide me why i am getting the error?

**Comment by clement-pages** [comment]
Hey @Indrijeet2042, your error logs are quite difficult to read, but according to this line:
```` 
raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name':
````
I think it could be a path issue. Please double check the path to your model in the `config.yml` file.
