### ISSUE TITLE
求助！ error when run "pip install ."

### ISSUE THREAD

**Issue by TTTJJJWWW** [pyannote/pyannote-audio#225]
Hi! @hbredin 
some errors when i run "pip install ."
`Running setup.py install for dlib ... error
    ERROR: Command errored out with exit status 1:
     command: /home/iie/.conda/envs/pyannote36/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-31re1v5f/dlib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-31re1v5f/dlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-frn0dyif/install-record.txt --single-version-externally-managed --compile
         cwd: /tmp/pip-install-31re1v5f/dlib/
    Complete output (55 lines):
    running install
    running build
    running build_py
    package init file 'dlib/__init__.py' not found (or not a regular file)
    running build_ext
    Traceback (most recent call last):
      File "/tmp/pip-install-31re1v5f/dlib/setup.py", line 120, in get_cmake_version
        out = subprocess.check_output(['cmake', '--version'])
      File "/home/iie/.conda/envs/pyannote36/lib/python3.6/subprocess.py", line 336, in check_output
        **kwargs).stdout
      File "/home/iie/.conda/envs/pyannote36/lib/python3.6/subprocess.py", line 403, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/home/iie/.conda/envs/pyannote36/lib/python3.6/subprocess.py", line 709, in __init__
        restore_signals, start_new_session)
      File "/home/iie/.conda/envs/pyannote36/lib/python3.6/subprocess.py", line 1344, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'cmake': 'cmake'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-31re1v5f/dlib/setup.py", line 261, in <module>
        'Topic :: Software Development',
      File "/home/iie/.conda/envs/pyannote36/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/home/iie/.conda/envs/pyannote36/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/iie/.conda/envs/pyannote36/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/home/iie/.conda/envs/pyannote36/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/iie/.conda/envs/pyannote36/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/iie/.conda/envs/pyannote36/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/home/iie/.conda/envs/pyannote36/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/iie/.conda/envs/pyannote36/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/iie/.conda/envs/pyannote36/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/home/iie/.conda/envs/pyannote36/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/iie/.conda/envs/pyannote36/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-31re1v5f/dlib/setup.py", line 129, in run
        cmake_version = self.get_cmake_version()
      File "/tmp/pip-install-31re1v5f/dlib/setup.py", line 125, in get_cmake_version
        "\n*******************************************************************\n")
    RuntimeError:
    *******************************************************************
     CMake must be installed to build the following extensions: dlib
    *******************************************************************
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/iie/.conda/envs/pyannote36/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-31re1v5f/dlib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-31re1v5f/dlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-frn0dyif/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.
`
how can i fix this?

**Comment by hbredin** [comment]
Lots of people are having issues with the installation of `dlib` (see #159).

Start by removing `dlib` from the list of dependencies in `requirements.txt` and this should fix your installation problem.

If you feel like contributing a long-term fix, maybe you can help with #223

**Comment by TTTJJJWWW** [comment]
@hbredin thanks！
