### ISSUE TITLE
Could not find file

### ISSUE THREAD

**Issue by yining4869** [pyannote/pyannote-audio#257]
Hi @hbredin,
I followed the steps give from https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/models/overlap_detection, but the code can't get noise files from the path I set in ~/.pyannote/database.yml.

In my case I copied 
'Databases:
  AMI: /home/yininggao/amicorpus/*/audio/{uri}.wav
  MUSAN: /home/yininggao/musan/{uri}.wav' in db.yml.' in my database.yml
Here is the error:

Traceback (most recent call last): File "pyann.py", line 9, in <module> for current_file in protocol.test(): File "/home/rehan/anaconda3/envs/pyannote/lib/python3.6/site-packages/pyannote/database/protocol/speaker_diarization.py", line 157, in test yield self.preprocess(item) File "/home/rehan/anaconda3/envs/pyannote/lib/python3.6/site-packages/pyannote/database/protocol/protocol.py", line 89, in preprocess current_file[key] = preprocessor(current_file) File "/home/rehan/anaconda3/envs/pyannote/lib/python3.6/site-packages/pyannote/database/util.py", line 316, in __call__ raise ValueError(msg.format(uri=uri)) ValueError: Could not find file "EN2002b.Mix-Headset".

I have tried all the solutions I found from the internet but the code still reports the same error. Could you help me to fix it? 

Thanks so much!

**Comment by hbredin** [comment]
It complains about not finding file `EN2002b.Mix-Headset.wav`
Is it somewhere in `/home/yininggao/amicorpus/*/audio/`?

**Comment by yining4869** [comment]
Thanks for you quick reply!
I feel so sorry that I pasted a similar error that someone else had encountered before. The error I encounted is showing below:
Traceback (most recent call last):
  File "/home/yininggao/anaconda3/envs/pyannote/bin/pyannote-overlap-detection", line 8, in <module>
    sys.exit(main())
  File "/home/yininggao/anaconda3/envs/pyannote/lib/python3.6/site-packages/pyannote/audio/applications/overlap_detection.py", line 309, in main
    training=True)
  File "/home/yininggao/anaconda3/envs/pyannote/lib/python3.6/site-packages/pyannote/audio/applications/base_labeling.py", line 49, in __init__
    experiment_dir, db_yml=db_yml, training=training)
  File "/home/yininggao/anaconda3/envs/pyannote/lib/python3.6/site-packages/pyannote/audio/applications/base.py", line 186, in __init__
    **self.config_['data_augmentation'].get('params', {}))
  File "/home/yininggao/anaconda3/envs/pyannote/lib/python3.6/site-packages/pyannote/audio/augmentation/noise.py", line 84, in __init__
    self.files_.extend(protocol.files())
  File "/home/yininggao/anaconda3/envs/pyannote/lib/python3.6/site-packages/pyannote/database/protocol/collection.py", line 78, in files
    yield self.preprocess(item)
  File "/home/yininggao/anaconda3/envs/pyannote/lib/python3.6/site-packages/pyannote/database/protocol/protocol.py", line 89, in preprocess
    current_file[key] = preprocessor(current_file)
  File "/home/yininggao/anaconda3/envs/pyannote/lib/python3.6/site-packages/pyannote/database/util.py", line 317, in __call__
    raise ValueError(msg.format(uri=uri))
ValueError: Could not find file "noise/free-sound/noise-free-sound-0232".

And the file is actually in the path:/home/yininggao/musan/noise/free-sound/noise-free-sound-0232.wav

Sorry for taking you time! I truly appreciate your timely help！
<img width="748" alt="1" src="https://user-images.githubusercontent.com/24437017/71140557-8dcb6f00-224c-11ea-8b0b-008b17fd1f27.png">
<img width="230" alt="2" src="https://user-images.githubusercontent.com/24437017/71140561-8e640580-224c-11ea-8213-3dc47ab23c82.png">
![3](https://user-images.githubusercontent.com/24437017/71140562-8e640580-224c-11ea-8084-41f0f76d0e27.jpg)

**Comment by hbredin** [comment]
You closed the issue. How did you solve it? It might be useful for others...

**Comment by yining4869** [comment]
> You closed the issue. How did you solve it? It might be useful for others...

Sorry, I just saw your message.
The wrong location of the configuration file caused this error, so I just put the file database.yml in the right location:

> ~/.pyannote/database.yml

And it works!
