### ISSUE TITLE
Unable to use pre-trained models with torch.hub.load

### ISSUE THREAD

**Issue by couch-potahto** [pyannote/pyannote-audio#278]
I am following the tutorial to test the pre-trained models for Speaking Change Detection on my own existing dataset. Upon running the code `scd = torch.hub.load('pyannote/pyannote-audio', 'scd_ami')`, I receive an error `FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/torch/hub/pyannote_pyannote-audio_master/hubconf.py'`. 

I have already pulled new changes from the repository down to my computer. The full error trace is as follows:

`Using cache found in /root/.cache/torch/hub/pyannote_pyannote-audio_master
Traceback (most recent call last):
  File "./test_script.py", line 6, in <module>
    scd = torch.hub.load('pyannote/pyannote-audio', 'scd_ami')
  File "/root/anaconda3/envs/pyannote_duo/lib/python3.6/site-packages/torch/hub.py", line 355, in load
    hub_module = import_module(MODULE_HUBCONF, repo_dir + '/' + MODULE_HUBCONF)
  File "/root/anaconda3/envs/pyannote_duo/lib/python3.6/site-packages/torch/hub.py", line 72, in import_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 780, in get_code
  File "<frozen importlib._bootstrap_external>", line 832, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/torch/hub/pyannote_pyannote-audio_master/hubconf.py'`

Please advise on this issue. Thank you!

**Comment by hbredin** [comment]
Thanks for reporting the issue.

Until a new version is released, pretrained models are only available in the `develop` branch.
Try with `scd = torch.hub.load('pyannote/pyannote-audio:develop', 'scd_ami')` instead.

**Comment by couch-potahto** [comment]
After following your advice, I am faced with this new error:
`ImportError: cannot import name 'Pretrained'`

The error trace is as follows:
`Downloading: "https://github.com/pyannote/pyannote-audio/archive/develop.zip" to /root/.cache/torch/hub/develop.zip
Traceback (most recent call last):
  File "./test_script.py", line 6, in <module>
    scd = torch.hub.load('pyannote/pyannote-audio:develop', 'scd_ami')
  File "/root/anaconda3/envs/pyannote_duo/lib/python3.6/site-packages/torch/hub.py", line 355, in load
    hub_module = import_module(MODULE_HUBCONF, repo_dir + '/' + MODULE_HUBCONF)
  File "/root/anaconda3/envs/pyannote_duo/lib/python3.6/site-packages/torch/hub.py", line 72, in import_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/.cache/torch/hub/pyannote_pyannote-audio_develop/hubconf.py", line 37, in <module>
    from pyannote.audio.features import Pretrained
ImportError: cannot import name 'Pretrained'`

**Comment by hbredin** [comment]
Looks like you are not using the latest version of `develop` branch.
Can you pull the latest commits and try again?

**Comment by couch-potahto** [comment]
I just executed a git pull but am still faced with the same problem. The error trace is still the same

**Comment by hbredin** [comment]
Looks like you did not re-install `pyannote.audio` after pulling the latest commits:
`pyannote.core` dependency has been updated in [`requirements.txt`](https://github.com/pyannote/pyannote-audio/blob/develop/requirements.txt#L4). 

Either re-install `pyannote.audio` or simply update `pyannote.core`:
```bash
pip install pyannote.core==3.4
```

**Comment by couch-potahto** [comment]
Thank you for your help! That solved the problem

**Comment by salisbury-espinosa** [comment]
> Thanks for reporting the issue.
> 
> Until a new version is released, pretrained models are only available in the `develop` branch.
> Try with `scd = torch.hub.load('pyannote/pyannote-audio:develop', 'scd_ami')` instead.

need update documentation https://github.com/pyannote/pyannote-audio/tree/develop/tutorials/pretrained

**Comment by hbredin** [comment]
Tutorial has been updated in 0d82f87.
