### ISSUE TITLE
ValueError: SincNet only supports mono waveforms. Here, waveform has 59 channels.

### ISSUE THREAD

**Issue by alamnasim** [pyannote/pyannote-audio#298]
Hi,
I am facing this issue when I run sad and scd training on one of my dataset.
Full error log:
pyannote-audio sad train --subset=train --to=100 --parallel=4 ${EXPERIMENT_DIR} odiosd.SpeakerDiarization.Hinglish

Training set: 0it [00:00, ?it/s]/home/nasim.ezeia/anaconda3/envs/pyannote_new/lib/python3.7/site-packages/pyannote/database/util.py:257: UserWarning: "annotated" was approximated by [0, audio duration].
  warnings.warn(msg)
Training set: 2651it [57:49,  1.31s/it]
Training set: 2651it [1:43:30,  2.34s/it]
Traceback (most recent call last):
  File "/home/nasim.ezeia/anaconda3/envs/pyannote_new/bin/pyannote-audio", line 8, in <module>
    sys.exit(main())
  File "/home/nasim.ezeia/anaconda3/envs/pyannote_new/lib/python3.7/site-packages/pyannote/audio/applications/pyannote_audio.py", line 333, in main
    app.train(protocol, **params)
  File "/home/nasim.ezeia/anaconda3/envs/pyannote_new/lib/python3.7/site-packages/pyannote/audio/applications/base.py", line 190, in train
    model = self.get_model_from_specs_(batch_generator.specifications)
  File "/home/nasim.ezeia/anaconda3/envs/pyannote_new/lib/python3.7/site-packages/pyannote/audio/train/model.py", line 79, in __init__
    self.init(**architecture_params)
  File "/home/nasim.ezeia/anaconda3/envs/pyannote_new/lib/python3.7/site-packages/pyannote/audio/models/models.py", line 442, in init
    raise ValueError(msg)
ValueError: SincNet only supports mono waveforms. Here, waveform has 59 channels.

My config file for sad:
task:
   name: SpeechActivityDetection
   params:
      duration: 2.0      
      batch_size: 64     
      per_epoch: 1       

feature_extraction:
   name: Precomputed      
   params:
      root_dir: tutorials/feature_extraction

architecture:
   name: pyannote.audio.models.PyanNet
   params:
      rnn:
         unit: LSTM
         hidden_size: 128
         num_layers: 2
         bidirectional: True
      ff:
         hidden_size: [128, 128]
scheduler:
   name: ConstantScheduler
   params:
      learning_rate: 0.01

metadata.yml for feature extraction part:
dimension: 59
duration: 0.025
start: -0.0125
step: 0.01

My question is since the dimension is calculated during feature extraction how it would be 2 for the mono channel?
Is it a bug in code or some problem in my dataset?

Thanks, please help me to solve this issue.

**Comment by juanmc2005** [comment]
Hello,
I think your problem might be that the configuration defaults to using SincNet from the raw waveform, whereas you are apparently using features like MFCC.
Can you try replacing your architecture configuration to this ?

```yaml
architecture:
    name: pyannote.audio.models.PyanNet
    params:
        sincnet:
            skip: True
        rnn:
            unit: LSTM
            hidden_size: 128
            num_layers: 2
            bidirectional: True
        ff:
            hidden_size: [128, 128]
```

This should ignore the SincNet layer.

**Comment by alamnasim** [comment]
Thanks
After doing the above changes, I am getting this error.

Training set: 2651it [45:49,  1.04s/it]
Training set: 0it [00:00, ?it/s]Traceback (most recent call last):
  File "/home/nasim.ezeia/anaconda3/envs/pyannote_new/bin/pyannote-audio", line 8, in <module>
    sys.exit(main())
  File "/home/nasim.ezeia/anaconda3/envs/pyannote_new/lib/python3.7/site-packages/pyannote/audio/applications/pyannote_audio.py", line 333, in main
    app.train(protocol, **params)
  File "/home/nasim.ezeia/anaconda3/envs/pyannote_new/lib/python3.7/site-packages/pyannote/audio/applications/base.py", line 187, in train
    alignment=self.model_alignment_)
  File "/home/nasim.ezeia/anaconda3/envs/pyannote_new/lib/python3.7/site-packages/pyannote/audio/labeling/tasks/speech_activity_detection.py", line 142, in get_batch_generator
    batch_size=self.batch_size)
  File "/home/nasim.ezeia/anaconda3/envs/pyannote_new/lib/python3.7/site-packages/pyannote/audio/labeling/tasks/base.py", line 147, in __init__   
    total_duration = self._load_metadata(protocol, subset=subset)
  File "/home/nasim.ezeia/anaconda3/envs/pyannote_new/lib/python3.7/site-packages/pyannote/audio/labeling/tasks/base.py", line 284, in _load_metadata
    self.data_[uri]['y'] = self.initialize_y(current_file)
  File "/home/nasim.ezeia/anaconda3/envs/pyannote_new/lib/python3.7/site-packages/pyannote/audio/labeling/tasks/base.py", line 185, in initialize_y
    mode='center')
  File "/home/nasim.ezeia/anaconda3/envs/pyannote_new/lib/python3.7/site-packages/pyannote/core/utils/numpy.py", line 69, in one_hot_encoding
    raise TypeError(msg)
TypeError: `window` must be an instance of `SlidingWindow` or have an attribute called 'sliding_window'.
Training set: 0it [00:28, ?it/s]

**Comment by hbredin** [comment]
Thanks for catching this bug.
This should be fixed in `develop` branch.
