### ISSUE TITLE
There is something wrong with augment when use 8000 sample rate.

### ISSUE THREAD

**Issue by Naminwang** [pyannote/pyannote-audio#349]
**### I have some 8000 sample rate wavs, so i changed the config.yml：feature_extraction sample_rate to 8000. But there is an error in augmentation step, the error message like:** 
_Traceback (most recent call last):3:23, 15.90s/batch, loss=0.975, loss_classification=0.975]
  File "/root/anaconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/root/anaconda3/lib/python3.7/site-packages/pyannote/audio/utils/background.py", line 188, in run
    sample = next(self.producer_)
  File "/root/anaconda3/lib/python3.7/site-packages/pyannote/audio/train/generator.py", line 103, in __call__
    next_batch = next(batches)
  File "/root/anaconda3/lib/python3.7/site-packages/pescador/maps.py", line 130, in buffer_stream
    for item in stream:
  File "/root/anaconda3/lib/python3.7/site-packages/pyannote/audio/embedding/generators.py", line 227, in samples
    fixed=batch_duration),
  File "/root/anaconda3/lib/python3.7/site-packages/pyannote/audio/features/utils.py", line 346, in crop
    return self.get_features(data, sample_rate)
  File "/root/anaconda3/lib/python3.7/site-packages/pyannote/audio/features/utils.py", line 176, in get_features
    y = self.augmentation(y, sample_rate)
  File "/root/anaconda3/lib/python3.7/site-packages/pyannote/audio/augmentation/noise.py", line 135, in __call__
    return normalize(original) + alpha * noise
ValueError: operands could not be broadcast together with shapes (16000,1) (16001,1)_

**Comment by picheny-nyu** [comment]
See closed issue #300

**Comment by Naminwang** [comment]
When i downsample the musan dataset to 8khz, all things run well.

**Comment by hbredin** [comment]
Closing as I understand that the original issue has been solved.
