### ISSUE TITLE
Key Error  - Audio while trying to train default models in the speaker diarization tutorial

### ISSUE THREAD

**Issue by sangeetaghangam** [pyannote/pyannote-audio#364]
I am running into the following error while trying to follow the tutorial for Speaker Diarization. I am using the pre-trained models to understand the pipeline. Is it because I am using pretrained models? or maybe models from the master branch?

(base) spc@u02052020000:~$ export PYANNOTE_DATABASE_CONFIG=/export/corpora/amidata/database.yml 
(base) spc@u02052020000:~$ cd pyannote-audio/
(base) spc@u02052020000:~/pyannote-audio$ export EXP_DIR=tutorials/pipelines/speaker_diarization

(base) spc@u02052020000:~/pyannote-audio$ for SUBSET in development test; do for TASK in sad scd emb;  do   pyannote-audio ${TASK} apply --step=0.1 --pretrained=${TASK}_ami --subset=${SUBSET} ${EXP_DIR} AMI.SpeakerDiarization.MixHeadset;  done; done
Using cache found in /home/spc/.cache/torch/hub/pyannote_pyannote-audio_master
Using cache found in /home/spc/.cache/torch/hub/pyannote_pyannote-audio_master
Development set: 26it [08:56, 20.64s/it]
Development set: 26it [01:00,  2.31s/it]
Using cache found in /home/spc/.cache/torch/hub/pyannote_pyannote-audio_master
Using cache found in /home/spc/.cache/torch/hub/pyannote_pyannote-audio_master
Development set: 26it [08:56, 20.65s/it]
Development set: 26it [00:14,  1.75it/s]
Using cache found in /home/spc/.cache/torch/hub/pyannote_pyannote-audio_master
Using cache found in /home/spc/.cache/torch/hub/pyannote_pyannote-audio_master
Development set: 26it [01:19,  3.06s/it]
Using cache found in /home/spc/.cache/torch/hub/pyannote_pyannote-audio_master
Using cache found in /home/spc/.cache/torch/hub/pyannote_pyannote-audio_master
Test set: 24it [08:55, 22.30s/it]
Test set: 24it [01:01,  2.54s/it]
Using cache found in /home/spc/.cache/torch/hub/pyannote_pyannote-audio_master
Using cache found in /home/spc/.cache/torch/hub/pyannote_pyannote-audio_master
Test set: 24it [08:49, 22.08s/it]
Test set: 24it [00:14,  1.66it/s]
Using cache found in /home/spc/.cache/torch/hub/pyannote_pyannote-audio_master
Using cache found in /home/spc/.cache/torch/hub/pyannote_pyannote-audio_master
Test set: 24it [01:19,  3.31s/it]
(base) spc@u02052020000:~/pyannote-audio$ pyannote-pipeline train --subset=development --forever ${EXP_DIR} AMI.SpeakerDiarization.MixHeadset
Using cache found in /home/spc/.cache/torch/hub/pyannote_pyannote-audio_master
Using cache found in /home/spc/.cache/torch/hub/pyannote_pyannote-audio_master
Using cache found in /home/spc/.cache/torch/hub/pyannote_pyannote-audio_master
Using cache found in /home/spc/.cache/torch/hub/pyannote_pyannote-audio_master
Waiting for first iteration to complete: : 0iteration [00:00, ?iteration/s][W 2020-04-27 00:32:21,917] Setting status of trial#0 as TrialState.FAIL because of the following error: KeyError('audio')
Traceback (most recent call last):
  File "/home/spc/anaconda3/lib/python3.7/site-packages/optuna/study.py", line 677, in _run_trial
    result = func(trial)
  File "/home/spc/anaconda3/lib/python3.7/site-packages/pyannote/pipeline/optimizer.py", line 184, in objective
    output = pipeline(input)
  File "/home/spc/pyannote-audio/pyannote/audio/pipeline/speaker_diarization.py", line 154, in __call__
    speech_turns = self.speech_turn_segmentation(current_file)
  File "/home/spc/pyannote-audio/pyannote/audio/pipeline/speech_turn_segmentation.py", line 123, in __call__
    sad = self.speech_activity_detection(current_file).get_timeline()
  File "/home/spc/pyannote-audio/pyannote/audio/pipeline/speech_activity_detection.py", line 139, in __call__
    sad_scores = self._scores(current_file)
  File "/home/spc/pyannote-audio/pyannote/audio/features/wrapper.py", line 274, in __call__
    return self.scorer_(current_file)
  File "/home/spc/pyannote-audio/pyannote/audio/features/base.py", line 149, in __call__
    y, sample_rate = self.raw_audio_(current_file, return_sr=True)
  File "/home/spc/pyannote-audio/pyannote/audio/features/utils.py", line 229, in __call__
    current_file["audio"], dtype="float32", always_2d=True
  File "/home/spc/anaconda3/lib/python3.7/site-packages/pyannote/database/protocol/protocol.py", line 102, in __getitem__
    return self._store[key]
KeyError: 'audio'
Traceback (most recent call last):
  File "/home/spc/anaconda3/bin/pyannote-pipeline", line 8, in <module>
    sys.exit(main())
  File "/home/spc/anaconda3/lib/python3.7/site-packages/pyannote/pipeline/experiment.py", line 427, in main
    pretrained=pretrained, sampler=sampler, pruner=pruner)
  File "/home/spc/anaconda3/lib/python3.7/site-packages/pyannote/pipeline/experiment.py", line 281, in train
    for i, status in zip(count, iterations):
  File "/home/spc/anaconda3/lib/python3.7/site-packages/pyannote/pipeline/optimizer.py", line 288, in tune_iter
    timeout=None, n_jobs=1)
  File "/home/spc/anaconda3/lib/python3.7/site-packages/optuna/study.py", line 331, in optimize
    func, n_trials, timeout, catch, callbacks, gc_after_trial, None
  File "/home/spc/anaconda3/lib/python3.7/site-packages/optuna/study.py", line 626, in _optimize_sequential
    self._run_trial_and_callbacks(func, catch, callbacks, gc_after_trial)
  File "/home/spc/anaconda3/lib/python3.7/site-packages/optuna/study.py", line 656, in _run_trial_and_callbacks
    trial = self._run_trial(func, catch, gc_after_trial)
  File "/home/spc/anaconda3/lib/python3.7/site-packages/optuna/study.py", line 677, in _run_trial
    result = func(trial)
  File "/home/spc/anaconda3/lib/python3.7/site-packages/pyannote/pipeline/optimizer.py", line 184, in objective
    output = pipeline(input)
  File "/home/spc/pyannote-audio/pyannote/audio/pipeline/speaker_diarization.py", line 154, in __call__
    speech_turns = self.speech_turn_segmentation(current_file)
  File "/home/spc/pyannote-audio/pyannote/audio/pipeline/speech_turn_segmentation.py", line 123, in __call__
    sad = self.speech_activity_detection(current_file).get_timeline()
  File "/home/spc/pyannote-audio/pyannote/audio/pipeline/speech_activity_detection.py", line 139, in __call__
    sad_scores = self._scores(current_file)
  File "/home/spc/pyannote-audio/pyannote/audio/features/wrapper.py", line 274, in __call__
    return self.scorer_(current_file)
  File "/home/spc/pyannote-audio/pyannote/audio/features/base.py", line 149, in __call__
    y, sample_rate = self.raw_audio_(current_file, return_sr=True)
  File "/home/spc/pyannote-audio/pyannote/audio/features/utils.py", line 229, in __call__
    current_file["audio"], dtype="float32", always_2d=True
  File "/home/spc/anaconda3/lib/python3.7/site-packages/pyannote/database/protocol/protocol.py", line 102, in __getitem__
    return self._store[key]
KeyError: 'audio'
Waiting for first iteration to complete: : 0iteration [00:01, ?iteration/s]

**Comment by sangeetaghangam** [comment]
Yes I ran the Raw extraction scores
(base) spc@u02052020000:~/pyannote-audio$ for SUBSET in development test; do for TASK in sad scd emb;  do   pyannote-audio ${TASK} apply --step=0.1 --pretrained=${TASK}_ami --subset=${SUBSET} ${EXP_DIR} AMI.SpeakerDiarization.MixHeadset;  done; done
Using cache found in /home/spc/.cache/torch/hub/pyannote_pyannote-audio_master
Using cache found in /home/spc/.cache/torch/hub/pyannote_pyannote-audio_master
Development set: 26it [08:56, 20.64s/it]
Development set: 26it [01:00,  2.31s/it]
Using cache found in /home/spc/.cache/torch/hub/pyannote_pyannote-audio_master
Using cache found in /home/spc/.cache/torch/hub/pyannote_pyannote-audio_master
Development set: 26it [08:56, 20.65s/it]
Development set: 26it [00:14,  1.75it/s]
Using cache found in /home/spc/.cache/torch/hub/pyannote_pyannote-audio_master
Using cache found in /home/spc/.cache/torch/hub/pyannote_pyannote-audio_master
Development set: 26it [01:19,  3.06s/it]
Using cache found in /home/spc/.cache/torch/hub/pyannote_pyannote-audio_master
Using cache found in /home/spc/.cache/torch/hub/pyannote_pyannote-audio_master
Test set: 24it [08:55, 22.30s/it]
Test set: 24it [01:01,  2.54s/it]
Using cache found in /home/spc/.cache/torch/hub/pyannote_pyannote-audio_master
Using cache found in /home/spc/.cache/torch/hub/pyannote_pyannote-audio_master
Test set: 24it [08:49, 22.08s/it]
Test set: 24it [00:14,  1.66it/s]
Using cache found in /home/spc/.cache/torch/hub/pyannote_pyannote-audio_master
Using cache found in /home/spc/.cache/torch/hub/pyannote_pyannote-audio_master
Test set: 24it [01:19,  3.31s/it]

Contents of config.yml file
pipeline:
   name: pyannote.audio.pipeline.speaker_diarization.SpeakerDiarization
   params:
      sad_scores: sad_ami
      scd_scores: scd_ami
      embedding: emb_ami
      evaluation_only: True

freeze:
   speech_turn_segmentation:
      speech_activity_detection:
         min_duration_off: 0.6315121069334447
         min_duration_on: 0.0007366523493967721
         offset: 0.5727193137037349
         onset: 0.5842225805454029
         pad_offset: 0.0
         pad_onset: 0.0

**Comment by hbredin** [comment]
As stated in the tutorial, 

```yaml
      sad_scores: sad_ami
      scd_scores: scd_ami
      embedding: emb_ami
```

should read

```yaml
      sad_scores: {EXP_DIR}/sad_ami
      scd_scores: {EXP_DIR}/scd_ami
      embedding: {EXP_DIR}/emb_ami
```
where `{EXP_DIR}` has been replaced by its actual value.

**Comment by sangeetaghangam** [comment]
Yup, I updated it and it's running now
