### ISSUE TITLE
RuntimeError: NNPACK SpatialConvolution_updateOutput failed

### ISSUE THREAD

**Issue by serene9199** [pyannote/pyannote-audio#393]
Hi,

I tried running the pre-trained model for speaker diarization as specified in the tutorial, on my system (Ubuntu 19.04, Python 3.7.6, pytorch 1.3.1), however the error given below is generated. 

The model is loaded correctly with `pipeline = torch.hub.load('pyannote/pyannote-audio', 'dia')`, but the error is produced on executing `diarization = pipeline(OWN_FILE)`. 

Traceback (most recent call last):
  File "pyannote1.py", line 31, in <module>
    diarization = pipeline(OWN_FILE)
  File "/home/serene/anaconda3/envs/myenv/lib/python3.7/site-packages/pyannote/audio/pipeline/speaker_diarization.py", line 154, in __call__
    speech_turns = self.speech_turn_segmentation(current_file)
  File "/home/serene/anaconda3/envs/myenv/lib/python3.7/site-packages/pyannote/audio/pipeline/speech_turn_segmentation.py", line 123, in __call__
    sad = self.speech_activity_detection(current_file).get_timeline()
  File "/home/serene/anaconda3/envs/myenv/lib/python3.7/site-packages/pyannote/audio/pipeline/speech_activity_detection.py", line 139, in __call__
    sad_scores = self._scores(current_file)
  File "/home/serene/anaconda3/envs/myenv/lib/python3.7/site-packages/pyannote/audio/features/wrapper.py", line 280, in __call__
    return self.scorer_(current_file)
  File "/home/serene/anaconda3/envs/myenv/lib/python3.7/site-packages/pyannote/audio/features/base.py", line 152, in __call__
    features = self.get_features(y.data, sample_rate)
  File "/home/serene/anaconda3/envs/myenv/lib/python3.7/site-packages/pyannote/audio/features/pretrained.py", line 232, in get_features
    progress_hook=self.progress_hook,
  File "/home/serene/anaconda3/envs/myenv/lib/python3.7/site-packages/pyannote/audio/train/model.py", line 468, in slide
    tfX = self(tX, return_intermediate=return_intermediate)
  File "/home/serene/anaconda3/envs/myenv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/serene/anaconda3/envs/myenv/lib/python3.7/site-packages/pyannote/audio/models/models.py", line 540, in forward
    output = self.sincnet_(waveforms)
  File "/home/serene/anaconda3/envs/myenv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/serene/anaconda3/envs/myenv/lib/python3.7/site-packages/pyannote/audio/models/sincnet.py", line 424, in forward
    output = conv1d(output)
  File "/home/serene/anaconda3/envs/myenv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/serene/anaconda3/envs/myenv/lib/python3.7/site-packages/pyannote/audio/models/sincnet.py", line 212, in forward
    groups=1,
RuntimeError: NNPACK SpatialConvolution_updateOutput failed

Kindly suggest a solution to resolve the same.
Any help is appreciated.

Thanks,
Serene

**Comment by hbredin** [comment]
Before I have a closer look, can you please try with the last version of pytorch (1.5) ? 
If it still does not work, can you please share the audio file that leads to this error?

**Comment by serene9199** [comment]
Hi, 

I've tried it as you suggested. Thank you for the response.
