### ISSUE TITLE
Error in apply mode

### ISSUE THREAD

**Issue by nikopartanen** [pyannote/pyannote-audio#40]
When running the apply-command I get a following error message. This comes after I have run the tune-command with the result that I describe in issue #39.

    /Users/niko/anaconda3/envs/py35-pyannote-audio/lib/python3.5/site-packages/keras/models.py:245: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
      warnings.warn('No training configuration found in save file: '
    Test set: 0it [00:00, ?it/s]
    Traceback (most recent call last):
      File "/Users/niko/anaconda3/envs/py35-pyannote-audio/bin/pyannote-speech-detection", line 11, in <module>
        sys.exit(main())
      File "/Users/niko/anaconda3/envs/py35-pyannote-audio/lib/python3.5/site-packages/pyannote/audio/applications/speech_detection.py", line 615, in main
        application.apply(protocol_name, subset=subset)
      File "/Users/niko/anaconda3/envs/py35-pyannote-audio/lib/python3.5/site-packages/pyannote/audio/applications/speech_detection.py", line 565, in apply
    precomputed = Precomputed(root_dir=apply_dir)
      File "/Users/niko/anaconda3/envs/py35-pyannote-audio/lib/python3.5/site-packages/pyannote/audio/features/utils.py", line 110, in __init__
        start = f.attrs['start']
      File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/Users/travis/miniconda3/conda-bld/h5py_1496412421941/work/h5py-2.7.0/h5py/_objects.c:2846)
      File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/Users/travis/miniconda3/conda-bld/h5py_1496412421941/work/h5py-2.7.0/h5py/_objects.c:2804)
      File "/Users/niko/anaconda3/envs/py35-pyannote-audio/lib/python3.5/site-packages/h5py/_hl/attrs.py", line 58, in __getitem__
        attr = h5a.open(self._id, self._e(name))
      File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/Users/travis/miniconda3/conda-bld/h5py_1496412421941/work/h5py-2.7.0/h5py/_objects.c:2846)
      File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/Users/travis/miniconda3/conda-bld/h5py_1496412421941/work/h5py-2.7.0/h5py/_objects.c:2804)
      File "h5py/h5a.pyx", line 77, in h5py.h5a.open (/Users/travis/miniconda3/conda-bld/h5py_1496412421941/work/h5py-2.7.0/h5py/h5a.c:2343)
    KeyError: "Can't open attribute (Can't locate attribute: 'start')"

**Comment by hbredin** [comment]
I believe this is the same as #39.
Default subset for "apply" mode is "test". 
Does your protocol define a test set?

**Comment by nikopartanen** [comment]
I solved this problem now with instructions in issue #39. Thanks for help! The only remaining warning I get is this:

    UserWarning: "get_audio_duration" now expects a dict. Please update your code.
      warnings.warn('"get_audio_duration" now expects a dict. '

But this doesn't seem to be a problem, just wanted to mention it.
