### ISSUE TITLE
How to visualize a model architecture using Tensorboard.Graph, PyTorchViz or Netron

### ISSUE THREAD

**Issue by RoyalStorm** [pyannote/pyannote-audio#412]
Hi, first of all thanks for that great work!

**Is your feature request related to a problem? Please describe.**
I'm trying to visualize your model architecture in tools like Tensorboard, Netron or PyTorchViz, but i can't.

**Describe the solution you'd like**
I want a graphical representation of the model architecture.

**Describe alternatives you've considered**
Here are my code examples for different ways:
______________________________________________________________________________________________________
**TensorBoard** (guide: https://pytorch.org/tutorials/intermediate/tensorboard_tutorial.html):
```python
from pathlib import Path

from torch.utils.tensorboard import SummaryWriter

from pyannote.audio.applications.config import load_specs
from pyannote.audio.models import PyanNet

writer = SummaryWriter('arch')

specs = load_specs(Path('/home/rs/.pyannote/hub/models/sad_ami/train/AMI.SpeakerDiarization.MixHeadset.train/specs.yml'))
model = PyanNet(specifications=specs)

writer.add_graph(model)
writer.close()
```

Result:
```
Feature extraction using pretrained models are not available because something went wrong at import: "cannot import name 'load_config' from partially initialized module 'pyannote.audio.applications.config' (most likely due to a circular import) (/home/rs/PycharmProjects/pyannote-audio/pyannote/audio/applications/config.py)".
Traceback (most recent call last):
  File "/home/rs/PycharmProjects/pyannote-audio/tb.py", line 13, in <module>
    writer.add_graph(model)
  File "/home/rs/PycharmProjects/pyannote-audio/venv/lib/python3.8/site-packages/torch/utils/tensorboard/writer.py", line 707, in add_graph
    self._get_file_writer().add_graph(graph(model, input_to_model, verbose))
  File "/home/rs/PycharmProjects/pyannote-audio/venv/lib/python3.8/site-packages/torch/utils/tensorboard/_pytorch_graph.py", line 285, in graph
    trace = torch.jit.trace(model, args)
  File "/home/rs/PycharmProjects/pyannote-audio/venv/lib/python3.8/site-packages/torch/jit/__init__.py", line 873, in trace
    return trace_module(func, {'forward': example_inputs}, None,
  File "/home/rs/PycharmProjects/pyannote-audio/venv/lib/python3.8/site-packages/torch/jit/__init__.py", line 1021, in trace_module
    module = make_module(mod, _module_class, _compilation_unit)
  File "/home/rs/PycharmProjects/pyannote-audio/venv/lib/python3.8/site-packages/torch/jit/__init__.py", line 703, in make_module
    elif torch._jit_internal.module_has_exports(mod):
  File "/home/rs/PycharmProjects/pyannote-audio/venv/lib/python3.8/site-packages/torch/_jit_internal.py", line 438, in module_has_exports
    item = getattr(mod, name)
  File "/home/rs/PycharmProjects/pyannote-audio/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 593, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'PyanNet' object has no attribute 'dimension'
```
______________________________________________________________________________________________________
**Netron** https://github.com/lutzroeder/netron:
This tool get me that image, (for *.pt file):
![Screenshot_20200630_092005_cut-photo ru](https://user-images.githubusercontent.com/36538161/86065476-186e1000-bab3-11ea-8382-86d7f887c4bf.png)
I tried to convert the model to ONXX format (https://github.com/lutzroeder/netron/issues/472), but it did not work.
One of my problems -- I don't know the size of the input and output tensor
Here my code (guide https://michhar.github.io/convert-pytorch-onnx/):
```python
from pathlib import Path

import torch.onnx

from pyannote.audio.applications.config import load_specs
from pyannote.audio.models import PyanNet

specs = load_specs(Path('/home/rs/.pyannote/hub/models/sad_ami/train/AMI.SpeakerDiarization.MixHeadset.train/specs.yml'))
model = PyanNet(specifications=specs)

state_dict = torch.load('/home/rs/.pyannote/hub/models/sad_ami/train/AMI.SpeakerDiarization.MixHeadset.train/weights/0140.pt')

model.load_state_dict(state_dict)

dummy_input = torch.randn(32, 32000, 1)

torch.onnx.export(model, dummy_input, "model.onnx")
torch.save(model.state_dict(), 'model.pth')
```
Result:
```
Feature extraction using pretrained models are not available because something went wrong at import: "cannot import name 'load_config' from partially initialized module 'pyannote.audio.applications.config' (most likely due to a circular import) (/home/rs/PycharmProjects/pyannote-audio/venv/lib/python3.8/site-packages/pyannote/audio/applications/config.py)".
Traceback (most recent call last):
  File "/home/rs/PycharmProjects/pyannote-audio/2onxx.py", line 13, in <module>
    model.load_state_dict(state_dict)
  File "/home/rs/PycharmProjects/pyannote-audio/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 846, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for PyanNet:
	Unexpected key(s) in state_dict: "rnn_.rnn_.weight_ih_l0_reverse", "rnn_.rnn_.weight_hh_l0_reverse", "rnn_.rnn_.bias_ih_l0_reverse", "rnn_.rnn_.bias_hh_l0_reverse", "rnn_.rnn_.weight_ih_l1", "rnn_.rnn_.weight_hh_l1", "rnn_.rnn_.bias_ih_l1", "rnn_.rnn_.bias_hh_l1", "rnn_.rnn_.weight_ih_l1_reverse", "rnn_.rnn_.weight_hh_l1_reverse", "rnn_.rnn_.bias_ih_l1_reverse", "rnn_.rnn_.bias_hh_l1_reverse", "ff_.linear_.1.weight", "ff_.linear_.1.bias". 
	size mismatch for rnn_.rnn_.weight_ih_l0: copying a param with shape torch.Size([512, 60]) from checkpoint, the shape in current model is torch.Size([64, 60]).
	size mismatch for rnn_.rnn_.weight_hh_l0: copying a param with shape torch.Size([512, 128]) from checkpoint, the shape in current model is torch.Size([64, 16]).
	size mismatch for rnn_.rnn_.bias_ih_l0: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for rnn_.rnn_.bias_hh_l0: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for ff_.linear_.0.weight: copying a param with shape torch.Size([128, 256]) from checkpoint, the shape in current model is torch.Size([16, 16]).
	size mismatch for ff_.linear_.0.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([16]).
	size mismatch for linear_.weight: copying a param with shape torch.Size([2, 128]) from checkpoint, the shape in current model is torch.Size([2, 16]).
```
______________________________________________________________________________________________________
**PyTorchViz** (https://github.com/szagoruyko/pytorchviz):
Code:
```python
from pathlib import Path

import torch
from torchviz import make_dot

from pyannote.audio.applications.config import load_specs
from pyannote.audio.models import PyanNet

specs = load_specs(Path('/home/rs/.pyannote/hub/models/sad_ami/train/AMI.SpeakerDiarization.MixHeadset.train/specs.yml'))
model = PyanNet(specifications=specs)

x = torch.randn(32, 1174, 60, dtype=torch.float, requires_grad=False)
make_dot(x, params=dict(model.named_parameters())).render(view=True, format='png')
```
Result:
![Digraph gv](https://user-images.githubusercontent.com/36538161/86068918-d4cbd400-babb-11ea-8832-1fba37eee7d3.png)
______________________________________________________________________________________________________
**pytorch-summary** (https://github.com/sksq96/pytorch-summary)
Code:
```python
from pathlib import Path

from torchsummary import summary

from pyannote.audio.applications.config import load_specs
from pyannote.audio.models import PyanNet

specs = load_specs(Path('/home/rs/.pyannote/hub/models/sad_ami/train/AMI.SpeakerDiarization.MixHeadset.train/specs.yml'))
model = PyanNet(specifications=specs)

summary(model.cuda(), input_size=(32000, 1))
```
Result:
```
Feature extraction using pretrained models are not available because something went wrong at import: "cannot import name 'load_config' from partially initialized module 'pyannote.audio.applications.config' (most likely due to a circular import) (/home/rs/PycharmProjects/pyannote-audio/venv/lib/python3.8/site-packages/pyannote/audio/applications/config.py)".
Traceback (most recent call last):
  File "/home/rs/PycharmProjects/pyannote-audio/tb.py", line 13, in <module>
    summary(model.cuda(), input_size=(32000, 1))
  File "/home/rs/PycharmProjects/pyannote-audio/venv/lib/python3.8/site-packages/torchsummary/torchsummary.py", line 72, in summary
    model(*x)
  File "/home/rs/PycharmProjects/pyannote-audio/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rs/PycharmProjects/pyannote-audio/venv/lib/python3.8/site-packages/pyannote/audio/models/models.py", line 543, in forward
    output = self.rnn_(output)
  File "/home/rs/PycharmProjects/pyannote-audio/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rs/PycharmProjects/pyannote-audio/venv/lib/python3.8/site-packages/pyannote/audio/models/models.py", line 217, in forward
    output, hidden = self.rnn_(features)
  File "/home/rs/PycharmProjects/pyannote-audio/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 552, in __call__
    hook_result = hook(self, input, result)
  File "/home/rs/PycharmProjects/pyannote-audio/venv/lib/python3.8/site-packages/torchsummary/torchsummary.py", line 22, in hook
    summary[m_key]["output_shape"] = [
  File "/home/rs/PycharmProjects/pyannote-audio/venv/lib/python3.8/site-packages/torchsummary/torchsummary.py", line 23, in <listcomp>
    [-1] + list(o.size())[1:] for o in output
AttributeError: 'tuple' object has no attribute 'size'
```
______________________________________________________________________________________________________
I used `print` as an easy way to get at least something, it works, but it’s not at all the result that I need. Code:
```python
specs = load_specs(Path('/home/rs/.pyannote/hub/models/sad_ami/train/AMI.SpeakerDiarization.MixHeadset.train/specs.yml'))
model = PyanNet(specifications=specs)

print(model)
```
Result:
```
PyanNet(
  (sincnet_): SincNet(
    (waveform_normalize_): InstanceNorm1d(1, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
    (conv1d_): ModuleList(
      (0): SincConv1d()
      (1): Conv1d(80, 60, kernel_size=(5,), stride=(1,))
      (2): Conv1d(60, 60, kernel_size=(5,), stride=(1,))
    )
    (max_pool1d_): ModuleList(
      (0): MaxPool1d(kernel_size=3, stride=3, padding=0, dilation=1, ceil_mode=False)
      (1): MaxPool1d(kernel_size=3, stride=3, padding=0, dilation=1, ceil_mode=False)
      (2): MaxPool1d(kernel_size=3, stride=3, padding=0, dilation=1, ceil_mode=False)
    )
    (instance_norm1d_): ModuleList(
      (0): InstanceNorm1d(80, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
      (1): InstanceNorm1d(60, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
      (2): InstanceNorm1d(60, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
    )
    (activation_): LeakyReLU(negative_slope=0.2)
  )
  (rnn_): RNN(
    (rnn_): LSTM(60, 16, batch_first=True)
  )
  (ff_): FF(
    (linear_): ModuleList(
      (0): Linear(in_features=16, out_features=16, bias=True)
    )
  )
  (linear_): Linear(in_features=16, out_features=2, bias=True)
  (activation_): LogSoftmax()
)
```
______________________________________________________________________________________________________

Please, help me visualize the architecture in one of these environments (preferably Tensorboard, Netron or PyTorchViz).

**Additional context**
Links to used projects:
Tensorboard guide: https://pytorch.org/tutorials/intermediate/tensorboard_tutorial.html
PyTorchViz: https://github.com/szagoruyko/pytorchviz
Netron project: https://github.com/lutzroeder/netron
PyTorch weights support: https://github.com/lutzroeder/netron/issues/472
pytorch-summary: https://github.com/sksq96/pytorch-summary

**Comment by alfonsozunigaj** [comment]
The Tensorboard one fails because PyTorch calls `item = getattr(mod, name)` on the `dimension` "attribute"  of the PyanNet class. Checking the [source code for that class](https://github.com/pyannote/pyannote-audio/blob/c68389786673eda66f83b5af01216befac31d781/pyannote/audio/models/models.py#L568), I noticed that `dimension` is a [property](https://www.programiz.com/python-programming/property) and not an attribute, so the method `getattr` won't be able to find it.

I found [this site](http://www.lpsm.paris/pageperso/sangnier/property.html) explaining how to fix it, but apparently we would have to change PyTorch's code, so... any ideas?

**Comment by hbredin** [comment]
I agree that it would be nice to visualize the models.

I am in the process of switching pyannote.audio to `pytorch-lightning` (see [this PR](https://github.com/pyannote/pyannote-audio/pull/407)). 

Adding this issue to the 2.0 milestone so that I remember to have a look at this when times come.
