### ISSUE TITLE
Error with pyannote-audio prodi.gy recipe

### ISSUE THREAD

**Issue by TSSlade** [pyannote/pyannote-audio#433]
**Describe the bug**

With a freshly-created `prodigy` environment supplemented by the `pyannote` github repo and the associated `develop` branch, the error trace below is the consistent result across multiple `.wav` files created from other source files (some `.mp3`, some `.wav`) via the command `ffmpeg -i source-file.mp3 -f s16le -ar 16k -ac 1 destination-file.wav` (adjusted based on the input format), all of which we were able to pass through a `pyannote`-driven SAD inference process when working outside of Prodigy. (In those cases, the SAD inference was conducted using `pyannote-audio` and a multi-label classification task was completed with Marvin Lavechin's `https://github.com/MarvinLvn/voice-type-classifier`.)

Any guidance, please?  
```bash
(prodigy) → ls -lah
total 110288
drwxr-xr-x@  5 tsslade  staff   160B Aug 25 21:00 .
drwxr-xr-x@ 26 tsslade  staff   832B Aug 25 20:59 ..
-rw-r--r--@  1 tsslade  staff    47M Jun 25 19:14 1593136205820.wav

(prodigy) → prodigy pyannote.sad.manual speech_activity
(prodigy) → prodigy pyannote.sad.manual speech_activity .
Using cache found in /Users/tsslade/.cache/torch/hub/pyannote_pyannote-audio_master
Using cache found in /Users/tsslade/.cache/torch/hub/pyannote_pyannote-audio_master
/Users/tsslade/miniconda3/envs/prodigy/lib/python3.8/site-packages/pyannote/audio/embedding/approaches/arcface_loss.py:170: FutureWarning: The 's' parameter is deprecated in favor of 'scale', and will be removed in a future release
  warnings.warn(msg, FutureWarning)
Traceback (most recent call last):
  File "/Users/tsslade/miniconda3/envs/prodigy/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/tsslade/miniconda3/envs/prodigy/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/tsslade/miniconda3/envs/prodigy/lib/python3.8/site-packages/prodigy/__main__.py", line 60, in <module>
    controller = recipe(*args, use_plac=True)
  File "cython_src/prodigy/core.pyx", line 318, in prodigy.core.recipe.recipe_decorator.recipe_proxy
  File "cython_src/prodigy/core.pyx", line 138, in prodigy.core.Controller.__init__
  File "cython_src/prodigy/components/feeds.pyx", line 56, in prodigy.components.feeds.SharedFeed.__init__
  File "cython_src/prodigy/components/feeds.pyx", line 155, in prodigy.components.feeds.SharedFeed.validate_stream
  File "/Users/tsslade/miniconda3/envs/prodigy/lib/python3.8/site-packages/toolz/itertoolz.py", line 376, in first
    return next(iter(seq))
  File "/Users/tsslade/miniconda3/envs/prodigy/lib/python3.8/site-packages/pyannote/audio/interactive/recipes/sad.py", line 99, in sad_manual_stream
    speech: Annotation = pipeline.compute_speech(file).to_annotation(
  File "/Users/tsslade/miniconda3/envs/prodigy/lib/python3.8/site-packages/pyannote/audio/interactive/pipeline.py", line 170, in compute_speech
    sad_scores = self.sad(current_file)
  File "/Users/tsslade/miniconda3/envs/prodigy/lib/python3.8/site-packages/pyannote/audio/features/wrapper.py", line 280, in __call__
    return self.scorer_(current_file)
  File "/Users/tsslade/miniconda3/envs/prodigy/lib/python3.8/site-packages/pyannote/audio/features/base.py", line 149, in __call__
    y, sample_rate = self.raw_audio_(current_file, return_sr=True)
  File "/Users/tsslade/miniconda3/envs/prodigy/lib/python3.8/site-packages/pyannote/audio/features/utils.py", line 237, in __call__
    y = self.get_features(y, sample_rate)
  File "/Users/tsslade/miniconda3/envs/prodigy/lib/python3.8/site-packages/pyannote/audio/features/utils.py", line 173, in get_features
    y = librosa.core.resample(y.T, sample_rate, self.sample_rate).T
  File "/Users/tsslade/miniconda3/envs/prodigy/lib/python3.8/site-packages/librosa/core/audio.py", line 548, in resample
    util.valid_audio(y, mono=False)
  File "/Users/tsslade/miniconda3/envs/prodigy/lib/python3.8/site-packages/librosa/util/utils.py", line 305, in valid_audio
    raise ParameterError(
librosa.util.exceptions.ParameterError: Mono data must have shape (samples,). Received shape=(1, 24682736)
```

**To Reproduce**

```bash
$  prodigy pyannote.sad.manual speech_activity .
```

**Content of `config.yml`**

N/A - `config.yml` not explicitly provided beyond the default in the cloned repo

**pyannote environment**

```bash
(prodigy) → conda list | grep pyannote
pyannote-audio            2.0a1+60.gc683897          pypi_0    pypi
pyannote-core             4.1                      pypi_0    pypi
pyannote-database         4.0.1                    pypi_0    pypi
pyannote-metrics          3.0.1                    pypi_0    pypi
pyannote-pipeline         1.5.2                    pypi_0    pypi
```

**Additional context**
Overall conda env:
```bash
(prodigy) → conda list
# packages in environment at /Users/tsslade/miniconda3/envs/prodigy:
#
# Name                    Version                   Build  Channel
absl-py                   0.10.0                   pypi_0    pypi
aiofiles                  0.5.0                    pypi_0    pypi
alembic                   1.4.2                    pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
appnope                   0.1.0                 py38_1001
argon2-cffi               20.1.0           py38haf1e3a3_1
attrs                     20.1.0                     py_0
audioread                 2.1.8                    pypi_0    pypi
backcall                  0.2.0                      py_0
blas                      1.0                         mkl
bleach                    3.1.5                      py_0
blis                      0.4.1                    pypi_0    pypi
brotlipy                  0.7.0           py38h64e0658_1000    conda-forge
bzip2                     1.0.8                haf1e3a3_3    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
cachetools                4.1.1                    pypi_0    pypi
catalogue                 1.0.0                    pypi_0    pypi
certifi                   2020.6.20        py38h32f6830_0    conda-forge
cffi                      1.14.2           py38hed5b41f_0
chardet                   3.0.4           py38h32f6830_1006    conda-forge
click                     7.1.2                    pypi_0    pypi
cliff                     3.4.0                    pypi_0    pypi
cmaes                     0.6.0                    pypi_0    pypi
cmd2                      1.3.5                    pypi_0    pypi
colorama                  0.4.3                    pypi_0    pypi
colorlog                  4.2.1                    pypi_0    pypi
cryptography              3.0              py38h52adbb4_0    conda-forge
cycler                    0.10.0                   pypi_0    pypi
cymem                     2.0.3                    pypi_0    pypi
dbus                      1.13.16              h18a8e69_0
decorator                 4.4.2                      py_0
defusedxml                0.6.0                      py_0
en-core-web-sm            2.3.1                    pypi_0    pypi
entrypoints               0.3                      py38_0
expat                     2.2.9                hb1e8313_2
fastapi                   0.44.1                   pypi_0    pypi
ffmpeg                    4.2.3                hd0c0d6a_0    conda-forge
filelock                  3.0.12                   pypi_0    pypi
freetype                  2.10.2               h8da9a1a_0    conda-forge
gettext                   0.19.8.1             hb0f4f8b_2
glib                      2.65.0               hc5f4afa_0
gmp                       6.2.0                h4a8c4bd_2    conda-forge
gnutls                    3.6.13               hc269f14_0    conda-forge
google-auth               1.20.1                   pypi_0    pypi
google-auth-oauthlib      0.4.1                    pypi_0    pypi
grpcio                    1.31.0                   pypi_0    pypi
h11                       0.9.0                    pypi_0    pypi
httptools                 0.1.1                    pypi_0    pypi
icu                       58.2                 h0a44026_3
idna                      2.10               pyh9f0ad1d_0    conda-forge
importlib-metadata        1.7.0                    py38_0
importlib_metadata        1.7.0                         0
intel-openmp              2019.4                      233
ipykernel                 5.3.4            py38h5ca1d4c_0
ipython                   7.17.0           py38h5ca1d4c_0
ipython_genutils          0.2.0                    py38_0
ipywidgets                7.5.1                      py_0
jedi                      0.17.2                   py38_0
jinja2                    2.11.2                     py_0
joblib                    0.16.0                   pypi_0    pypi
jpeg                      9b                   he5867d9_2
json5                     0.9.4              pyh9f0ad1d_0    conda-forge
jsonschema                3.2.0                    py38_1
jupyter                   1.0.0                    py38_7
jupyter_client            6.1.6                      py_0
jupyter_console           6.1.0                      py_0
jupyter_core              4.6.3                    py38_0
jupyterlab                2.2.6                      py_0    conda-forge
jupyterlab_server         1.2.0                      py_0    conda-forge
kiwisolver                1.2.0                    pypi_0    pypi
lame                      3.100             h1de35cc_1001    conda-forge
libcxx                    10.0.0                        1
libedit                   3.1.20191231         h1de35cc_1
libffi                    3.3                  hb1e8313_2
libiconv                  1.16                 h1de35cc_0
libpng                    1.6.37               ha441bb4_0
librosa                   0.8.0                    pypi_0    pypi
libsodium                 1.0.18               h1de35cc_0
llvmlite                  0.31.0                   pypi_0    pypi
mako                      1.1.3                    pypi_0    pypi
markdown                  3.2.2                    pypi_0    pypi
markupsafe                1.1.1            py38h1de35cc_1
matplotlib                3.3.1                    pypi_0    pypi
mistune                   0.8.4           py38h1de35cc_1001
mkl                       2019.4                      233
mkl-service               2.3.0            py38hfbe908c_0
mkl_fft                   1.1.0            py38hc64f4ea_0
mkl_random                1.1.1            py38h959d312_0
mpmath                    1.1.0                    pypi_0    pypi
murmurhash                1.0.2                    pypi_0    pypi
nbconvert                 5.6.1                    py38_1
nbformat                  5.0.7                      py_0
ncurses                   6.2                  h0a44026_1
nettle                    3.4.1             h3efe00b_1002    conda-forge
ninja                     1.10.0           py38h879752b_0
notebook                  6.1.1                    py38_0
numba                     0.48.0                   pypi_0    pypi
numpy                     1.19.1           py38h3b9f5b6_0
numpy-base                1.19.1           py38hcfb5961_0
oauthlib                  3.1.0                    pypi_0    pypi
openh264                  2.1.1                hd174df1_0    conda-forge
openssl                   1.1.1g               haf1e3a3_1    conda-forge
optuna                    2.0.0                    pypi_0    pypi
packaging                 20.4                       py_0
pandas                    1.1.1                    pypi_0    pypi
pandoc                    2.10.1                        0
pandocfilters             1.4.2                    py38_1
parso                     0.7.0                      py_0
pbr                       5.4.5                    pypi_0    pypi
pcre                      8.44                 hb1e8313_0
peewee                    3.13.3                   pypi_0    pypi
pescador                  2.1.0                    pypi_0    pypi
pexpect                   4.8.0                    py38_1
pickleshare               0.7.5                 py38_1001
pillow                    7.2.0                    pypi_0    pypi
pip                       20.2.2                   py38_0
plac                      1.1.3                    pypi_0    pypi
pooch                     1.1.1                    pypi_0    pypi
preshed                   3.0.2                    pypi_0    pypi
prettytable               0.7.2                    pypi_0    pypi
prodigy                   1.10.3                   pypi_0    pypi
prometheus_client         0.8.0                      py_0
prompt-toolkit            3.0.5                      py_0
prompt_toolkit            3.0.5                         0
protobuf                  3.13.0                   pypi_0    pypi
ptyprocess                0.6.0                    py38_0
pyannote-audio            2.0a1+60.gc683897          pypi_0    pypi
pyannote-core             4.1                      pypi_0    pypi
pyannote-database         4.0.1                    pypi_0    pypi
pyannote-metrics          3.0.1                    pypi_0    pypi
pyannote-pipeline         1.5.2                    pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.20                       py_2
pydantic                  1.6.1                    pypi_0    pypi
pygments                  2.6.1                      py_0
pyjwt                     1.7.1                    pypi_0    pypi
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.7                      py_0
pyperclip                 1.8.0                    pypi_0    pypi
pyqt                      5.9.2            py38h655552a_2
pyrsistent                0.16.0           py38h1de35cc_0
pysocks                   1.7.1            py38h32f6830_1    conda-forge
python                    3.8.5                h26836e1_0
python-dateutil           2.8.1                      py_0
python-editor             1.0.4                    pypi_0    pypi
python_abi                3.8                      1_cp38    conda-forge
pytorch                   1.6.0                   py3.8_0    pytorch
pytz                      2020.1                   pypi_0    pypi
pyyaml                    5.3.1                    pypi_0    pypi
pyzmq                     19.0.1           py38hb1e8313_1
qt                        5.9.7                h468cd18_1
qtconsole                 4.7.6                      py_0
qtpy                      1.9.0                      py_0
readline                  8.0                  h1de35cc_0
requests                  2.24.0             pyh9f0ad1d_0    conda-forge
requests-oauthlib         1.3.0                    pypi_0    pypi
resampy                   0.2.2                    pypi_0    pypi
rsa                       4.6                      pypi_0    pypi
scikit-learn              0.23.2                   pypi_0    pypi
scipy                     1.5.2                    pypi_0    pypi
send2trash                1.5.0                    py38_0
setuptools                49.6.0                   py38_0
shellingham               1.3.2                    pypi_0    pypi
simplejson                3.17.2                   pypi_0    pypi
sip                       4.19.8           py38h0a44026_0
six                       1.15.0                     py_0
sortedcollections         1.2.1                    pypi_0    pypi
sortedcontainers          2.2.2                    pypi_0    pypi
soundfile                 0.10.3.post1             pypi_0    pypi
spacy                     2.3.2                    pypi_0    pypi
sqlalchemy                1.3.19                   pypi_0    pypi
sqlite                    3.33.0               hffcf06c_0
srsly                     1.0.2                    pypi_0    pypi
starlette                 0.12.9                   pypi_0    pypi
stevedore                 3.2.0                    pypi_0    pypi
sympy                     1.6.2                    pypi_0    pypi
tabulate                  0.8.7                    pypi_0    pypi
tensorboard               2.3.0                    pypi_0    pypi
tensorboard-plugin-wit    1.7.0                    pypi_0    pypi
terminado                 0.8.3                    py38_0
testpath                  0.4.4                      py_0
thinc                     7.4.1                    pypi_0    pypi
threadpoolctl             2.1.0                    pypi_0    pypi
tk                        8.6.10               hb0a8c7a_0
toolz                     0.10.0                   pypi_0    pypi
tornado                   6.0.4            py38h1de35cc_1
tqdm                      4.48.2                   pypi_0    pypi
traitlets                 4.3.3                    py38_0
typer                     0.3.2                    pypi_0    pypi
typing-extensions         3.7.4.3                  pypi_0    pypi
urllib3                   1.25.10                    py_0    conda-forge
uvicorn                   0.11.8                   pypi_0    pypi
uvloop                    0.14.0                   pypi_0    pypi
wasabi                    0.7.1                    pypi_0    pypi
wcwidth                   0.2.5                      py_0
webencodings              0.5.1                    py38_1
websockets                8.1                      pypi_0    pypi
werkzeug                  1.0.1                    pypi_0    pypi
wheel                     0.35.1                     py_0
widgetsnbextension        3.5.1                    py38_0
x264                      1!152.20180806       h1de35cc_0    conda-forge
xz                        5.2.5                h1de35cc_0
zeromq                    4.3.2                hb1e8313_2
zipp                      3.1.0                      py_0
zlib                      1.2.11               h1de35cc_3
```

**Comment by hbredin** [comment]
Looks like it is related to [this issue](#422). 

Can you please try with librosa 0.7.2 and let me know if that solves the issue?

**Comment by hbredin** [comment]
I confirm this is due to breaking changes in librosa 0.8: 
https://github.com/librosa/librosa/commit/f2079c1300c63d515f7fbad1f65208aa57dc5265

**Comment by TSSlade** [comment]
And I confirm the downgrade to `librosa=0.7.2` resolved the issue. Thank you for the speedy response, @hbredin !
