### ISSUE TITLE
TypeError: get_protocol() got an unexpected keyword argument 'progress'

### ISSUE THREAD

**Issue by bml1g12** [pyannote/pyannote-audio#470]
**Describe the bug**
I can run validation on AMI as per tutorial, but when I run on my own fine-tuned training folder and protocol I get TypeError: get_protocol() got an unexpected keyword argument 'progress'

Seems same issue as here:
https://github.com/pyannote/pyannote-audio/issues/455

**To Reproduce**

 ```
pyannote-audio emb validate --pretrained=emb_voxceleb --subset=train --to=20 --parallel=8 /media/ben/datadrive/Software/pyannote-audio/data/ami/tmp2/train/mydataset.SpeakerVerification.MixHeadset.train/ mydataset.SpeakerVerification.MixHeadset

0iteration [00:00, ?iteration/s]Traceback (most recent call last):
  File "/home/ben/anaconda3/envs/pyannote/bin/pyannote-audio", line 8, in <module>
    sys.exit(main())
  File "/home/ben/anaconda3/envs/pyannote/lib/python3.7/site-packages/pyannote/audio/applications/pyannote_audio.py", line 415, in main
    app.validate(protocol, **params)
  File "/home/ben/anaconda3/envs/pyannote/lib/python3.7/site-packages/pyannote/audio/applications/base.py", line 327, in validate
    **kwargs)
  File "/home/ben/anaconda3/envs/pyannote/lib/python3.7/site-packages/pyannote/audio/applications/speaker_embedding.py", line 94, in validate_epoch
    epoch, validation_data, protocol=protocol, **kwargs)
  File "/home/ben/anaconda3/envs/pyannote/lib/python3.7/site-packages/pyannote/audio/applications/speaker_embedding.py", line 147, in _validate_epoch_verification
    preprocessors=self.preprocessors_)
TypeError: get_protocol() got an unexpected keyword argument 'progress'
0iteration [00:01, ?iteration/s]
```
Using: 
```
╰─❯ pip freeze | grep pyannote
pyannote.audio==2.0a1
pyannote.core==4.1
pyannote.database==4.0.2
pyannote.db.voxceleb==1.0.2
pyannote.metrics==3.0.1
pyannote.pipeline==1.5.2
```
And also tried using the latest source of pyannote-audio:
```
╰─❯ pip freeze | grep pyannote
-e git+https://github.com/pyannote/pyannote-audio.git@b8d623596e1c01a1049a0ba2eb5be2f6bf8ba1a0#egg=pyannote.audio
pyannote.core==4.1
pyannote.database==4.0.2
pyannote.db.voxceleb==1.0.2
pyannote.metrics==3.0.1
pyannote.pipeline==1.5.2
```

But then get the following error instead:

```
Traceback (most recent call last):
  File "/home/ben/anaconda3/envs/pyannote/bin/pyannote-audio", line 33, in <module>
    sys.exit(load_entry_point('pyannote.audio', 'console_scripts', 'pyannote-audio')())
  File "/media/ben/datadrive/Software/pyannote-audio/pyannote/audio/applications/pyannote_audio.py", line 422, in main
    app.validate(protocol, **params)
  File "/media/ben/datadrive/Software/pyannote-audio/pyannote/audio/applications/base.py", line 362, in validate
    **kwargs,
  File "/media/ben/datadrive/Software/pyannote-audio/pyannote/audio/applications/speaker_embedding.py", line 93, in validate_epoch
    epoch, validation_data, protocol=protocol, **kwargs
  File "/media/ben/datadrive/Software/pyannote-audio/pyannote/audio/applications/speaker_embedding.py", line 171, in _validate_epoch_verification
    emb1 = self.get_embedding(file1, pretrained)
  File "/media/ben/datadrive/Software/pyannote-audio/pyannote/audio/applications/speaker_embedding.py", line 126, in get_embedding
    return np.mean(np.vstack(emb), axis=0, keepdims=True)
  File "<__array_function__ internals>", line 6, in vstack
  File "/home/ben/anaconda3/envs/pyannote/lib/python3.7/site-packages/numpy/core/shape_base.py", line 283, in vstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate
0iteration [00:08, ?iteration/s]
```

**Content of `config.yml`**

```
architecture:
  name: pyannote.audio.models.SincTDNN
  params:
    embedding:
      batch_normalize: false
      unit_normalize: false
    sincnet:
      instance_normalize: true
      stride:
      - 5
      - 1
      - 1
      waveform_normalize: true
    tdnn:
      embedding_dim: 512
feature_extraction:
  name: pyannote.audio.features.RawAudio
  params:
    sample_rate: 16000
scheduler:
  name: ConstantScheduler
  params:
    learning_rate: 0.01
task:
  name: AdditiveAngularMarginLoss
  params:
    duration: 4.0
    label_min_duration: 30
    margin: 0.05
    min_duration: 1.0
    per_fold: 128
    per_label: 1
    per_turn: 1
    s: 10
```

**Comment by bml1g12** [comment]
I discovered the reason I was getting this error was because my .trials file, defining a speaker verification protocol was wrongly formatted. 

Fixing that issue gives me:

```
pyannote-audio emb validate --pretrained=emb_voxceleb --subset=development --to=1 --parallel=8 /media/ben/datadrive/Software/pyannote-audio/data/ami/voxceleb_finetuneexp1/train/ZALODATASET.SpeakerVerification.MixHeadset.train ZALODATASET.SpeakerVerification.MixHeadset
Traceback (most recent call last):
  File "/home/ben/anaconda3/envs/pyannote/bin/pyannote-audio", line 33, in <module>
    sys.exit(load_entry_point('pyannote.audio', 'console_scripts', 'pyannote-audio')())
  File "/media/ben/datadrive/Software/pyannote-audio/pyannote/audio/applications/pyannote_audio.py", line 422, in main
    app.validate(protocol, **params)
  File "/media/ben/datadrive/Software/pyannote-audio/pyannote/audio/applications/base.py", line 362, in validate
    **kwargs,
  File "/media/ben/datadrive/Software/pyannote-audio/pyannote/audio/applications/speaker_embedding.py", line 93, in validate_epoch
    epoch, validation_data, protocol=protocol, **kwargs
  File "/media/ben/datadrive/Software/pyannote-audio/pyannote/audio/applications/speaker_embedding.py", line 189, in _validate_epoch_verification
    _, _, _, eer = det_curve(np.array(y_true), np.array(y_pred), distances=True)
  File "/home/ben/anaconda3/envs/pyannote/lib/python3.7/site-packages/pyannote/metrics/binary_classification.py", line 67, in det_curve
    y_true, scores, pos_label=True)
  File "/home/ben/anaconda3/envs/pyannote/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/ben/anaconda3/envs/pyannote/lib/python3.7/site-packages/sklearn/metrics/_ranking.py", line 776, in roc_curve
    y_true, y_score, pos_label=pos_label, sample_weight=sample_weight)
  File "/home/ben/anaconda3/envs/pyannote/lib/python3.7/site-packages/sklearn/metrics/_ranking.py", line 545, in _binary_clf_curve
    assert_all_finite(y_score)
  File "/home/ben/anaconda3/envs/pyannote/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/ben/anaconda3/envs/pyannote/lib/python3.7/site-packages/sklearn/utils/validation.py", line 117, in assert_all_finite
    _assert_all_finite(X.data if sp.issparse(X) else X, allow_nan)
  File "/home/ben/anaconda3/envs/pyannote/lib/python3.7/site-packages/sklearn/utils/validation.py", line 99, in _assert_all_finite
    msg_dtype if msg_dtype is not None else X.dtype)
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
0iteration [01:59, ?iteration/s]
```

But I'll have a stab at debugging this; and if I can't figure it out raise it as separate bug ticket.
