### ISSUE TITLE
Default cropping mode in speaker_embedding.py erases a clip

### ISSUE THREAD

**Issue by bml1g12** [pyannote/pyannote-audio#471]
**Describe the bug**
Running 
```
pyannote-audio emb validate  --subset=development --to=1 --parallel=8 /media/ben/datadrive/Software/pyannote-audio/data/ami/voxceleb_finetuneexp1/train/myexpt.SpeakerVerification.MixHeadset.train myexpt.SpeakerVerification.BenProtocol
```
Led to 
```
Traceback (most recent call last):
  File "/home/ben/anaconda3/envs/pyannote/bin/pyannote-audio", line 33, in <module>
    sys.exit(load_entry_point('pyannote.audio', 'console_scripts', 'pyannote-audio')())
  File "/media/ben/datadrive/Software/pyannote-audio/pyannote/audio/applications/pyannote_audio.py", line 422, in main
    app.validate(protocol, **params)
  File "/media/ben/datadrive/Software/pyannote-audio/pyannote/audio/applications/base.py", line 362, in validate
    **kwargs,
  File "/media/ben/datadrive/Software/pyannote-audio/pyannote/audio/applications/speaker_embedding.py", line 93, in validate_epoch
    epoch, validation_data, protocol=protocol, **kwargs
  File "/media/ben/datadrive/Software/pyannote-audio/pyannote/audio/applications/speaker_embedding.py", line 195, in _validate_epoch_verification
    _, _, _, eer = det_curve(np.array(y_true), np.array(y_pred), distances=True)
  File "/home/ben/anaconda3/envs/pyannote/lib/python3.7/site-packages/pyannote/metrics/binary_classification.py", line 67, in det_curve
    y_true, scores, pos_label=True)
  File "/home/ben/anaconda3/envs/pyannote/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/ben/anaconda3/envs/pyannote/lib/python3.7/site-packages/sklearn/metrics/_ranking.py", line 776, in roc_curve
    y_true, y_score, pos_label=pos_label, sample_weight=sample_weight)
  File "/home/ben/anaconda3/envs/pyannote/lib/python3.7/site-packages/sklearn/metrics/_ranking.py", line 545, in _binary_clf_curve
    assert_all_finite(y_score)
  File "/home/ben/anaconda3/envs/pyannote/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/ben/anaconda3/envs/pyannote/lib/python3.7/site-packages/sklearn/utils/validation.py", line 117, in assert_all_finite
    _assert_all_finite(X.data if sp.issparse(X) else X, allow_nan)
  File "/home/ben/anaconda3/envs/pyannote/lib/python3.7/site-packages/sklearn/utils/validation.py", line 99, in _assert_all_finite
    msg_dtype if msg_dtype is not None else X.dtype)
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
0iteration [00:03, ?iteration/s]
```
Which I found is caused by Line 124 `emb.append(pretrained.crop(f, segment, mode="center"))` of speaker_embedding.py

Specifically I can reproduce it with minimal code:

```
emb = torch.hub.load('pyannote/pyannote-audio', 'emb_voxceleb')
file = 71-2.wav
emb(file).crop(Segment(0, 0.495646), mode="center")
``` 
Attached:  [71-2.zip](https://github.com/pyannote/pyannote-audio/files/5504536/71-2.zip)

And it seems using "loose" mode works around this. Is there any problem anticipated if i just change the source code to use "loose" here? The clip duration according to ffprobe is 0.5 so I do not quite understand the problem here. 

Thanks for any help 

```
-e git+https://github.com/pyannote/pyannote-audio.git@b8d623596e1c01a1049a0ba2eb5be2f6bf8ba1a0#egg=pyannote.audio
pyannote.core==4.1
pyannote.database==4.0.2
pyannote.db.voxceleb==1.0.2
pyannote.metrics==3.0.1
pyannote.pipeline==1.5.2
```

**Comment by hbredin** [comment]
I'd happily merge a PR that would do something like this (instead of switching to "loose" completely):

https://github.com/pyannote/pyannote-audio/blob/ffe9b0b5d3b1f505acbcdfb47995f197aa10ce8b/pyannote/audio/pipeline/speech_turn_assignment.py#L101-L106

Note that I'd avoid using `"strict"` at all because, in my experience, `"center"` always led to better results than `"strict"`.
And `"center"` also leads to better results than `"loose"` but, as you experienced, sometimes, `"center"` does not return any embedding.

Or...

One could update the behavior of `crop` with `center` mode to always return at least one embedding.

**Comment by bml1g12** [comment]
Great I'll try it out locally as you've suggested; and make a PR later if I have no problems.
