### ISSUE TITLE
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

### ISSUE THREAD

**Issue by saumyaborwankar** [pyannote/pyannote-audio#518]
(py3) saumya@INSISCPLT-5158:~/pyannote-audio$ pip3 install .
Processing /home/saumya/pyannote-audio
    ERROR: Command errored out with exit status 1:
     command: /home/saumya/anaconda3/envs/py3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-_ggk3f60/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-_ggk3f60/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-iw68wduu
         cwd: /tmp/pip-req-build-_ggk3f60/
    Complete output (38 lines):
    WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f17af004510>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/pyscaffold/
    WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f17af0225d0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/pyscaffold/
    WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f17af022890>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/pyscaffold/
    WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f17af022590>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/pyscaffold/
    WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f17af022950>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/pyscaffold/
    ERROR: Could not find a version that satisfies the requirement pyscaffold<3.3a0,>=3.2a0 (from versions: none)
    ERROR: No matching distribution found for pyscaffold<3.3a0,>=3.2a0
    Traceback (most recent call last):
      File "/home/saumya/anaconda3/envs/py3/lib/python3.7/site-packages/setuptools/installer.py", line 126, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/home/saumya/anaconda3/envs/py3/lib/python3.7/subprocess.py", line 363, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/home/saumya/anaconda3/envs/py3/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpe2q5jpp4', '--quiet', 'pyscaffold<3.3a0,>=3.2a0']' returned non-zero exit status 1.

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-_ggk3f60/setup.py", line 60, in <module>
        "Topic :: Scientific/Engineering",
      File "/home/saumya/anaconda3/envs/py3/lib/python3.7/site-packages/setuptools/__init__.py", line 152, in setup
        _install_setup_requires(attrs)
      File "/home/saumya/anaconda3/envs/py3/lib/python3.7/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/home/saumya/anaconda3/envs/py3/lib/python3.7/site-packages/setuptools/dist.py", line 676, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/saumya/anaconda3/envs/py3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 766, in resolve
        replace_conflicting=replace_conflicting
      File "/home/saumya/anaconda3/envs/py3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1049, in best_match
        return self.obtain(req, installer)
      File "/home/saumya/anaconda3/envs/py3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1061, in obtain
        return installer(requirement)
      File "/home/saumya/anaconda3/envs/py3/lib/python3.7/site-packages/setuptools/dist.py", line 732, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/home/saumya/anaconda3/envs/py3/lib/python3.7/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['/home/saumya/anaconda3/envs/py3/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpe2q5jpp4', '--quiet', 'pyscaffold<3.3a0,>=3.2a0']' returned non-zero exit status 1.
    -- Building version 0.0.1
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by ZakariaaAit** [comment]
I've the same problem please can anyone give us some help
