### ISSUE TITLE
pyannote-audio sad apply gives EOFError

### ISSUE THREAD

**Issue by bitcarousel** [pyannote/pyannote-audio#562]
I created a python virtual environment and installed pyannote.audio by:

pip install pyannote.audio==1.1.1

However every pyannote-audio command like: 

pyannote-audio --version OR
pyannote-audio --help
Throw Error like this:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/Caskroom/miniconda/base/bin/pyannote-audio", line 5, in <module>
    from pyannote.audio.applications.pyannote_audio import main
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/pyannote/audio/applications/pyannote_audio.py", line 270, in <module>
    from .speech_detection import SpeechActivityDetection
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/pyannote/audio/applications/speech_detection.py", line 35, in <module>
    from pyannote.audio.pipeline import (
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/pyannote/audio/pipeline/__init__.py", line 33, in <module>
    from .speech_activity_detection import SpeechActivityDetection
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/pyannote/audio/pipeline/speech_activity_detection.py", line 44, in <module>
    from pyannote.metrics.detection import DetectionErrorRate
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/pyannote/metrics/__init__.py", line 40, in <module>
    manager_ = Manager()
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/multiprocessing/managers.py", line 579, in start
    self._process.start()
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/bin/pyannote-audio", line 5, in <module>
    from pyannote.audio.applications.pyannote_audio import main
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/pyannote/audio/applications/pyannote_audio.py", line 270, in <module>
    from .speech_detection import SpeechActivityDetection
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/pyannote/audio/applications/speech_detection.py", line 35, in <module>
    from pyannote.audio.pipeline import (
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/pyannote/audio/pipeline/__init__.py", line 33, in <module>
    from .speech_activity_detection import SpeechActivityDetection
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/pyannote/audio/pipeline/speech_activity_detection.py", line 44, in <module>
    from pyannote.metrics.detection import DetectionErrorRate
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/pyannote/metrics/__init__.py", line 40, in <module>
    manager_ = Manager()
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/multiprocessing/managers.py", line 583, in start
    self._address = reader.recv()
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError

**BTW: I also tried on a fresh AWS Instance which also throw error on ever pyannote-audio command.** 

[root@ip-10-255-255-123 ec2-user]# pyannote-audio --version
Traceback (most recent call last):
  File "/usr/local/bin/pyannote-audio", line 5, in <module>
    from pyannote.audio.applications.pyannote_audio import main
  File "/usr/local/lib/python3.6/site-packages/pyannote/audio/applications/pyannote_audio.py", line 269, in <module>
    from .base import apply_pretrained
  File "/usr/local/lib/python3.6/site-packages/pyannote/audio/applications/base.py", line 52, in <module>
    from pyannote.audio.features.utils import get_audio_duration
  File "/usr/local/lib/python3.6/site-packages/pyannote/audio/features/__init__.py", line 33, in <module>
    from .base import FeatureExtraction
  File "/usr/local/lib/python3.6/site-packages/pyannote/audio/features/base.py", line 32, in <module>
    from .utils import RawAudio
  File "/usr/local/lib/python3.6/site-packages/pyannote/audio/features/utils.py", line 32, in <module>
    import librosa
  File "/usr/local/lib/python3.6/site-packages/librosa/__init__.py", line 211, in <module>
    from . import core
  File "/usr/local/lib/python3.6/site-packages/librosa/core/__init__.py", line 6, in <module>
    from .audio import *  # pylint: disable=wildcard-import
  File "/usr/local/lib/python3.6/site-packages/librosa/core/audio.py", line 8, in <module>
    import soundfile as sf
  File "/usr/local/lib/python3.6/site-packages/soundfile.py", line 142, in <module>
    raise OSError('sndfile library not found')
OSError: sndfile library not found

**Comment by bitcarousel** [comment]
Had to install libsnd:
Linux:
yum install libsndfile

**Comment by bitcarousel** [comment]
Honestly not on a MAC. I installed pyannote-audio on a RedHat in AWS where it was working fine.

**Comment by DmitryBabichev** [comment]
I have the same problem on a MAC, it makes it impossible to use pyannote, do you know hot to fix it?

**Comment by ryanfb** [comment]
For anyone encountering this now, here's how I got around it on macOS 12.4 with libsndfile installed from Homebrew on an M1 Mac:
```
CFLAGS="-I/opt/homebrew/include" LDFLAGS="-L/opt/homebrew/lib" pip3 install sndfile
cd /usr/local/lib && sudo ln -s /opt/homebrew/lib/libsndfile.dylib
```
