### ISSUE TITLE
Unable to finetune scd models

### ISSUE THREAD

**Issue by amruthanadarajan** [pyannote/pyannote-audio#667]
**Describe the bug**
When I try to fine tune scd model, I get the following error:
TypeError: __init__() got an unexpected keyword argument 'collar'
Traceback (most recent call last):
  File "/home/amrutha/anaconda2/envs/pyannot/bin/pyannote-audio", line 8, in <module>
    sys.exit(main())
  File "/home/amrutha/anaconda2/envs/pyannot/lib/python3.7/site-packages/pyannote/audio/applications/pyannote_audio.py", line 364, in main
    root_dir, training=True, pretrained_config_yml=pretrained_config_yml
  File "/home/amrutha/anaconda2/envs/pyannot/lib/python3.7/site-packages/pyannote/audio/applications/base.py", line 163, in __init__
    pretrained_config_yml=pretrained_config_yml,
  File "/home/amrutha/anaconda2/envs/pyannot/lib/python3.7/site-packages/pyannote/audio/applications/config.py", line 222, in load_config
    cfg["task"] = TaskClass(**cfg["task"].get("params", {}))
TypeError: __init__() got an unexpected keyword argument 'collar'

**To Reproduce**
```bash
$ pyannote-audio scd train --pretrained=scd --subset=train --to=5 --parallel=4 ${EXP_DIR} ICSI.SpeakerDiari
zation.ClosecommontalkProtocol
```

**Content of `config.yml`**

Because pretrained models come with their own configuration file, no configuration file is needed to fine-tune a model.

**pyannote environment**

```bash
$ pip freeze | grep pyannote
pyannote.audio==1.1.2
pyannote.core==4.1
pyannote.database==4.1
pyannote.metrics==3.0.1
pyannote.pipeline==1.5.2
```

**Additional context**
the fine tuning worked for overlap models

**Comment by amruthanadarajan** [comment]
I had to do "rm ${EXP_DIR}/config.yml" and that seemed to resolve the issue
