### ISSUE TITLE
Error in "pyannote-speaker-embedding apply"

### ISSUE THREAD

**Issue by nikopartanen** [pyannote/pyannote-audio#68]
I'm finishing going through this [tutorial](https://github.com/pyannote/pyannote-audio/tree/master/tutorials/speaker-embedding), and everything has gone very well otherwise, but in the last extraction part I get following error.

It is very possible that I need to do some bigger changes to my setup or do some of the earlier tutorials again, as there seems to have been quite many changes. Anyway, maybe I'm missing something obvious here so I open an issue first. I updated pyannote-audio and others to the newest versions.

```
pyannote-speaker-embedding apply --step=2.0 $VALIDATION_DIR/development.eer.txt ikdp.SpeakerDiarization.MyFirstProtocol $OUTPUT_DIR

Using Theano backend.
/Users/niko/anaconda3/envs/pyannote/lib/python3.5/site-packages/keras/models.py:251: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
Development set: 0it [00:00, ?it/s]
Development set: 0it [00:00, ?it/s]Traceback (most recent call last):
  File "/Users/niko/anaconda3/envs/pyannote/bin/pyannote-speaker-embedding", line 11, in <module>
    load_entry_point('pyannote.audio', 'console_scripts', 'pyannote-speaker-embedding')()
  File "/Users/niko/pyannote_test/pyannote-audio/pyannote/audio/applications/speaker_embedding.py", line 791, in main
    internal=internal)
  File "/Users/niko/pyannote_test/pyannote-audio/pyannote/audio/applications/speaker_embedding.py", line 708, in apply
    fX = extraction.apply(current_file)
  File "/Users/niko/pyannote_test/pyannote-audio/pyannote/audio/embedding/extraction.py", line 142, in apply
    incomplete=True)])
  File "/Users/niko/pyannote_test/pyannote-audio/pyannote/audio/embedding/extraction.py", line 141, in <listcomp>
    [batch for batch in self.from_file(current_file,
  File "/Users/niko/anaconda3/envs/pyannote/lib/python3.5/site-packages/pyannote/generators/batch.py", line 379, in from_file
    incomplete=incomplete):
  File "/Users/niko/anaconda3/envs/pyannote/lib/python3.5/site-packages/pyannote/generators/batch.py", line 432, in __call__
    for fragment in self.generator.from_file(preprocessed_file):
  File "/Users/niko/anaconda3/envs/pyannote/lib/python3.5/site-packages/pyannote/generators/fragment.py", line 154, in from_file
    raise ValueError('source must be one of "annotated", "annotated_extent", "annotation", "support" or "audio"')
ValueError: source must be one of "annotated", "annotated_extent", "annotation", "support" or "audio"
```

Thanks for help!

**Comment by hbredin** [comment]
Sorry for the lag in answering... 
Did you solve your issue?  
I guess you also need to update pyannote-generators.

**Comment by nikopartanen** [comment]
I updated everything and it worked! Sorry that I didn't have enough time to get into it earlier, I think what finally got it work was to update pyannote-audio into development version. This issue can be closed now!

**Comment by hbredin** [comment]
Perfect.
