### ISSUE TITLE
Get a problem when convert onnx model

### ISSUE THREAD

**Issue by lfgogogo** [pyannote/pyannote-audio#702]
I want to convert the model to onnx model,i add the following code in pretrained.py.
![image](https://user-images.githubusercontent.com/42054022/124879969-5bd15780-e000-11eb-9118-c9fc11ae22d0.png)

I run a demo ,i think in the process of the wav file i will get onnx model,but i get error below:
C:\Users\Administrator\anaconda3\envs\diarization\python.exe D:/pyannote-audio-demo/demo/test.py
torch.Size([3111253, 2])
Traceback (most recent call last):
  File "D:/pyannote-audio-demo/demo/test.py", line 4, in <module>
    sad = Pretrained(validate_dir=r'D:\pyannote-audio-demo\models\sad\ami\712d7e3184\train\AMI.SpeakerDiarization.MixHeadset.train\validate\AMI.SpeakerDiarization.MixHeadset.development')
  File "C:\Users\Administrator\anaconda3\envs\diarization\lib\site-packages\pyannote\audio\features\pretrained.py", line 156, in __init__
    output_names=["output"]
  File "C:\Users\Administrator\anaconda3\envs\diarization\lib\site-packages\torch\onnx\__init__.py", line 276, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "C:\Users\Administrator\anaconda3\envs\diarization\lib\site-packages\torch\onnx\utils.py", line 94, in export
    use_external_data_format=use_external_data_format)
  File "C:\Users\Administrator\anaconda3\envs\diarization\lib\site-packages\torch\onnx\utils.py", line 701, in _export
    dynamic_axes=dynamic_axes)
  File "C:\Users\Administrator\anaconda3\envs\diarization\lib\site-packages\torch\onnx\utils.py", line 459, in _model_to_graph
    use_new_jit_passes)
  File "C:\Users\Administrator\anaconda3\envs\diarization\lib\site-packages\torch\onnx\utils.py", line 420, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "C:\Users\Administrator\anaconda3\envs\diarization\lib\site-packages\torch\onnx\utils.py", line 380, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
  File "C:\Users\Administrator\anaconda3\envs\diarization\lib\site-packages\torch\jit\_trace.py", line 1139, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "C:\Users\Administrator\anaconda3\envs\diarization\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\Administrator\anaconda3\envs\diarization\lib\site-packages\torch\jit\_trace.py", line 130, in forward
    self._force_outplace,
  File "C:\Users\Administrator\anaconda3\envs\diarization\lib\site-packages\torch\jit\_trace.py", line 116, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "C:\Users\Administrator\anaconda3\envs\diarization\lib\site-packages\torch\nn\modules\module.py", line 887, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "C:\Users\Administrator\anaconda3\envs\diarization\lib\site-packages\torch\nn\modules\module.py", line 860, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "C:\Users\Administrator\anaconda3\envs\diarization\lib\site-packages\pyannote\audio\models\models.py", line 540, in forward
    output = self.sincnet_(waveforms)
  File "C:\Users\Administrator\anaconda3\envs\diarization\lib\site-packages\torch\nn\modules\module.py", line 887, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "C:\Users\Administrator\anaconda3\envs\diarization\lib\site-packages\torch\nn\modules\module.py", line 860, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "C:\Users\Administrator\anaconda3\envs\diarization\lib\site-packages\pyannote\audio\models\sincnet.py", line 415, in forward
    output = waveforms.transpose(1, 2)
IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

Anyone has an idea to solve this or i do something wrong,please help,thank you!

**Comment by hbredin** [comment]
I never tried this myself so cannot really help. 

That being said, I'd recommend you try this on models trained with upcoming pyannote.audio 2.0 (available in [develop branch](https://github.com/pyannote/pyannote-audio/tree/develop)) because pyannote.audio 1.x will no longer be supported in the future...

For instance, I'd love to know whether [these pretrained models](https://hf.co/pyannote) can easily be _onnx-ified_.
