### ISSUE TITLE
No module named pyannote.audio.pipelines

### ISSUE THREAD

**Issue by danaiksez** [pyannote/pyannote-audio#707]
Hi,

I have installed pyannote audio through pip in both Linux and macOS environments, but when I run in python `from pyannote.audio.pipelines import OverlappedSpeechDetection` I get this error:

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pyannote.audio.pipelines'`

I also tried to clone the repo but there is no OverlappedSpeechDetection class in the 'master' branch, it seems to exist only at 'develop' branch. Is there anything I am missing there? Any clarification would be really helpful.

Thanks a lot!

**Comment by dimuthuanuraj** [comment]
@danaiksez Hi, I had the same problem, It can be solved by changing **_piplines_** to **_pipline_**.

Let me know if it working for you.

Thank you.

**Comment by danaiksez** [comment]
Hi, thanks for the response!

I changed pipelines to pipeline as you suggested, and the error now is:

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'OverlappedSpeechDetection' from 'pyannote.audio.pipeline' (/Users/danaiksez/miniconda3/lib/python3.8/site-packages/pyannote/audio/pipeline/__init__.py)
`

I tried to uninstall pyannote and install it again but it didn't work. Is there anything else that you think I should try? Any guidance would be very helpful.

**Comment by SPDAnuraj** [comment]
Hi @danaiksez, 

Sorry for the late response, I think _**OverlappedSpeechDetection**_  is a change to need to **_overlap_detection_**. So changing the import name as **_OverlappedSpeechDetection_** to  **_overlap_detection_**  will solve your problem. 

Let me know if it is working for you.
Thank you.
