### ISSUE TITLE
'WindowsPath'/'PosixPath' object has no attribute 'format'

### ISSUE THREAD

**Issue by RickyGunawan09** [pyannote/pyannote-audio#708]
I tried to finetune with my own dataset in local windows and in colab. i already follow your step in data preparation and finetune. 

i run this code for finetuned:
!pyannote-audio scd train --pretrained=scd_dihard --subset=train --to=5 --parallel=4 "/content/drive/MyDrive/finetuned" WAV.SpeakerDiarization.MixHeadset

than i get this error in colab:
`Using cache found in /root/.cache/torch/hub/pyannote_pyannote-audio_master
Loading labels: 0file [00:00, ?file/s]Traceback (most recent call last):
  File "/usr/local/bin/pyannote-audio", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/pyannote/audio/applications/pyannote_audio.py", line 364, in main
    app.train(protocol, **params)
  File "/usr/local/lib/python3.7/dist-packages/pyannote/audio/applications/base.py", line 210, in train
    alignment=self.model_alignment_,
  File "/usr/local/lib/python3.7/dist-packages/pyannote/audio/labeling/tasks/speaker_change_detection.py", line 276, in get_batch_generator
    per_epoch=self.per_epoch,
  File "/usr/local/lib/python3.7/dist-packages/pyannote/audio/labeling/tasks/speaker_change_detection.py", line 133, in __init__
    local_labels=True,
  File "/usr/local/lib/python3.7/dist-packages/pyannote/audio/labeling/tasks/base.py", line 154, in __init__
    total_duration = self._load_metadata(protocol, subset=subset)
  File "/usr/local/lib/python3.7/dist-packages/pyannote/audio/labeling/tasks/base.py", line 290, in _load_metadata
    for current_file in tqdm(files, desc="Loading labels", unit="file"):
  File "/usr/local/lib/python3.7/dist-packages/tqdm/std.py", line 1104, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.7/dist-packages/pyannote/database/protocol/protocol.py", line 363, in subset_helper
    yield self.preprocess(file)
  File "/usr/local/lib/python3.7/dist-packages/pyannote/database/protocol/protocol.py", line 329, in preprocess
    return ProtocolFile(current_file, lazy=self.preprocessors)
  File "/usr/local/lib/python3.7/dist-packages/pyannote/database/protocol/protocol.py", line 87, in __init__
    self._store[key] = precomputed[key]
  File "/usr/local/lib/python3.7/dist-packages/pyannote/database/protocol/protocol.py", line 122, in __getitem__
    value = self.lazy[key](self)
  File "/usr/local/lib/python3.7/dist-packages/pyannote/database/loader.py", line 128, in __call__
    loaded = load_rttm(self.path.format(**sub_file))
AttributeError: 'PosixPath' object has no attribute 'format'
Loading labels: 0file [00:00, ?file/s]`

in windows:
AttributeError: 'WindowsPath' object has no attribute 'format'

my database.yml
![image](https://user-images.githubusercontent.com/65578014/125740404-d56bb524-5ca9-4e8c-959e-985e1aeb6069.png)

can you please help me ? it's my database.yml wrong ?

pyannote.audio==1.1.2

**Comment by RickyGunawan09** [comment]
i referance with the wrong file. this case closed now
