### ISSUE TITLE
Can't list pretrained models 

### ISSUE THREAD

**Issue by picheny-nyu** [pyannote/pyannote-audio#761]
**Describe the bug**
I am trying to list the pretrained models in pyannote as I was having trouble loading one of them. I can't list them, either. 

**To Reproduce**
python 3.9
pytorch 1.9
pyannote 1.1.2

Here is the output. What might I be doing wrong? 

Thanks
Michael

>>> import torch
>>> torch.hub.list('pyannote/pyannote-audio')
Downloading: "https://github.com/pyannote/pyannote-audio/archive/master.zip" to /home/map22/.cache/torch/hub/master.zip
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ext3/miniconda3/envs/pyannote5/lib/python3.9/site-packages/torch/hub.py", line 280, in list
    hub_module = import_module(MODULE_HUBCONF, repo_dir + '/' + MODULE_HUBCONF)
  File "/ext3/miniconda3/envs/pyannote5/lib/python3.9/site-packages/torch/hub.py", line 76, in import_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/map22/.cache/torch/hub/pyannote_pyannote-audio_master/hubconf.py", line 37, in <module>
    from pyannote.audio.features import Pretrained as _Pretrained
  File "/ext3/miniconda3/envs/pyannote5/lib/python3.9/site-packages/pyannote/audio/features/__init__.py", line 33, in <module>
    from .base import FeatureExtraction
  File "/ext3/miniconda3/envs/pyannote5/lib/python3.9/site-packages/pyannote/audio/features/base.py", line 32, in <module>
    from .utils import RawAudio
  File "/ext3/miniconda3/envs/pyannote5/lib/python3.9/site-packages/pyannote/audio/features/utils.py", line 32, in <module>
    import librosa
  File "/ext3/miniconda3/envs/pyannote5/lib/python3.9/site-packages/librosa/__init__.py", line 211, in <module>
    from . import core
  File "/ext3/miniconda3/envs/pyannote5/lib/python3.9/site-packages/librosa/core/__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "/ext3/miniconda3/envs/pyannote5/lib/python3.9/site-packages/librosa/core/convert.py", line 7, in <module>
    from . import notation
  File "/ext3/miniconda3/envs/pyannote5/lib/python3.9/site-packages/librosa/core/notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "/ext3/miniconda3/envs/pyannote5/lib/python3.9/site-packages/librosa/util/__init__.py", line 83, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "/ext3/miniconda3/envs/pyannote5/lib/python3.9/site-packages/librosa/util/utils.py", line 6, in <module>
    import scipy.ndimage
  File "/ext3/miniconda3/envs/pyannote5/lib/python3.9/site-packages/scipy/ndimage/__init__.py", line 153, in <module>
    from .interpolation import *
  File "/ext3/miniconda3/envs/pyannote5/lib/python3.9/site-packages/scipy/ndimage/interpolation.py", line 37, in <module>
    from scipy import special
  File "/ext3/miniconda3/envs/pyannote5/lib/python3.9/site-packages/scipy/special/__init__.py", line 643, in <module>
    from . import _ufuncs
ImportError: /ext3/miniconda3/envs/pyannote5/lib/python3.9/site-packages/scipy/special/_ufuncs.cpython-39-x86_64-linux-gnu.so: cannot read file data

```

**Comment by hbredin** [comment]
Looks like a problem in your environment.
Does `import librosa`work?
