### ISSUE TITLE
Does speaker diarization work properly in pyannote-audio 2.0?

### ISSUE THREAD

**Issue by albyho** [pyannote/pyannote-audio#830]
``` python
from pyannote.audio.pipelines import SpeakerDiarization

CONFIG = {
    "segmentation": "pyannote/segmentation",
    "embedding": "speechbrain/spkrec-ecapa-voxceleb",
    "clustering": "AgglomerativeClustering"
}
PARAMS = {
    "onset": 0.5, "offset": 0.5,
    "stitch_threshold": 0.04, "min_activity": 6.0,
    "clustering": {"method": "average", "threshold": 0.595}
}

pipeline = SpeakerDiarization(**CONFIG).instantiate(PARAMS)
dia = pipeline("test.wav") #  The duration of the wav file 15s.
print(dia)
```

``` sh
time python test-01.py
  rank_zero_deprecation(
^CTraceback (most recent call last):
  File "test-01.py", line 15, in <module>
    dia = pipeline("test.wav")
  File "/Users/alby/opt/anaconda3/envs/pyannote/lib/python3.8/site-packages/pyannote/audio/core/pipeline.py", line 212, in __call__
    return self.apply(file, **kwargs)
  File "/Users/alby/opt/anaconda3/envs/pyannote/lib/python3.8/site-packages/pyannote/audio/pipelines/speaker_diarization.py", line 344, in apply
    embedding_batch: np.ndarray = self._embedding(
  File "/Users/alby/opt/anaconda3/envs/pyannote/lib/python3.8/site-packages/pyannote/audio/pipelines/speaker_verification.py", line 150, in __call__
    self.classifier_.encode_batch(signals, wav_lens=wav_lens)
  File "/Users/alby/opt/anaconda3/envs/pyannote/lib/python3.8/site-packages/speechbrain/pretrained/interfaces.py", line 680, in encode_batch
    embeddings = self.modules.embedding_model(feats, wav_lens)
  File "/Users/alby/opt/anaconda3/envs/pyannote/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/alby/opt/anaconda3/envs/pyannote/lib/python3.8/site-packages/speechbrain/lobes/models/ECAPA_TDNN.py", line 475, in forward
    x = self.asp(x, lengths=lengths)
  File "/Users/alby/opt/anaconda3/envs/pyannote/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/alby/opt/anaconda3/envs/pyannote/lib/python3.8/site-packages/speechbrain/lobes/models/ECAPA_TDNN.py", line 260, in forward
    attn = self.conv(self.tanh(self.tdnn(attn)))
  File "/Users/alby/opt/anaconda3/envs/pyannote/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/alby/opt/anaconda3/envs/pyannote/lib/python3.8/site-packages/speechbrain/lobes/models/ECAPA_TDNN.py", line 72, in forward
    return self.norm(self.activation(self.conv(x)))
  File "/Users/alby/opt/anaconda3/envs/pyannote/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/alby/opt/anaconda3/envs/pyannote/lib/python3.8/site-packages/speechbrain/nnet/CNN.py", line 412, in forward
    wx = self.conv(x)
  File "/Users/alby/opt/anaconda3/envs/pyannote/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/alby/opt/anaconda3/envs/pyannote/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 301, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/Users/alby/opt/anaconda3/envs/pyannote/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 297, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
KeyboardInterrupt

python test-01.py  13.61s user 1.84s system 78% cpu 19.706 total
```

Hang  when call `_conv_forward`.

**Comment by albyho** [comment]
My CPU is shit!
