### ISSUE TITLE
Fine tune model error "TypeError: cannot pickle '_thread.RLock' object"

### ISSUE THREAD

**Issue by dingyic1** [pyannote/pyannote-audio#904]
**Describe the bug**
When I try to fine-tune the segmentation model Following with tutorial, I got this error.

**pyannote environment**

```bash
pyannote-audio            0.0.1                    pypi_0    pypi
pyannote-core             4.3                      pypi_0    pypi
pyannote-database         4.1.1                    pypi_0    pypi
pyannote-metrics          3.2                      pypi_0    pypi
pyannote-pipeline         2.2                      pypi_0    pypi

Python 3.9
OS: Windows
```

**Additional context**

ami = DataLoader()
    # Test_file dataset
    test_file = next(ami.test())

    # import pretrained model
    pretrained = Model.from_pretrained("pyannote/segmentation")
    spk_probability = Inference(pretrained, step=2.5)(test_file)
    print(spk_probability)

    seg_task = Segmentation(ami, duration=5.0, max_num_speakers=4)

    finetuned = deepcopy(pretrained)
    finetuned.task = seg_task

    trainer = pl.Trainer(gpus=1, max_epochs=1, auto_select_gpus=True)
    trainer.fit(finetuned)

Traceback (most recent call last):
  File "E:\MSULinguisticsCapstone\PyannoteProj\data_preparation\voice_detect.py", line 54, in <module>
    trainer.fit(finetuned)
  File "C:\Users\eason\anaconda3\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 740, in fit
    self._call_and_handle_interrupt(
  File "C:\Users\eason\anaconda3\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 685, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "C:\Users\eason\anaconda3\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 777, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "C:\Users\eason\anaconda3\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1199, in _run
    self._dispatch()
  File "C:\Users\eason\anaconda3\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1279, in _dispatch
    self.training_type_plugin.start_training(self)
  File "C:\Users\eason\anaconda3\lib\site-packages\pytorch_lightning\plugins\training_type\training_type_plugin.py", line 202, in start_training
    self._results = trainer.run_stage()
  File "C:\Users\eason\anaconda3\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1289, in run_stage
    return self._run_train()
  File "C:\Users\eason\anaconda3\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1311, in _run_train
    self._run_sanity_check(self.lightning_module)
  File "C:\Users\eason\anaconda3\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1375, in _run_sanity_check
    self._evaluation_loop.run()
  File "C:\Users\eason\anaconda3\lib\site-packages\pytorch_lightning\loops\base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "C:\Users\eason\anaconda3\lib\site-packages\pytorch_lightning\loops\dataloader\evaluation_loop.py", line 110, in advance
    dl_outputs = self.epoch_loop.run(dataloader, dataloader_idx, dl_max_batches, self.num_dataloaders)
  File "C:\Users\eason\anaconda3\lib\site-packages\pytorch_lightning\loops\base.py", line 140, in run
    self.on_run_start(*args, **kwargs)
  File "C:\Users\eason\anaconda3\lib\site-packages\pytorch_lightning\loops\epoch\evaluation_epoch_loop.py", line 86, in on_run_start
    self._dataloader_iter = _update_dataloader_iter(data_fetcher, self.batch_progress.current.ready)
  File "C:\Users\eason\anaconda3\lib\site-packages\pytorch_lightning\loops\utilities.py", line 121, in _update_dataloader_iter
    dataloader_iter = enumerate(data_fetcher, batch_idx)
  File "C:\Users\eason\anaconda3\lib\site-packages\pytorch_lightning\utilities\fetching.py", line 197, in __iter__
    self.dataloader_iter = iter(self.dataloader)
  File "C:\Users\eason\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "C:\Users\eason\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\eason\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 918, in __init__
    w.start()
  File "C:\Users\eason\anaconda3\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\eason\anaconda3\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\eason\anaconda3\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\eason\anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\eason\anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle '_thread.RLock' object
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\eason\anaconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\eason\anaconda3\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

**Comment by hbredin** [comment]
Unfortunately, `pyannote.audio` does not support nor is tested for Windows.
That being said, you may want to try with different `strategy` option for the `trainer`. 
See https://devblog.pytorchlightning.ai/announcing-the-new-lightning-trainer-strategy-api-f70ad5f9857e

**Comment by dingyic1** [comment]
I was trying to move all my scripts into WSL os and it shows the error like this:


Traceback (most recent call last):
  File "voice_detect.py", line 54, in <module>
    trainer.fit(finetuned)
  File "/home/eason/anaconda3/envs/pyannote/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 740, in fit
    self._call_and_handle_interrupt(
  File "/home/eason/anaconda3/envs/pyannote/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 685, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/eason/anaconda3/envs/pyannote/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 777, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/eason/anaconda3/envs/pyannote/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1199, in _run
    self._dispatch()
  File "/home/eason/anaconda3/envs/pyannote/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1279, in _dispatch
    self.training_type_plugin.start_training(self)
  File "/home/eason/anaconda3/envs/pyannote/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 202, in start_training
    self._results = trainer.run_stage()
  File "/home/eason/anaconda3/envs/pyannote/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1289, in run_stage
    return self._run_train()
  File "/home/eason/anaconda3/envs/pyannote/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1319, in _run_train
    self.fit_loop.run()
  File "/home/eason/anaconda3/envs/pyannote/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/home/eason/anaconda3/envs/pyannote/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 234, in advance
    self.epoch_loop.run(data_fetcher)
  File "/home/eason/anaconda3/envs/pyannote/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/home/eason/anaconda3/envs/pyannote/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 156, in advance
    batch_idx, (batch, self.batch_progress.is_last_batch) = next(self._dataloader_iter)
  File "/home/eason/anaconda3/envs/pyannote/lib/python3.8/site-packages/pytorch_lightning/utilities/fetching.py", line 203, in __next__
    return self.fetching_function()
  File "/home/eason/anaconda3/envs/pyannote/lib/python3.8/site-packages/pytorch_lightning/utilities/fetching.py", line 270, in fetching_function
    self._fetch_next_batch()
  File "/home/eason/anaconda3/envs/pyannote/lib/python3.8/site-packages/pytorch_lightning/utilities/fetching.py", line 300, in _fetch_next_batch
    batch = next(self.dataloader_iter)
  File "/home/eason/anaconda3/envs/pyannote/lib/python3.8/site-packages/pytorch_lightning/trainer/supporters.py", line 550, in __next__
    return self.request_next_batch(self.loader_iters)
  File "/home/eason/anaconda3/envs/pyannote/lib/python3.8/site-packages/pytorch_lightning/trainer/supporters.py", line 562, in request_next_batch
    return apply_to_collection(loader_iters, Iterator, next)
  File "/home/eason/anaconda3/envs/pyannote/lib/python3.8/site-packages/pytorch_lightning/utilities/apply_func.py", line 95, in apply_to_collection
    return function(data, *args, **kwargs)
  File "/home/eason/anaconda3/envs/pyannote/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/eason/anaconda3/envs/pyannote/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1183, in _next_data
    return self._process_data(data)
  File "/home/eason/anaconda3/envs/pyannote/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/eason/anaconda3/envs/pyannote/lib/python3.8/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 3.
Original Traceback (most recent call last):
  File "/home/eason/anaconda3/envs/pyannote/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/eason/anaconda3/envs/pyannote/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 32, in fetch
    data.append(next(self.dataset_iter))
  File "/home/eason/anaconda3/envs/pyannote/lib/python3.8/site-packages/pyannote/audio/tasks/segmentation/mixins.py", line 366, in train__iter__
    other_sample = next(chunks)
  File "/home/eason/anaconda3/envs/pyannote/lib/python3.8/site-packages/pyannote/audio/tasks/segmentation/mixins.py", line 306, in train__iter__helper
    yield self.prepare_chunk(file, chunk, duration=self.duration, stage="train")
  File "/home/eason/anaconda3/envs/pyannote/lib/python3.8/site-packages/pyannote/audio/tasks/segmentation/mixins.py", line 192, in prepare_chunk
    sample["X"], _ = self.model.audio.crop(
  File "/home/eason/anaconda3/envs/pyannote/lib/python3.8/site-packages/pyannote/audio/core/io.py", line 342, in crop
    raise ValueError(
ValueError: requested chunk [1476.524621, 1481.524621] (23624393:23704393) lies outside of file bounds [0., 804.862625] (0:12877802).
