### ISSUE TITLE
Load own fine tuned model

### ISSUE THREAD

**Issue by dingyic1** [pyannote/pyannote-audio#930]
**Describe the bug**
Hi, Since I just fine-tuned the segmentation model and save it as a file named "000.pt". Then When I try to re-add it into:
```
pipeline = pipelines.SpeakerDiarization(segmentation="path/to/000.pt",
                                                                embedding="pyannote/embedding",
                                                                embedding_batch_size=32)
```

I got this error:

```Traceback (most recent call last):
  File "E:/MSULinguisticsCapstone/PyannoteProj/data_preparation/OptimizingHyperParameter.py", line 6, in <module>
    pipeline = pipelines.SpeakerDiarization(segmentation="saved_model/segmentation/new_segmentation_model.pt",
  File "C:\Users\eason\anaconda3\envs\MSULinguisticsCapstone\lib\site-packages\pyannote\audio\pipelines\speaker_diarization.py", line 112, in __init__
    model: Model = get_model(segmentation)
  File "C:\Users\eason\anaconda3\envs\MSULinguisticsCapstone\lib\site-packages\pyannote\audio\pipelines\utils.py", line 73, in get_model
    model = Model.from_pretrained(model, strict=False)
  File "C:\Users\eason\anaconda3\envs\MSULinguisticsCapstone\lib\site-packages\pyannote\audio\core\model.py", line 821, in from_pretrained
    module_name: str = loaded_checkpoint["pyannote.audio"]["architecture"]["module"]
IndexError: invalid index to scalar variable.
```

**Comment by dingyic1** [comment]
anyone have an idea. I have been stucked on this problem for long time
