### ISSUE TITLE
Syntax Error when pyannote-change-detection -h

### ISSUE THREAD

**Issue by lordzuko** [pyannote/pyannote-audio#95]
I am getting following error: 
gcc: 4.9.4
OS: Ubuntu 14.04

Can anyone tell, how to fix this ?

```
(speaker-diarization) himanshu@StaquResearch2:~/virtualenv/speaker-diarization/speaker/change_detection$ pyannote-change-detection -h
Using Theano backend.
/home/himanshu/virtualenv/speaker-diarization/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/home/himanshu/virtualenv/speaker-diarization/bin/pyannote-change-detection", line 7, in <module>
    from pyannote.audio.applications.change_detection import main
  File "/home/himanshu/virtualenv/speaker-diarization/lib/python3.5/site-packages/pyannote/audio/applications/change_detection.py", line 137, in <module>
    from pyannote.audio.generators.change import ChangeDetectionBatchGenerator
  File "/home/himanshu/virtualenv/speaker-diarization/lib/python3.5/site-packages/pyannote/audio/generators/change.py", line 1, in <module>
    from pyannote.audio.generators.periodic import PeriodicFeaturesMixin
  File "/home/himanshu/virtualenv/speaker-diarization/lib/python3.5/site-packages/pyannote/audio/generators/periodic.py", line 33, in <module>
    from pyannote.audio.features.utils import PyannoteFeatureExtractionError
  File "/home/himanshu/virtualenv/speaker-diarization/lib/python3.5/site-packages/pyannote/audio/features/__init__.py", line 33, in <module>
    from .with_librosa import LibrosaMFCC
  File "/home/himanshu/virtualenv/speaker-diarization/lib/python3.5/site-packages/pyannote/audio/features/with_librosa.py", line 41, in <module>
    from pyannote.audio.features.utils import PyannoteFeatureExtractionError
  File "/home/himanshu/virtualenv/speaker-diarization/lib/python3.5/site-packages/pyannote/audio/features/utils.py", line 39, in <module>
    from pyannote.database.util import get_unique_identifier
  File "/home/himanshu/virtualenv/speaker-diarization/lib/python3.5/site-packages/pyannote/database/__init__.py", line 37, in <module>
    from .database import Database
  File "/home/himanshu/virtualenv/speaker-diarization/lib/python3.5/site-packages/pyannote/database/database.py", line 30, in <module>
    from .util import PyannoteDatabaseException
  File "/home/himanshu/virtualenv/speaker-diarization/lib/python3.5/site-packages/pyannote/database/util.py", line 146
    methods.append(f'{subset}{suffix}')
                                     ^
SyntaxError: invalid syntax

```

**Comment by hbredin** [comment]
This problem is due to pyannote.database, not pyannote.audio.
It uses a syntax introduced in Python 3.6.
Therefore, switching to Python 3.6 should solve your issue.
