### ISSUE TITLE
Segmentation fault on import Pipeline when installed alongside transformers >= 4.0 from pip

### ISSUE THREAD

**Issue by guillermo-gabrielli-fer** [pyannote/pyannote-audio#963]
**Describe the bug**

When the package transformers >= 4.0 is installed on the same environment a segmentation fault happens when the following line is  executed:

`from pyannote.audio import Pipeline`

This behaviour didn't happen when transformers is installed from conda.

**To Reproduce**

Install environment and transformers >= 4.0 from pip

```
conda create -n pyannote python=3.8
conda activate pyannote
conda install pytorch torchaudio -c pytorch
pip install https://github.com/pyannote/pyannote-audio/archive/develop.zip
pip install speechbrain
pip install transformers
```

Run code:

```
import faulthandler

faulthandler.enable()

from pyannote.audio import Pipeline
```

Faulthandler traces the segmentation fault to the import Pipeline line

**pyannote environment**

`pip freeze | grep pyannote`

```
pyannote.audio @ https://github.com/pyannote/pyannote-audio/archive/develop.zip
pyannote.core==4.4
pyannote.database==4.1.3
pyannote.metrics==3.2
pyannote.pipeline==2.2
```

Does anyone else had this issue?

**Comment by hbredin** [comment]
Please provide a minimum reproducible example that I can run easily (e.g. a Google Colab).

**Comment by danielezhu** [comment]
I'm also facing the segmentation fault issue caused by the import statement. However, in my case, I don't even have transformers installed. I'm running python 3.9.12, but otherwise followed the installation instructions from the repo exactly as written:
`conda install pytorch torchaudio -c pytorch
pip install https://github.com/pyannote/pyannote-audio/archive/develop.zip`


Traceback (most recent call last):
  File "/home/ubuntu/Code/pyannote.py", line 3, in <module>
    from pyannote.audio import Pipeline
  File "/home/ubuntu/anaconda/lib/python3.9/site-packages/pyannote/audio/__init__.py", line 29, in <module>
    from .core.inference import Inference
  File "/home/ubuntu/anaconda/lib/python3.9/site-packages/pyannote/audio/core/inference.py", line 34, in <module>
    from pyannote.audio.core.model import Model
  File "/home/ubuntu/anaconda/lib/python3.9/site-packages/pyannote/audio/core/model.py", line 45, in <module>
    from pyannote.audio.core.task import Problem, Resolution, Specifications, Task
  File "/home/ubuntu/anaconda/lib/python3.9/site-packages/pyannote/audio/core/task.py", line 45, in <module>
    from torch_audiomentations import Identity
  File "/home/ubuntu/anaconda/lib/python3.9/site-packages/torch_audiomentations/__init__.py", line 1, in <module>
    from .augmentations.background_noise import AddBackgroundNoise
  File "/home/ubuntu/anaconda/lib/python3.9/site-packages/torch_audiomentations/augmentations/background_noise.py", line 11, in <module>
    from ..utils.io import Audio
  File "/home/ubuntu/anaconda/lib/python3.9/site-packages/torch_audiomentations/utils/io.py", line 5, in <module>
    import librosa
  File "/home/ubuntu/anaconda/lib/python3.9/site-packages/librosa/__init__.py", line 209, in <module>
    from . import core
  File "/home/ubuntu/anaconda/lib/python3.9/site-packages/librosa/core/__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "/home/ubuntu/anaconda/lib/python3.9/site-packages/librosa/core/convert.py", line 7, in <module>
    from . import notation
  File "/home/ubuntu/anaconda/lib/python3.9/site-packages/librosa/core/notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "/home/ubuntu/anaconda/lib/python3.9/site-packages/librosa/util/__init__.py", line 77, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "/home/ubuntu/anaconda/lib/python3.9/site-packages/librosa/util/utils.py", line 1879, in <module>
    def __shear_dense(X, *, factor=+1, axis=-1):
  File "/home/ubuntu/anaconda/lib/python3.9/site-packages/numba/core/decorators.py", line 208, in wrapper
    disp = dispatcher(py_func=func, locals=locals,
  File "/home/ubuntu/anaconda/lib/python3.9/site-packages/numba/core/dispatcher.py", line 824, in __init__
    self.targetctx = self.targetdescr.target_context
  File "/home/ubuntu/anaconda/lib/python3.9/site-packages/numba/core/registry.py", line 47, in target_context
    return self._toplevel_target_context
  File "/home/ubuntu/anaconda/lib/python3.9/functools.py", line 993, in __get__
    val = self.func(instance)
  File "/home/ubuntu/anaconda/lib/python3.9/site-packages/numba/core/registry.py", line 31, in _toplevel_target_context
    return cpu.CPUContext(self.typing_context, self._target_name)
  File "/home/ubuntu/anaconda/lib/python3.9/site-packages/numba/core/cpu.py", line 41, in __init__
    super().__init__(typingctx, target)
  File "/home/ubuntu/anaconda/lib/python3.9/site-packages/numba/core/base.py", line 262, in __init__
    self.init()
  File "/home/ubuntu/anaconda/lib/python3.9/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda/lib/python3.9/site-packages/numba/core/cpu.py", line 50, in init
    self._internal_codegen = codegen.JITCPUCodegen("numba.exec")
  File "/home/ubuntu/anaconda/lib/python3.9/site-packages/numba/core/codegen.py", line 1172, in __init__
    self._init(self._llvm_module)
  File "/home/ubuntu/anaconda/lib/python3.9/site-packages/numba/core/codegen.py", line 1177, in _init
    target = ll.Target.from_triple(ll.get_process_triple())
  File "/home/ubuntu/anaconda/lib/python3.9/site-packages/llvmlite/binding/targets.py", line 197, in from_triple
    raise RuntimeError(str(outerr))
RuntimeError: Unable to find target for this triple (no targets are registered)
Segmentation fault (core dumped)

**Comment by Daksitha** [comment]
Were you able to find a solution for this ?

**Comment by fabiocat93** [comment]
> **Describe the bug**
> 
> When the package transformers >= 4.0 is installed on the same environment a segmentation fault happens when the following line is executed:
> 
> `from pyannote.audio import Pipeline`
> 
> This behaviour didn't happen when transformers is installed from conda.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> Install environment and transformers >= 4.0 from pip
> 
> ```
> conda create -n pyannote python=3.8
> conda activate pyannote
> conda install pytorch torchaudio -c pytorch
> pip install https://github.com/pyannote/pyannote-audio/archive/develop.zip
> pip install speechbrain
> pip install transformers
> ```
> 
> Run code:
> 
> ```
> import faulthandler
> 
> faulthandler.enable()
> 
> from pyannote.audio import Pipeline
> ```
> 
> Faulthandler traces the segmentation fault to the import Pipeline line
> 
> **pyannote environment**
> 
> `pip freeze | grep pyannote`
> 
> ```
> pyannote.audio @ https://github.com/pyannote/pyannote-audio/archive/develop.zip
> pyannote.core==4.4
> pyannote.database==4.1.3
> pyannote.metrics==3.2
> pyannote.pipeline==2.2
> ```
> 
> Does anyone else had this issue?

@guillermo-gabrielli-fer were you able to find any solution to this issue? If yes, do you mind sharing?
