### ISSUE TITLE
requested chunk lies outside of file bounds

### ISSUE THREAD

**Issue by moodeerf** [pyannote/pyannote-audio#984]
Hi! When I learn to train with **pyannote.audio** according to [https://github.com/pyannote/pyannote-audio/blob/develop/tutorials/training_a_model.ipynb](url) , I encountered a problem as follows：
Traceback (most recent call last):
  File "train_vad.py", line 31, in <module>
    trainer.fit(model)
  File "/root/miniconda3/envs/pyannote/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 768, in fit
    self._call_and_handle_interrupt(
  File "/root/miniconda3/envs/pyannote/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 721, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/root/miniconda3/envs/pyannote/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 809, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/root/miniconda3/envs/pyannote/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1234, in _run
    results = self._run_stage()
  File "/root/miniconda3/envs/pyannote/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1321, in _run_stage
    return self._run_train()
  File "/root/miniconda3/envs/pyannote/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1351, in _run_train
    self.fit_loop.run()
  File "/root/miniconda3/envs/pyannote/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/root/miniconda3/envs/pyannote/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 268, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/root/miniconda3/envs/pyannote/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/root/miniconda3/envs/pyannote/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 171, in advance
    batch = next(data_fetcher)
  File "/root/miniconda3/envs/pyannote/lib/python3.8/site-packages/pytorch_lightning/utilities/fetching.py", line 184, in __next__
    return self.fetching_function()
  File "/root/miniconda3/envs/pyannote/lib/python3.8/site-packages/pytorch_lightning/utilities/fetching.py", line 259, in fetching_function
    self._fetch_next_batch(self.dataloader_iter)
  File "/root/miniconda3/envs/pyannote/lib/python3.8/site-packages/pytorch_lightning/utilities/fetching.py", line 273, in _fetch_next_batch
    batch = next(iterator)
  File "/root/miniconda3/envs/pyannote/lib/python3.8/site-packages/pytorch_lightning/trainer/supporters.py", line 553, in __next__
    return self.request_next_batch(self.loader_iters)
  File "/root/miniconda3/envs/pyannote/lib/python3.8/site-packages/pytorch_lightning/trainer/supporters.py", line 565, in request_next_batch
    return apply_to_collection(loader_iters, Iterator, next)
  File "/root/miniconda3/envs/pyannote/lib/python3.8/site-packages/pytorch_lightning/utilities/apply_func.py", line 99, in apply_to_collection
    return function(data, *args, **kwargs)
  File "/root/miniconda3/envs/pyannote/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/root/miniconda3/envs/pyannote/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1204, in _next_data
    return self._process_data(data)
  File "/root/miniconda3/envs/pyannote/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/root/miniconda3/envs/pyannote/lib/python3.8/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 1.
**Original Traceback (most recent call last):
  File "/root/miniconda3/envs/pyannote/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/miniconda3/envs/pyannote/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 32, in fetch
    data.append(next(self.dataset_iter))
  File "/root/miniconda3/envs/pyannote/lib/python3.8/site-packages/pyannote/audio/tasks/segmentation/mixins.py", line 269, in train__iter__
    yield next(chunks)
  File "/root/miniconda3/envs/pyannote/lib/python3.8/site-packages/pyannote/audio/tasks/segmentation/mixins.py", line 232, in train__iter__helper
    yield self.prepare_chunk(file, chunk, duration=self.duration)
  File "/root/miniconda3/envs/pyannote/lib/python3.8/site-packages/pyannote/audio/tasks/segmentation/mixins.py", line 171, in prepare_chunk
    sample["X"], _ = self.model.audio.crop(file, chunk, duration=duration)
  File "/root/miniconda3/envs/pyannote/lib/python3.8/site-packages/pyannote/audio/core/io.py", line 367, in crop
    raise ValueError(
ValueError: requested chunk [1600.748792, 1620.748792] (25611980:25931980) lies outside of file bounds [0., 590.334625] (0:9445354).**
My code is as follows:
![image](https://user-images.githubusercontent.com/43941697/169188724-cbd079be-2d78-454d-8403-f9dfd660ac4e.png)

Is there any problem in it? Thank you so much for taking the time to look at this issue

**Comment by hbredin** [comment]
Looks like a file is shorter than it should be.

Can you install from [this branch](https://github.com/pyannote/pyannote-audio/tree/issue/984) in which I added more context to the error message?
In particular, the error message should now let you know for which file this problem occurs.

**Comment by moodeerf** [comment]
It's the ES2002c which is shorter than it should be.   I removed this file and solved  the above problem. Thank you very much !
